### ISSUE TITLE
Two instatnces of touchegg possible ?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JoseExposito/touchegg#194]
```
I own an Asus aspire V5 with touchscreen and touchpad and want to configure 
different actions for the input devices - eg. scroll normal for touchscreen ant 
inverted for touchpad - is it possible?
```

Original issue reported on code.google.com by `daniel.k...@gmail.com` on 12 Feb 2013 at 8:08

**Comment by superscript18** [comment]
Is this blocked because of an upstream (geis?) problem or is it a feature that might be added with someone willing to do it?
