### ISSUE TITLE
3 finger drag to select (apple magic trackpad)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JoseExposito/touchegg#233]
```
Using Linux, to "select-text" with an Apple magic trackpad I need to press down 
hard with a single finger and then drag without letting the pad's hard button 
unclick.  This is an awkward motion.  Many people recommend using a three 
finger drag to select instead.  Is this possible with touchegg?

something like:

<gesture type="DRAG" fingers="3" direction="ALL">
   <action type="MOUSE_HOLD????">BUTTON=1</action>
</gesture>

thank you!
```

Original issue reported on code.google.com by `r...@verifaction.co.za` on 5 Mar 2014 at 8:52

**Comment by kramer65** [comment]
@GoogleCodeExporter - So you gave up? Why isn't it possible to make this precise if it is in fact possible on a Mac?

**Comment by luyanfeng** [comment]
You can use Touchégg together with fusuma. I do

**Comment by JoseExposito** [comment]
libinput supports this now, it is possible to do it without any additional tool:
https://www.reddit.com/r/linux/comments/1ix1tuz/linuxs_libinput_input_library_finally_supports/

**Comment by luyanfeng** [comment]
> libinput supports this now, it is possible to do it without any additional tool: https://www.reddit.com/r/linux/comments/1ix1tuz/linuxs_libinput_input_library_finally_supports/

How do I configure this to take effect? I'm using Ubuntu 24.04 with GNOME
