### ISSUE TITLE
Package uTouch is no longer Available.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JoseExposito/touchegg#238]
```
The Package uTouch is not longer available for download/Install.
In the Ubuntu Package list there is an Package named: 

xserver-xorg-input-mutouch

Touchegg doesn't Support this Package so i got the Problem that i can't 
install / use Touchegg.

Is it possible to run Touchegg with the Package?

Thanks for Help
```

Original issue reported on code.google.com by `horvatke...@gmail.com` on 15 May 2014 at 12:40

**Comment by Stezizzi** [comment]
Hi Jose, 
I am trying to compile touchegg  in Raspbian Buster, and the result is same as above: 
unable to locate package utouch and package libgeis-dev
Do you have any suggestion to go on with compiling touchegg?
Many thanks for your help
Stefano
