### ISSUE TITLE
Problem with acer Aspire S7 393 and linux mint

### ISSUE THREAD

**Issue by Laval429** [JoseExposito/touchegg#256]
Hi,

I tried to make the trackpad of my new laptop to recognize the multi-touch features (mostly for the two finger scroll) and tried to use touchégg but without success.

I'm running a fresh new install of linux mint with Cinnamon and I followed this tutorial: http://community.linuxmint.com/tutorial/view/1884 appart from the compiz part 
I also tried to compile it while following this guide: http://forums.linuxmint.com/viewtopic.php?t=128971&f=42
I added "/usr/bin/touchegg" in the programs lauched at startup.
then I tried to change the xorg.conf file (I created it actually) with the Acer Aspire One D255 config from this page: https://code.google.com/p/touchegg/wiki/ConfigureDevices
From this point the touchpad stopped to work at all.
I then tried to install  libinput-pad1 in case a driver was missing but it didn't change anything the trackpad was still not working at all.
Finally I removed the xorg.conf file and it came back like before. Trackpad working, no multi-touch, no scroll

I was wondering if compiz is required since it can only work with Mate I believe... Or if it is incompatible with the Aspire S7. Or if I was missing something...

**Comment by JoseExposito** [comment]
Hi @Laval429 

It's possible that your device is not compatible with uTouch, the libraries that Touchégg uses to recognise the gestures.

Try to run in a terminal `$ touchegg` and check the output while you perform multitouch gestures. If your device is supported, you'll see some information about the gestures
