### ISSUE TITLE
Can not install touchegg

### ISSUE THREAD

**Issue by andreshp** [JoseExposito/touchegg#257]
I have the following error when compiling with make:

g++ -m64 -Wl,-O1 -o touchegg ....

/usr/lib/x86_64-linux-gnu/libgeis.so: undefined reference to `frame_x11_delete@FRAME_2.2'
/usr/lib/x86_64-linux-gnu/libgeis.so: undefined reference to `frame_x11_create_window_id@FRAME_2.2'
/usr/lib/x86_64-linux-gnu/libgeis.so: undefined reference to `frame_x11_process_event@FRAME_2.2'
/usr/lib/x86_64-linux-gnu/libgeis.so: undefined reference to `frame_x11_get_window_id@FRAME_2.2'
/usr/lib/x86_64-linux-gnu/libgeis.so: undefined reference to `frame_x11_new@FRAME_2.2'
collect2: error: ld returned 1 exit status
Makefile:175: recipe for target 'touchegg' failed
make: *** [touchegg] Error 1

I have tried to install geis with no luck.

**Comment by JoseExposito** [comment]
You are missing some X11 dependencies, run
$ sudo apt-get build-dep touchegg
And try again

**Comment by andreshp** [comment]
The command `$ sudo apt-get build-dep touchegg` does not install any other package.

When I execute touchegg there is again an error with x11:

~~~
$ touchegg
Reading config from  "/home/andreshp/.config/touchegg/touchegg.conf" 
Try to make a multitouch gesture. If everything goes well the information about 
the gesture must appear 
touchegg: relocation error: /usr/lib/x86_64-linux-gnu/libgeis.so.1: symbol frame_x11_new, 
version FRAME_2.2 not defined in file libframe.so.6 with link time reference
~~~

I tried to reinstall frame but it kept failing. I also tried to reinstall [geis](https://launchpad.net/geis) but couldn't compile it because of problems with x11 :(

**Comment by JoseExposito** [comment]
Hola Andrés,

But did you finally manage to compile it or not? Because the `touchegg` command seems to be right. Those warnings are normal.

Once touchegg is running try to make some gestures in your trackpack check if it is compatible:
https://wiki.ubuntu.com/Multitouch/HardwareSupport
Unfortunately the list of Geis supported devices has not changed in more than 3 years, so it is kind of difficult to get one compatible.

If you are still having issues, please attach some details like your distro, trackpack model, desktop environment, etc

**Comment by andreshp** [comment]
My laptop is a [Dell XPS 13 (2015)](https://wiki.archlinux.org/index.php/Dell_XPS_13_%282015%29).  I use Ubuntu Gnome 5.10. Neither the trackpad nor the touch screen work.

Touchegg worked for two days or so. But afterwards it did not work anymore (it does not recognize any gesture). So I tried to reinstall Geis and Touchegg manually (this is where the error came from).

Probably it does not work because of the hardware, I had other problems with wifi, bluetooth, etc.

When I update the distro, I will try touchegg again ^^.

Thank you for your work Jose!

**Comment by JoseExposito** [comment]
OK, thank you! :)
