### ISSUE TITLE
Double Tap and Tap and Hold being recognized in single tap

### ISSUE THREAD

**Issue by jefferson-lima** [JoseExposito/touchegg#258]
If I configure touchegg to recognize _double taps_, like this:

```
<gesture type="DOUBLE_TAP" fingers="1">
    <action type="MOUSE_CLICK">BUTTON=2</action>
</gesture>
```

or _tap and hold_:

```
<gesture type="TAP_AND_HOLD" fingers="1">
    <action type="MOUSE_CLICK">BUTTON=2</action>
</gesture>
```

It will recognize an extra _double tap_, when a _single tap_ is performed:

```
[+] New gesture: 
     Type      ->  "TAP" 
     Fingers   ->  1 
     Direction ->  "NO_DIRECTION" 
     Action    ->  "MOUSE_CLICK" 
     Timing    ->  "AT_END" 
     App Class ->  "konsole" 
[+] New gesture: 
     Type      ->  "DOUBLE_TAP" 
     Fingers   ->  1 
     Direction ->  "NO_DIRECTION" 
     Action    ->  "NO_ACTION" 
     Timing    ->  "AT_END" 
     App Class ->  "konsole" 
     Gesture Start 
     Gesture Update 
     Gesture Finish 
```

When a _double tap_ is performed, it recognizes a _single tap_ and a _double tap_ twice.

I tried the patch proposed on

https://code.google.com/p/touchegg/issues/detail?id=206

but it didn't work.

I'm running the last version of the code on Kubuntu 15.10.

**Comment by deadwolfst** [comment]
Are there any updates on this issue? It still persists on KDE Neon 5.9. I guess, it is so on Kubuntu too.
I've downloaded mentioned patch, but it doesn't do anything with recognizing tap&hold.

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
