### ISSUE TITLE
What we will do with the wiki?

### ISSUE THREAD

**Issue by alexandre-mbm** [JoseExposito/touchegg#259]
To convert to GitHub's wiki?
I want reactivate the project and finally use it on Arch Linux.
Or would you prefer the wiki as a Jekyll site in a `gh-pages` branch?
I need to understand the full documentation.

**Comment by alexandre-mbm** [comment]
See the **[wikiconvert.py](https://github.com/trentm/googlecode2github/blob/master/wikiconvert.py)** from [here](http://evennia.blogspot.com.br/2014/02/moving-from-google-code-to-github.html).

**Comment by JoseExposito** [comment]
Her you go:
https://github.com/JoseExposito/touchegg/wiki

**Comment by alexandre-mbm** [comment]
It would be better it be a Gitbook multi-language. We already have in spanish (es). If you create the book and integrate it to GitHub (another repository), I will make pull requests with english (en) and brazilian portuguese (pt-br). I can create all and transfer to you at Gitbook and GitHub. Do you would want it?

**Comment by JoseExposito** [comment]
My experience with multi language wikis/documentation is that they are difficult to maintain and finally the changes only go to the main language (English).

I prefer to maintain a small wiki -you'd probably noticed that I removed outdated pages- in English. Language that most of the people understand or at least can translate with Google Translator.

**Comment by alexandre-mbm** [comment]
Okay, all well. I was only thinking in enjoy what did done already. Gitbooks are elegant. But my notes in portuguese really can be managed in other sites or in private.

**Comment by JoseExposito** [comment]
Sorry for the delay, your wiki changes are merged now.
Thank you very much for your help!!

**Comment by alexandre-mbm** [comment]
You did not a merge and so my commits were not imported.
