### ISSUE TITLE
touchegg-gui

### ISSUE THREAD

**Issue by alexandre-mbm** [JoseExposito/touchegg#260]
What it is and for where it was?

Ref.: d9086dc7348d49a381021755d8d5edba6896ccc7

**Comment by JoseExposito** [comment]
Hi,

It use to be the official Qt based graphical user interface to configure Touchégg. It become outdated, none tried to update it but, thanks to @Raffarti this new tool is available:

https://github.com/Raffarti/Touchegg-gce

As you can see in the FAQ is the recommended tool to configure Touchégg:
https://github.com/JoseExposito/touchegg/wiki/faq

Than you very much for your feedback!

**Comment by alexandre-mbm** [comment]
Thank you by your attention. An _issue_ like this can be labeled as `question`.
