### ISSUE TITLE
Reopen issues?

### ISSUE THREAD

**Issue by alexandre-mbm** [JoseExposito/touchegg#261]
At Google Code there were [open issues](https://code.google.com/p/touchegg/issues/list)...

**Comment by JoseExposito** [comment]
Most of them are configuration questions, minor distro specified stuff or very outdated issues that I won't fix (pull request are welcome hehe).

For the moment I'd prefer to keep them closed.

Thanks! :)

**Comment by alexandre-mbm** [comment]
You can reopen them but also label them: `wontfix`, `ubuntu`, `question`, `help wanted`, etc.
