### ISSUE TITLE
GRAIL ERROR (touch.cpp:~Touch:82): touch 424 failed to be rejected

### ISSUE THREAD

**Issue by alexandre-mbm** [JoseExposito/touchegg#263]
My configuration for tests have action `Control++` and `Control+-` with DRAGs (left, right) in Firefox.

Ref.:  happens something like [GRAIL ERROR (v3/touch.cpp:~Touch:84)](https://bugs.launchpad.net/grail/+bug/1027462)

**Comment by jefferson-lima** [comment]
Try using Control+KP_Add instead of Control++ and Control+KP_Subtract instead of Control+-

**Comment by alexandre-mbm** [comment]
@alandbm, when you make the test, report them here please.

**Comment by alexandre-mbm** [comment]
Is there something wrong with the code bellow?
```xml
<touchégg>
    
    <settings>
        <property name="composed_gestures_time">0</property>
    </settings>

    <application name="Firefox">

        <gesture type="DRAG" fingers="2" direction="LEFT">
            <action type="SEND_KEYS">Control+KP_Add</action>
        </gesture>

        <gesture type="DRAG" fingers="2" direction="RIGHT">
            <action type="SEND_KEYS">Control+KP_Subtract</action>
        </gesture>
        
    </application>

</touchégg>
```

The intent is simply testing the Touchégg using a action much simple for two fingers on Firefox.

**Comment by JoseExposito** [comment]
Execute Touchégg from the command line to make sure that the gestures with 2 fingers are being recognised and it is not a problem with your configuration, or temporary change them to 4 fingers for example.

If that is the problem:
https://github.com/JoseExposito/touchegg/wiki/faq#what-configuration-need-my-multitouch-device

Execute those commands and try again.

**Comment by alexandre-mbm** [comment]
@JoseExposito, we have done those synclient atributions, but lacks to test the last XML code above. My brother @alandbm is the owner; the notebook is with he perhaps to 1200 miles from me.

**Comment by alandbm** [comment]
Calma. Aqui eu sou dono de casa também. Compro comida limp, troco 
lãmpada. Daqui a pouco eu conecto full
VOu jantar.

Em 03-01-2016 21:07, Alexandre Magno escreveu:

**Comment by alexandre-mbm** [comment]
My brother got a test successfully. Thank guys.
