### ISSUE TITLE
Import my wiki edits

### ISSUE THREAD

**Issue by alexandre-mbm** [JoseExposito/touchegg#264]
See them [here](https://github.com/alexandre-mbm/touchegg/wiki/_history). This continues the issue #259. It is my contribution for now.

---

_Update 1_

Oops! Wait. I forgot the page FAQ.

_Update 2_

Ready! You can merge already.

**Comment by alexandre-mbm** [comment]
[See all changes](https://github.com/alexandre-mbm/touchegg/wiki/_compare/edea261132f682d0524de3b7cc5b10357686887c...8037febdbaef8fac5df03ac71900a4ef771062ec).

**Comment by JoseExposito** [comment]
Done, thank you very much :)
