### ISSUE TITLE
Support for ETPS/2 Elantech touchpad.

### ISSUE THREAD

**Issue by Shmink** [JoseExposito/touchegg#265]
I needed touchegg to work, after spending too much time on trying to set it up I finally realised my track pad wasn't supported according to [the following question posted on the Google code archive](https://code.google.com/archive/p/touchegg/issues/165). Well that sucks but that was 2012 so I scoured for a solution and came across [the following article.](http://www.evilcodingmonkey.com/2014/01/23/ubuntu-activate-multi-touch-on-elantech/) Success! touchegg recognises my gestures immediately. So this is less of an issue and more of a recommendation to add to the wiki or install guide or something. Thanks for the software.

**Comment by JoseExposito** [comment]
Thank you, added to the FAQ:
https://github.com/JoseExposito/touchegg/wiki/FAQ#what-configuration-i-need-for-my-multitouch-device
