### ISSUE TITLE
Doesnt work on Fedora 22, 23 or Ubuntu 15.04

### ISSUE THREAD

**Issue by angelsix** [JoseExposito/touchegg#267]
I've  tried to get touchegg to work. I've tried Fedora 22, Fedora 23 and ubuntu 15.04.

All the same. Disable TapButton1,2 and 3, start touchegg on startup. Nothing ever works. Output that touchegg has started is in the /var/log/syslog, yet no gestures work and no output about gestures being detected works.

People mention they get it working in Ubuntu 15 yet I cannot. Start up install from latest ISO, install touchegg, create config file (that /var/log/syslog says its read in ok) and run touchegg in a startup script (~/.config/autostart) as ~/.xprofile never runs.

Nothing works. Does this work in any of the above. If so how?

**Comment by JoseExposito** [comment]
Hi @angelsix 

That is  because your hardware is probably not supported:
https://github.com/JoseExposito/touchegg/wiki/FAQ#is-my-device-supported-by-touch%C3%A9gg
Check if your trackpad is on that list, please.

Jose

**Comment by angelsix** [comment]
Its a synatics on new Dell XPS 13. Should be supported it states new synaptics should be.

If not, is there any way to get 3 finger swipes in linux? I just need a way to swipe out of a VMWare screen on another workspace via trackpad.

**Comment by angelsix** [comment]
Just tested on my Macbook Pro Retina 13 and it doesn't work on that either and that is supported. Its running in Parallels if that makes a difference

**Comment by JoseExposito** [comment]
If you are running Linux in a VM on mac, it is not possible to use multitouch features. OS X reserves 3 and/or 4 fingers gestures to use mission control or drag and drop depending on your configuration.

I'm guessing you are running Ubuntu on your Dell *not* in a VM. If so, if you are using Unity:
https://github.com/JoseExposito/touchegg/wiki/FAQ#im-using-unity-and-i-cant-use-gestures-with-3-and-4-fingers
If not, please provide more information.

About Fedora, I think they switch in the latest versions to libinput, uTouch is not compatible with that backend at the moment.

**Comment by isomerase** [comment]
@JoseExposito I also am also trying to get multitouch working on my Dell XPS 13 9343 (running Debian + OpenBox) with Touchegg. When I run `touchegg` it loads my config and lists gestures, but when I try pinching and rotating I don't see any output in terminal. Does that mean my hardware is incompatible?

**Comment by JoseExposito** [comment]
Yes, that probably means that your trackpack is not supported, sorry

**Comment by dbruenig** [comment]
Touchegg works fine with xps 13 here. If you still need help, let me know.

**Comment by 4ndrej** [comment]
https://copr.fedorainfracloud.org/coprs/mhoeher/multitouch/ provides Touchegg build for Fedora

**Comment by mhoeher** [comment]
Hi @4ndrej,

The touchegg builds in that repository are not up to date - mainly due to Fedora switched to libinput for handling input events. However, there is an alternative app in that repository - libinput-gestures - which you could use.
