### ISSUE TITLE
3 Finger Swipe doesn't work

### ISSUE THREAD

**Issue by fobus42** [JoseExposito/touchegg#268]
Hello I'm using Linux mint on Asus n550jk notebook When I swipe with my three finger it touchegg unabel to catch the swipe. But 4 finger works great.

Here is my configuration 

$ xinput | grep Touch
⎜   ↳ ETPS/2 Elantech Touchpad                	id=13	[slave  pointer  (2)]

$uname -a
Linux Pabeda 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by VictorBogo** [comment]
Two and Three fingers are reserved to OS use on some distributions. I needed to execute
 ```
synclient ClickFinger2=0 & synclient TapButton2=0
synclient ClickFinger3=0 & synclient TapButton3=0
```
on Ubuntu to disable it. Try to find the correspondent commands for Mint (and your touchpad)!

**Comment by fobus42** [comment]
@VictorBogo Yes, great solution. Thanks.

**Comment by ademcal** [comment]
I have same problem I tried solution but doesn't work Beside I am using Mint 18 Cinnamon

synclient ClickFinger2=0 & synclient TapButton2=0
synclient ClickFinger3=0 & synclient TapButton3=0

$ xinput | grep Touch

⎜   ↳ ELAN1010:00 04F3:3012 Touchpad          	id=15	[slave  pointer  (2)]
⎜   ↳ ETPS/2 Elantech Touchpad                	id=17	[slave  pointer  (2)]


uname -a

Linux uygur-Inspiron-7559 4.6.3-040603-generic #201606241434 SMP Fri Jun 24 18:36:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
