### ISSUE TITLE
Feature request: Compose multiple gestures

### ISSUE THREAD

**Issue by Jereviendrai** [JoseExposito/touchegg#271]
My tablet does not support multitouch, so I only have the gestures with 1 finger available which restricts the amount of actions I can perform with touchegg.

To make up for this, it would be nice to be able to compose multiple gestures, e.g. first drag up, then left, then down. This could be done either in one continuous stroke, or - probably easier to implement - with three separate strokes in quick succession. 

This feature would offer more flexibility for devices like mine that don't support multitouch.

Thanks,
jereviendrai

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
