### ISSUE TITLE
Mouse cursor messed up if touchegg is running

### ISSUE THREAD

**Issue by seb443556** [JoseExposito/touchegg#272]
Hello,

I have installed touchegg for a touchscreen on Ubuntu 16.04 with Lightdm instead of Unity. I modified the .conf for touchegg to support a small set of gestures. If I start touchegg manually via console it's working nicely (Thank you, devs!). However if I try to start touchegg in an init-skript, the mouse cursor behaves strangely. It looks like every "route" of the cursor is executed twice. 

I've played around with the init script and tried starting touchegg after some delay in case of any missing drivers or whatever, but so far I couldn't find out the difference between working and not working. Does touchegg intercept touch events or does it read/copy them? 

Sebastian

**Comment by seb443556** [comment]
My touchegg config contained only two gestures:
1. DRAG 2 Fingers DOWN --> RUN_COMMAND
2. DRAG 1 Finger ALL --> DRAG_AND_DROP Button=1

I now have removed the DRAG_AND_DROP entry and this seems to solve the problem. However I'd like to have Drag&Drop available and still don't know why the problem doesn't arise if I start touchegg manually from the console.

**Comment by JoseExposito** [comment]
Hi @seb443556 

I'm afraid I don't have a device with a touch screen to test with the behaviour of 1 finger drag and drop, however, in a trackpad -device Touchégg was designed to- I don't expect that config to work.

Can you expose how do you run Touchégg on start please? Maybe we can find the problem there, as it should work in the same manner it does from console.

Jose

**Comment by seb443556** [comment]
At the start, it's lightdm-->.xinitrc 

.xinitrc:
"
#!/usr/bin/env bash
...
...
touchegg &
xfwm4
"

**Comment by seb443556** [comment]
I tried replacing DRAG 1 Finger with TAP_AND_HOLD. In that case my mouse cursor is moving normally but sadly drag&drop doesn't work and single taps (as mouse clicks) are not working anymore (only if you tap and hold). 

Is there a way to tell touchegg that it should only use gestures with more than one finger and leave the rest alone?

**Comment by JoseExposito** [comment]
In general -at least with trackpads- I recommend to leave 1 and 2 fingers gestures to the system and use 3 or more gestures with Touchégg.

> Is there a way to tell touchegg that it should only use gestures with more 
> than one finger and leave the rest alone?

Yes, this is an example configuration illustrating that:
https://github.com/JoseExposito/touchegg/blob/master/installation/touchegg.conf

**Comment by seb443556** [comment]
However this default config behaves similarly to my own config. With both configs I cannot drag&drop windows. I also found out that I can't click "close", "maximize" and "minimize" buttons.
