### ISSUE TITLE
Gesture tracking with Arch/Cinnamon

### ISSUE THREAD

**Issue by tsusanka** [JoseExposito/touchegg#274]
Thank you for the work on touchegg, I am a happy user on Manjaro Linux (based on Arch linux) with cinnamon.

However I have similar problem as described in #273. I updated my system yesterday and something messes with touchegg's capability to track gestures. Here's a [list of the updates ](https://gist.github.com/tsusanka/33e3114fc4a5cbe330ef291c1ee660c9). I suspected Cinnamon, however downgrading it to 3.0.4. didn't help.

Maybe someone sees something in the list? Any ideas?

**Comment by dbruenig** [comment]
it's the new synaptics version
upgraded xf86-input-synaptics (1.8.3-1 -> 1.8.99.1-0.1)
which does not emit xf86PostTouchEvent any longer. I created a patch: https://gist.github.com/dbruenig/ae80fedbeded12084b7227b0ef53aeec

You would need to get the source from http://xorg.freedesktop.org/releases/individual/driver/ first and then apply the patch

**Comment by tsusanka** [comment]
Thank you! I'm a bit busy now, but I'll do it later :). Is there any chance this might get fixed from xf86-input-synaptics' side or it's not a bug?

**Comment by dbruenig** [comment]
it's not a bug, developed dropped support for sending the touch events since they assumed this feature was not used by anyone[1].

[1] https://lists.x.org/archives/xorg-announce/2016-April/002689.html

**Comment by tsusanka** [comment]
I've created new issue to address this more directly #282 .
