### ISSUE TITLE
MOVE_WINDOW is very slow on HiDPI screens

### ISSUE THREAD

**Issue by alexanderadam** [JoseExposito/touchegg#276]
Would it be possible also to add a `SPEED` setting?

Thank you very much for touchegg. I love it!

**Comment by anbroid** [comment]
Yes, I am using MOVE_WINDOW for 3-finger dragging and it is very slow for me too. A SPEED setting would be fantastic. @JoseExposito could you add this ?

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
