### ISSUE TITLE
Xorg crashes if using touchegg

### ISSUE THREAD

**Issue by seb443556** [JoseExposito/touchegg#277]
Hello,

I have an application which uses xmessage with buttons. So everytime I press a button in the window, it opens a new window with xmessage with different text and buttons. If I use the touch to press the buttons, it sometimes (rarely) happens that xorg chrashes. The crash only happens if I have touchegg running in the background. I get the following reports:

in syslog: 
org.a11y.atspi.Registry[1112]: XIO: fatal IO error 11 (Resource temporarily unavailable) on X server ":0"

in Xorg.o.log:
Segmentation fault at address 0x...
Fatal server error:
Caught signal 11 (Segmentation fault). Server aborting

in touchegg:
touchegg: Fatal IO error: client killed

I was able to reproduce the crash reliably by using the following script:
# !/bin/bash

while :
do
  xmessage -center "test bla bla bla" -buttons "" &
  testpid=$!
  sleep 0.1
  kill $testpid
done

If I now start touching around in the area of the appearing test window (only normal single touches, no gestures) the xorg crashes immediately. If I kill touchegg before doing this, no crashes appear. 

Ubuntu 16.04 LTS
Xorg Version 1.18.3
Intel Atom Processor E3827

I'm using a touchscreen but maybe this issue exists with trackpads as well. Any tipps on how I could debug this further are appreciated.

Sebastian

**Comment by seb443556** [comment]
probabliy the same issue as in
https://github.com/anodynos/touchegg/issues/250

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
