### ISSUE TITLE
Compilation Error on Debian 8.5

### ISSUE THREAD

**Issue by 8Niubility** [JoseExposito/touchegg#279]
Hi there, I am a new user to this software.

When i tried to execute make, i got the following message

g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -o Config.o src/touchegg/config/Config.cpp
In file included from src/touchegg/config/Config.cpp:21:0:
src/touchegg/config/Config.h:24:24: fatal error: QtCore/QFile: No such file or directory
 #include <QtCore/QFile>
                        ^
compilation terminated.
Makefile:380: recipe for target 'Config.o' failed
make: *** [Config.o] Error 1

I have just installed g++, wonder if this has anything to do with it.

**Comment by JoseExposito** [comment]
Hi, you need to install Qt, check the wiki to see the other dependencies.

I'm not sure if uTouch will be available in Debian though...

**Comment by 8Niubility** [comment]
oops, utouch doesn't seem to be available for debian.
(That might be a reason for the error which i encountered.)
thanks for your time.(Do I need to mark this as closed? I am new to github.)
