### ISSUE TITLE
No gesture detected on Ubuntu 16.04

### ISSUE THREAD

**Issue by DavidPeicho** [JoseExposito/touchegg#280]
Still not working for me on Ubuntu 16.04 using the Gnome DE.
I tried to call touchegg in the .xprofile file, but that did not work for me.
I tried with 3 and 4 fingers, but the event isn't caught.

**Comment by lzx1994** [comment]
Me too......

**Comment by DavidPeicho** [comment]
I actually thought it was because of my Desktop Environment but it does not seem to come from here (the .xprofile trick would have worked in this case).
I tried to update my Synaptics drivers, I do not know if it is related but it did not change anything.

**Comment by everdark** [comment]
same here.
ubuntu gnome 16.04
the .xprofile trick is not working
indeed the synclient can't set TapButton3 = 0

**Comment by manV** [comment]
Same here, touchegg doesn't recognize anything, even after .xprofile trick.

**Comment by abhiguru** [comment]
same as manV, Is it required to have the Magic touchpad2 connected over BT ? I have a USB and ubuntu 16.04 seems to be okay with basic tap but nothing else

**Comment by manV** [comment]
@abhiguru are you using Ubuntu Gnome?

**Comment by abhiguru** [comment]
yup Gnome, Actually it is 16.10 I tried reinstall and also tried the branch with the QT5 but none of them worked would love to use this

**Comment by RA-Danny** [comment]
Any update ? Same problem here, also with 16.10

**Comment by iwex** [comment]
I'm using Unity, and added commands to .xprofile = no success

**Comment by rickmed** [comment]
Not working either for me -xfce4. I don't think is a matter of DE.

**Comment by mhinsch** [comment]
Working on Kubuntu 16.04 (touchscreen of yoga pro 2). Pinch always seems to be recognized as drag though.

**Comment by rickmed** [comment]
@mhinsch is it working with both touchscreen and touchpad?

**Comment by mhinsch** [comment]
No, just with the touchscreen.

**Comment by nottoseethesun** [comment]
Not working for me under Ubuntu 16.04 LTS with `touchegg&` as the first line in my `~/.xprofile` . 

Separately, where should [the synclient commands given in the TouchEgg wiki](https://github.com/JoseExposito/touchegg/wiki/FAQ#what-configuration-i-need-for-my-multitouch-device) be given?

**Comment by YoussefDev** [comment]
Same problem on ubuntu 16.04 LTS unity desktop

**Comment by CigarZh** [comment]
Same problem

**Comment by rjsteinert** [comment]
Not working on Ubuntu 16.04 Unity.

**Comment by rjsteinert** [comment]
@all According to the wiki, Unity is not supported or possible to support https://github.com/JoseExposito/touchegg/wiki/FAQ#im-using-unity-and-i-cant-use-gestures-with-3-and-4-fingers

**Comment by rjsteinert** [comment]
Here is a tutorial on rebuilding Unity so that gestures are disabled thus allowing touchegg to take over https://ineed.coffee/1068/os-x-like-multitouch-gestures-for-macbook-pro-running-ubuntu-12-10/

**Comment by kabalage** [comment]
In Ubuntu 16.04 Unity default gestures may be disabled via dconf options, no need to rebuild Unity.
You need to disable all 3 options in `com.canonical.unity.gestures`, I used dconf-editor.
Touchegg works with these Unity built-in gestures disabled.

**Comment by Sergeant007** [comment]
Same problem - no touchegg gestures detected, only system-default gestures work (Kubuntu 16.04).

**Comment by VitorBrangioni** [comment]
Same problem

**Comment by zexiangliu** [comment]
Just try fusuma. It uses libinput instead of Synaptics and works pretty good in my Ubuntu 16.04. `https://github.com/iberianpig/fusuma`

**Comment by hexiaoyanh** [comment]
some problem

**Comment by mostafa-pgs** [comment]
same problem, not gesture in ubuntu **16.04 TLS**

**Comment by AltanS** [comment]
fusuma fixed the issue for me, thinkpad x1 carbon 5th gen on ubuntu 16.04

**Comment by VitorBrangioni** [comment]
I solved this problem with LIBINPUT, following steps in this page: [setting up multitouch gestures with Ubuntu 16.04 ](https://www.reddit.com/r/Dell/comments/646y0t/xps_9560_setting_up_multitouch_gestures_with/)

**Comment by D12EA177E12** [comment]
I am using the default touchegg.conf. While the 4-finger swipe down gesture is set to trigger the "SHOW_DESKTOP" action but it doesn't actually register.

What's even more disappointing is that 2-finger swipe left/right doesn't work.  Anyone else getting the same problem?

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
