### ISSUE TITLE
Does not work on libinput

### ISSUE THREAD

**Issue by himanshub16** [JoseExposito/touchegg#281]
libinput is the one I found controlling the touchpad on GNOME 3.20 and Elementary OS Loki, where I was not able to use touchegg. 
Any workaround?

**Comment by JoseExposito** [comment]
I'm afraid there is not any possible workaround for this.

libinput is an absolute different backend in terms of multitouch input and the library Touchégg is using at the moment (uTouch) does not support this backend.
The only possible fix is to re-write Touchégg to support libinput, what it is actually something I'm considering.

**Comment by himanshub16** [comment]
I gave a try on "libinput-debug-events" (available from package libinput-tools) on a Macbook Air 15 with Elementary OS Loki. It seems like libinput properly recognizes touchpad events like "pinch" and "flick" with three and four fingers. The desktop environment is not made to listen and act to such events.

**Comment by capstan1** [comment]
After trying to get touchegg to work on elementary OS Loki today I came to the same conclusion. 
Was very happy with touchegg on Unity and don't want to miss it.

Is there any possbile solution for now? Can we use synaptic in eOS?

Thank you for this great software!

**Comment by himanshub16** [comment]
Yes. I don't remember precisely, but you can can give it a try. It's one of the "safest experiments" to carry out on any Linux machine. You should give it a try, and share your results. I've switched to Unity.
 ```
sudo apt remove xserver-xorg-input-libinput
sudo apt install xserver-xorg-input-synaptics 
```

**Comment by capstan1** [comment]
I can confirm that the solution given by himanshub16 works! Now I can make use of touchegg!
Thank you very much!

There is just one issue I have (maybe someone has an idea here)
I put workspace changing on 3 fingers swipe to left right via he corresponding shortcuts of elementary OS (Win+right/left).
This is only working if there is an window on the current workspace. If it's empty nothing happens. The keyboard shortcut itself does work on empty workspaces nevertheless.

the correspnding parts of my touchegg.conf
`<gesture type="DRAG" fingers="3" direction="RIGHT">
			<action type="SEND_KEYS">Super+Right</action>
		</gesture>
		<gesture type="DRAG" fingers="3" direction="LEFT">
			<action type="SEND_KEYS">Super+Left</action>
		</gesture>`

Any idea how to change this behavior?

**Comment by himanshub16** [comment]
Try doing the same with keyboard shortcuts when there are no windows on current workspace. Perhaps, Elementary does not create workspaces on the right if there are no windows on the current workspace. However, you can do by opening the multi-tasking view from the dock, and clicking on +. This is unlike Ubuntu, which has a certain number of workspaces in advance.
Check it out once.

**Comment by capstan1** [comment]
it wasn't a problem with the workspace handling itself (shortcuts were always working) but with elementary OS not handling the Desktop (no icons)

I had to put "nautilus -n" in startup applications, so now touchegg works just perfect! :)

**Comment by himanshub16** [comment]
Glad to hear.

**Comment by himanshub16** [comment]
Glad to hear.

**Comment by meijieru** [comment]
I have tested touchegg on my yoga 900, it seems to work for my touchscreen (apart pinch), but when I do the same on my touchpad, the touchegg does not responce at all. I am working with xf86-input-libinput on manjaro with plasma5

**Comment by rickmed** [comment]
I'm having the same problem as @meijieru (did you fix it?). Xubuntu 16.04 -xserver-xorg-input-synaptics .

**Comment by meijieru** [comment]
Not yet @rickmed

**Comment by himanshub16** [comment]
@JoseExposito Hey, I stepped onto [this](https://github.com/bulletmark/libinput-gestures) today.

**Comment by uvisgrinfelds** [comment]
@himanshub16 Thanks, man. Everything works perfectly as expected - the installation and configuration were easy as one-two-three. I was already given up on multitouch for a while, cannot believe it`s back! :)

**Comment by shacharoz** [comment]
hey guys, is it reasonable that when i had lubuntu i managed to run touchegg, but now in ubuntu 18,04 i cant?
i now have libinput driver installed, but when i try to switch for synaptic, like suggested, after i sign in my user details, all input devices stop responding (no way to control the pc and i have to do hard reset). so i reinstalled evdev to talk to you now.
any ideas how to install synaptic in a good way?

**Comment by JoseExposito** [comment]
Hi all!

I'm working on support for libinput at the moment: https://github.com/JoseExposito/touchegg/issues/334

I'll be updating that issue (and my Twitter account) with the progress of the new version.
