### ISSUE TITLE
Touchegg is incompatible with the newest xf86-input-synaptics

### ISSUE THREAD

**Issue by tsusanka** [JoseExposito/touchegg#282]
In xf86-input-synaptics' version 1.8.99.1-0.1 the `xf86PostTouchEvent` which touchegg relies on was [removed](https://cgit.freedesktop.org/xorg/driver/xf86-input-synaptics/commit/?id=0a4cf80a00663ff3ce8e76baf0940782576efe13).

Workaround is to apply this @dbruenig 's [patch](https://gist.github.com/dbruenig/ae80fedbeded12084b7227b0ef53aeec) or use any older version of xf86-input-synaptics (1.8.3-1 tested and works).

Not sure it's worth to fix this, would be solved by #281.

**Comment by urbie-mk2** [comment]
[patch url fixed](https://gist.github.com/urbie-mk2/ae80fedbeded12084b7227b0ef53aeec)

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
