### ISSUE TITLE
PageDown SendKeys

### ISSUE THREAD

**Issue by tsusanka** [JoseExposito/touchegg#283]
Touchegg is working well, however I'm unable to bind gesture to perform "Control+PageDown". The gesture is recognized and the keys should be fired, but are not.

Does PageDown have a different title? "Control+t" for example works fine.

**Comment by JoseExposito** [comment]
Hi,

The key is "Page_Down" you can see the list here:
https://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h

Just remove the XK_ prefix from the name of the key.

**Comment by tsusanka** [comment]
Uf it's even written your [wiki](https://github.com/JoseExposito/touchegg/wiki/All-actions-supported-by-Touch%C3%A9gg), I'm just so blind!

Thank you very much and thx for a great piece of software!
