### ISSUE TITLE
touchegg with openSUSE tumbleweed

### ISSUE THREAD

**Issue by Letsdosomehardcore** [JoseExposito/touchegg#286]
Hi!
I use Asus G501JW with Elantech touchpad and i would like to be able to use some multitouch gestures in openSUSE Tumbleweed. (like 3 fingers up -> show all windows)
I've found this package... but it doesn't work.
Command 'touchegg' shows me this:

> Reading config from "/home/val/.config/touchegg/touchegg.conf" 
> Try to make a multitouch gesture. If everything goes well the information about the gesture must appear 
> [+] Avaliable gesture: 
> Name -> Flick 
> [+] Avaliable gesture: 
> Name -> Drag 
> [+] Avaliable gesture: 
> Name -> Pinch 
> [+] Avaliable gesture: 
> Name -> Rotate 
> [+] Avaliable gesture: 
> Name -> Tap 
> [+] Avaliable gesture: 
> Name -> Touch 

It means that my touchpad is supported, isn't it? But there are already a lot of gestures in /home/val/.config/touchegg/touchegg.conf, for example

```
<gesture type="DRAG" fingers="3" direction="DOWN">
<action type="MINIMIZE_WINDOW"></action>
</gesture>
```

And these gestures doesn't work. What do i do wrong?
Thank you.

**Comment by JoseExposito** [comment]
I'm afraid that means that your software stack supports those gestures, not necessarily your hardware.
The easiest way to ensure your hardware is supported is to perform some gestures and see if there is any output in your terminal.

As you can see in the wiki, the hardware supported by uTouch (Ubuntu's multitouch stack that Touchégg uses) is unfortunately pretty limited:
https://github.com/JoseExposito/touchegg/wiki/FAQ#is-my-device-supported-by-touch%C3%A9gg

**Comment by Letsdosomehardcore** [comment]
But all gestures work fine in Windows 10 (3 fingers swipe, zoom etc). It means that my hardware supports multitouch, doesn't it?

**Comment by JoseExposito** [comment]
Yes, your hardware supports it, but it looks like the Linux driver -which usually is not as good as the Windows one- does not support advanced multitouch features. Sorry :S

**Comment by Letsdosomehardcore** [comment]
The problem has gone after synaptics driver installation. All gestures work properly.
Thank you for that great package :)
