### ISSUE TITLE
Vertical scroll maximum speed of 10 is too slow on HiDPI display

### ISSUE THREAD

**Issue by cy6erGn0m** [JoseExposito/touchegg#287]
It should be way to make it scroll much faster. Perhaps the scale should be logarithmic?

**Comment by JoseExposito** [comment]
Hi,

Have you tried to use the default driver behaviour for 2 fingers? I usually have a better experience with synaptics for 1 and 2 fingers and Touchégg for 3 or more.

Anyway, what hardware are you using? Touchpad or touchscreen?

**Comment by cy6erGn0m** [comment]
I have laptop with touchscreen (Dell XPS 15 9550). Haven't tried synaptics yet. Both default and speed of 10 is not fast enough

**Comment by JeanVEGA** [comment]
+1 on this one. With KDE Plasma on my Dell Latitude E7470 (with HiDPI), any setting with double digit `SPEED` ignores the inverted scrolling:

`
        <gesture type="DRAG" fingers="2" direction="ALL">
            <action type="SCROLL">SPEED=10:INVERTED=true</action>
        </gesture>
`

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
