### ISSUE TITLE
Ability to switch between applications/windows with x-fingers swipe

### ISSUE THREAD

**Issue by axtux** [JoseExposito/touchegg#288]
Hello,

Before anything, thank you very much for your for your work. Touchegg is so wonderful when using a laptop without a mouse (now it's even better than with a mouse ;-))

I use touchegg to switch tabs and workspaces with finger swipe and this is amazing. Though, one missing feature is the ability to switch between applications/windows. The Unity shortcut for it is Alt+Tab and Alt+Shift+Tab but when Alt+Tab is pressed twice, the previous window is back again on the screen (not the next-next one). One workaround would be a new ACTION supported by Touchegg that would be CHANGE_WINDOW or CHANGE_APPLICATION and would allow to switch between windows/applications using Alt+Tab shortcut but keeping Alt key pressed for some seconds after swipe to let user swipe multiple times and go to next and next window.

Regards,
Axtux

**Comment by urbie-mk2** [comment]
try mapping to shift + alt + tab instead, not the solution but might fix it. 

touchegg could have an extended configuraiton of key combinations. Since some key combos (like this one) require holding one key down the whole time (alt) and activating the other key (tab) every tick activation of the gesture.

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.

**Comment by copytac** [comment]
I use finger swipe for switch tasks(mapping alt+tab and alt+shift tab with cycling), it went ok but had a noise thing, if I  swipe left for front task one by one, it's ok, and I continue swipe right it also went well one by one, but stopped at origin task, can't go ahead, back left is ok. If I start swipe right, same back at the origin task can't go left, just right, can you solve this?
