### ISSUE TITLE
Pinch-to-zoom

### ISSUE THREAD

**Issue by JackeLee** [JoseExposito/touchegg#289]
Hi, would it be possible to allow a combination of actions to take an effect at once. Namely, I'd like to be able to write something like this

        <gesture type="PINCH" fingers="2" direction="IN">
            <action type="SEND_KEYS">Control</action>
            <action type="SCROLL">SPEED=3:INVERTED=false</action>
        </gesture>

or 

        <gesture type="PINCH" fingers="2" direction="IN">
            <action type="SCROLL" modifier="Control">SPEED=3:INVERTED=false</action>
        </gesture>

By this, by pinching with two fingers in we would have the effect of Control + Scrolling. This combination works for most of apps as zooming in.

Similarly, if we can add modifiers to MOUSE_CLICKS we can have

        <gesture type="DOUBLE TAP" fingers="1" direction="">
            <action type="MOUSE_CLICK" modifier="Control">BUTTON=1</action>
        </gesture>

and then with double tap we have Control + Click to open windows in new tabs.

Or, is there already a (better) way to do this?

Thanks!

**Comment by JoseExposito** [comment]
I'm afraid the best way of doing it at the moment is to SEND_KEYS "Control" plus "+" or "-"
