### ISSUE TITLE
on ubuntu 16.04 LTS, get error

### ISSUE THREAD

**Issue by ORESoftware** [JoseExposito/touchegg#290]
![screenshot from 2016-12-02 20-12-41](https://cloud.githubusercontent.com/assets/11139560/20856740/b594cc18-b8cb-11e6-86d4-f823b61b7f46.png)

new to this, so this is all I have right now

**Comment by JoseExposito** [comment]
Make sure you have the universe repo enabled:
http://askubuntu.com/a/148645

**Comment by ORESoftware** [comment]
thanks!
