### ISSUE TITLE
F keys

### ISSUE THREAD

**Issue by zachkont** [JoseExposito/touchegg#292]
How do I use F keys with touchegg?
<action type="SEND_KEYS">F12</action> doesnt work (neither does f12, F_12)

What am I doing wrong?

**Comment by JoseExposito** [comment]
"F12" should be the correct one as you can see in your "/usr/include/X11/keysymdef.h" file in case you have any future problems ( https://github.com/JoseExposito/touchegg/wiki/All-actions-supported-by-Touch%C3%A9gg )

**Comment by zachkont** [comment]
Yeah I already read the documentation but F12 doesn't work for me. Also, there is no such file on my system, could that be the issue?

**Comment by JoseExposito** [comment]
Do you have the same problem with the other F keys?

**Comment by zachkont** [comment]
Yes, I can't bind any F key.

Also, not sure if relevant, but using `$ touchegg` to check for keystrokes etc doesn't work for me, all I get is this:
`Reading config from  "/home/user/.config/touchegg/touchegg.conf" 
Try to make a multitouch gesture. If everything goes well the information about the gesture must appear 
[+] Avaliable gesture: 
	 Name ->  Flick 
[+] Avaliable gesture: 
	 Name ->  Drag 
[+] Avaliable gesture: 
	 Name ->  Pinch 
[+] Avaliable gesture: 
	 Name ->  Rotate 
[+] Avaliable gesture: 
	 Name ->  Tap 
[+] Avaliable gesture: 
	 Name ->  Touch`
and nothing after it until I stop it

**Comment by JoseExposito** [comment]
That is weird, I'm positive the key code is F1...F12 (mind the capital F)... Also strange that you are not able to see any output to the console when you perform the actions that are working

If you can not make FX to work, try to change the binding to another key convination

**Comment by zachkont** [comment]
I actually tried that (it was F12 for guake btw) and now guake won't start at all, but I guess that is a guake problem with low priority for me at this time.

Anyway, if you come up with any ideas/solutions please update this. I will keep watching it. Touchegg is pretty awesome, well done.
