### ISSUE TITLE
Pinch for zoom in and out doesn't work

### ISSUE THREAD

**Issue by alothings** [JoseExposito/touchegg#294]
Tried PINCH gesture with both 2 fingers and 3 fingers. Using this config file:
http://pastebin.com/J3KimbyY

I have a .xprofile file containing this: 

synclient TapButton2=1
synclient ClickFinger2=1
synclient TapButton3=0
synclient ClickFinger3=0
synclient HorizTwoFingerScroll=1
synclient VertTwoFingerScroll=1
touchegg &

And these are my current xinput settings: http://pastebin.com/Lw0SQ3We

Also, the rest of the gestures do work in my touchpad, but they don't work on my screen. Why is that?
I do have a multitouch screen. 
Specs: Ubuntu 16.10. Kernel 4.8.8. Installed touchegg using sudo apt

**Comment by JoseExposito** [comment]
Hi Alonso,

Try with this configuration:

```
        <gesture type="PINCH" fingers="2" direction="IN">
            <action type="SEND_KEYS">Control+KP_Add</action>
        </gesture>

        <gesture type="PINCH" fingers="2" direction="OUT">
            <action type="SEND_KEYS">Control+KP_Subtract</action>
        </gesture>
```

Those should be the correct keys.

I'm afraid I can not help you with the touch screen as I don't have one to test with.

Jose
