### ISSUE TITLE
Adjust speed of Double Tap and Tap and Hold

### ISSUE THREAD

**Issue by blmvxer** [JoseExposito/touchegg#296]
I haven't looked at the source code yet, but from every tutorial and google search I've checked there is no answer, Is there any support for the sensitivity or speed of these actions?

Also when using button 3 to pull up menus or clicking on the start menu touchegg loses focus

**Comment by JoseExposito** [comment]
At the beginning of your configuration, you can change the speed by adding this lines:

```
    <settings>
        <property name="composed_gestures_time">0</property>
    </settings>
```
