### ISSUE TITLE
Focus on menu

### ISSUE THREAD

**Issue by ghost** [JoseExposito/touchegg#297]
Sorry to bother again, and thanks with the last issue.

So the following issue is when I open the app menu or right click touchegg looses focus and won't allow input on menu items(i.e. copy paste etc)

**Comment by urbie-mk2** [comment]
need info and version number of:
your distro
package customizations if any
synaptics (incl driver)
x11
touchegg.

and contents of 
x11 config
synaptics config
 touchegg config.

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
