### ISSUE TITLE
Cinnamon doesn't recognize Alt+Tab sent by Touchegg.

### ISSUE THREAD

**Issue by alextpedro** [JoseExposito/touchegg#299]
What it says on the tin. I'm trying to configure three finger gestures to tab through windows using:

```
<gesture type="DRAG" fingers="3" direction="LEFT">
      <action type="SEND_KEYS">Alt+Tab</action>
</gesture>

<gesture type="DRAG" fingers="3" direction="RIGHT">
     <action type="SEND_KEYS">Shift+Alt+Tab</action>
</gesture>
```

I've tried with another key combo (Super+D to show desktop) and the three finger gesture works fine. Not sure if it's a bug or something I'm doing wrong.

**Comment by urbie-mk2** [comment]
start touchegg in a terminal window (pkill old instance first). Use your gesture and look if you find this in the window, you might have to scroll back a bit.
```
        Type      ->  "DRAG" 
        Fingers   ->  3 
        Direction ->  "LEFT" 
        Action    ->  "SEND_KEYS" 
        Timing    ->  "AT_END" 
```
or direction right.

try to remap the alt tab in your distro and use that combination in touchegg and see if it works then.

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
