### ISSUE TITLE
Touchegg stopped recognizing touches after Ubuntu update

### ISSUE THREAD

**Issue by alothings** [JoseExposito/touchegg#300]
Hi,

I've had touchegg running with Ubuntu 16.04 and 16.10 for over a year, but a few days ago it stopped working. It happened after I run sudo apt update & sudo apt upgrade, I have pasted the log of the changes on this link: http://pastebin.com/6w1VAYr8

Whenever I check synclient, it does have ClickFinger3 and TapButton3 set to 0, and when I run Touchegg, I get the normal output, but nothing after that (so I suppose it's not recognizing the gestures).

Reading config from
"/home/username/.config/touchegg/touchegg.conf" 
Try to make a multitouch gesture. If everything goes
well the information about the gesture must appear 

[+] Avaliable gesture: 
 Name ->  Flick 
[+] Avaliable gesture: 
 Name ->  Drag 
[+] Avaliable gesture: 
 Name ->  Pinch 
[+] Avaliable gesture: 
 Name ->  Rotate 
[+] Avaliable gesture: 
 Name ->  Tap 
[+] Avaliable gesture: 
 Name ->  Touch 

I have not modified the touchegg.conf file, and last I changed (which was over 6 months ago), I used touchegg-gui. I did, however, just double checked the syntax of that file, and I have looked online for help, but I haven't found anything. Does touchegg depend on any of the packages I upgraded? Do you guys have any suggestions for troubleshooting this?

**Comment by JoseExposito** [comment]
Did you tried to recompile Touchégg? Maybe it is a problem with some updated dependencies and the compile log could give us more information.

**Comment by 2edff206** [comment]
I have exactly the same problem. I updated to 17.04 today and touchegg stopped working

**Comment by boardend** [comment]
Same problem here. After update to 17.04 multi touch gestures stopped working and reinstalling Touchegg didn't help... Let me know if I can help with Infos/Logs.

**Comment by 2edff206** [comment]
Here is a bug report about it on laucnhpad : https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-input-synaptics/+bug/1684336

**Comment by danielegrattarola** [comment]
Same problem here, I only noticed today because I have been using an external mouse for a while. 
I installed it with `sudo apt install touchegg`, could uninstalling and compiling it from source be of any help?

**Comment by urbie-mk2** [comment]
use old synaptics x11 driver or [apply patch](https://gist.github.com/urbie-mk2/ae80fedbeded12084b7227b0ef53aeec)

**Comment by bndr32** [comment]
I had the same problem, I went to the link provided by urbie-mk2:

[https://gist.github.com/urbie-mk2/ae80fedbeded12084b7227b0ef53aeec](url)

 where I followed bndr32's comment and got functionality back. Hope this helps!

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
