### ISSUE TITLE
Does Touchégg deal with palm detection?

### ISSUE THREAD

**Issue by lindhe** [JoseExposito/touchegg#302]
I'm having issues with the touch pad on my Lenovo Carbon X1 Synaptics touchpad, that the libinput drivers does not seem to support palm detection.

Would Touchégg be able to sort this out for me, or does Touchégg rely on the drivers to handle palm detection correctly in the first place?

**Comment by JoseExposito** [comment]
Touchégg relays on Synaptics to handle palm detection. In addition, it won't work with libinput drivers.
