### ISSUE TITLE
Which GUI has been used for the demonstration video?

### ISSUE THREAD

**Issue by janopae** [JoseExposito/touchegg#303]
Hello,
the Touchegg demonstation video from 2011 uses a really nice looking GUI. What's its name?Where can I get it from? 

Thanks! :)

**Comment by JoseExposito** [comment]
Hi,

That GUI used to be part of the Touchégg project, however I dropped support because I didn't have time to keep working on it.

At the moment you can use Touchégg GCE, developed and maintainer by @Raffarti:
https://github.com/Raffarti/Touchegg-gce

Jose

**Comment by janopae** [comment]
Okay, tank you, your GUI looked cooler than Gce, but Gce is also great!
