### ISSUE TITLE
Does not work on OpenSUSE tumbleweed

### ISSUE THREAD

**Issue by AlexCzar** [JoseExposito/touchegg#305]
I have v 1.1.1 installed from Tumbleweed repository. It does not recognize any gestures at all on both synaptics and libinput driver, something is working on evdev driver, but it's unusable even without touchegg.
My DE is Plasma 5.9.5

**Comment by urbie-mk2** [comment]
touchegg does not work with libinput.
for synapitcs you need the old driver or [apply patch](https://gist.github.com/urbie-mk2/ae80fedbeded12084b7227b0ef53aeec)

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

It should work out of the box on OpenSUSE. There is a RPM package available.

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.

**Comment by rrrepsac** [comment]
Opensuse tumbleweed, libinput, elan touchpad. touchegg doesn't add new gestures (three fingers swipe, etc.)
It seems that i do something wrong. Could you help me?

**Comment by rrrepsac** [comment]
I added $USER to input group, reinstall from github rpm and it worked. thanks
