### ISSUE TITLE
magic trackpad 2

### ISSUE THREAD

**Issue by Sean-Sekora** [JoseExposito/touchegg#306]
I'm trying to get touchegg working for a magic trackpad 2 but have not been able to get it to work. I've also not been able to locate any information on how to do this. First question, is it possible to use a magic trackpad 2 with touchegg? And if so are there any instructions on how to do this?

**Comment by JoseExposito** [comment]
Apparently, the Magic Trackpad 2 is not supported:
https://wiki.ubuntu.com/Multitouch/HardwareSupport

**Comment by x-ji** [comment]
It should be supported with the newest patch into the Linux kernel: https://github.com/robotrovsky/Linux-Magic-Trackpad-2-Driver, https://git.kernel.org/pub/scm/linux/kernel/git/jikos/hid.git/commit/?h=for-next&id=9d7b18668956c411a422d04c712994c5fdb23a4b, maybe touchegg can also consider supporting it in the future?

**Comment by JoseExposito** [comment]
uTouch is almost abandoned by Ubuntu, but I hope that patch makes the Magic Trackpad 2 work with uTouch.

If so, Touchègg will work as soon as the patch is installed.
