### ISSUE TITLE
Disable for some apps?

### ISSUE THREAD

**Issue by verge-36** [JoseExposito/touchegg#307]
Is there a way to disable touchegg for some applications, so that it doesn't "eat" the touch events and lets the application process them? Google chrome, for example, is capable of pinch to zoom in/out. However I'm unable to make use of that functionality when touchegg is running. Thanks

**Comment by urbie-mk2** [comment]
load up touchegg-gce, create a new category, add a gesture and have it use 'no action'.

**Comment by NitroBAY** [comment]
It would be even better if you we could make some passthrough for gestures. Like not consuming at all two fingers pinching so zoom don't break.
Is it even possible though ?
Thanks.
