### ISSUE TITLE
Continuous drag-and-drop with pauses (lift fingers off the touchpad) support

### ISSUE THREAD

**Issue by sasoiliev** [JoseExposito/touchegg#308]
Hi,

I'm trying to configure touchegg with Mac-like three finger drag. In Mac OS the gesture supports the following sequence:

1. Tap three fingers and start dragging - drag action is activated.
2. Lift your fingers from the touchpad in order to reposition them and continue the drag operation - the drag actions is not interrupted if you reposition and continue dragging fast enough.
3. Tap again and continue dragging - drag action is continued from where you left off.

This is crucial in situations where for example you need to select a large block of text and you reach the border of the trackpad while you still have text left to select.

I'd guess naively that it would not be too hard to implement support for this. Adding a (configurable?) timeout and making the gesture finish condition something like: `timeout_has_passed or another_gesture_has_started`. This way the act of lifting your fingers off the trackpad would not immediately trigger the gesture finish, but starting another gesture (e.g. two finger tap) would.

I hope I've managed to explain clearly.

Thanks!

**Comment by urbie-mk2** [comment]
can be done by simply commenting out one line. 
See end of ```src/touchegg/actions/implementation/DragAndDrop.cpp```

```
 void DragAndDrop::executeFinish(const QHash<QString, QVariant>& /*attrs*/)
 {
    //XTestFakeButtonEvent(QX11Info::display(), this->button, false, 0);
 }
```
You start three finger drag normally. Then you can continue moving cursor with one finger. scrolling in the meanwhile works as well if you dont have 2-finger gestures enabled for processing by touchegg.

You can make use of QTimer of you want something more but there it is, all you need is controlling the calls to XTestFakeButtonEvent.

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
