### ISSUE TITLE
How to use it in centos?

### ISSUE THREAD

**Issue by a523** [JoseExposito/touchegg#313]
when make:
      In file included from src/touchegg/config/Config.h:24:0,
                 from src/touchegg/config/Config.cpp:21:
./src/touchegg/util/Include.h:24:22: 致命错误：QtCore：没有那个文件或目录
     #include <QtCore>
                      ^
编译中断。
make: *** [Config.o] 错误 1

**Comment by JoseExposito** [comment]
You can try this:
https://copr.fedorainfracloud.org/coprs/mhoeher/multitouch/

Have in mind that Touchegg will not work if you are using the libinput driver or Wayland.
