### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by nemaniarjun** [JoseExposito/touchegg#314]
https://github.com/JoseExposito/touchegg/wiki/All-actions-supported-by-Touch%C3%A9gg

In action: SEND KEYS
`withput` should be `without`

**Comment by JoseExposito** [comment]
Thanks :)

**Comment by nemaniarjun** [comment]
Also consider adding the following example. Good for people who want Desktop switching in Unity ;)
```
<gesture type="DRAG" fingers="3" direction="DOWN">
        <action type="SEND_KEYS">Control+Alt+Up</action>
</gesture>
```
