### ISSUE TITLE
Change target device of touchegg

### ISSUE THREAD

**Issue by Wursteintopf** [JoseExposito/touchegg#315]
I'm having trouble to get touchegg to work on my Lenovo Yoga 500, which is a device with a touchscreen AND a normal touchpad. And after installing touchegg it works like a charm on the touchscreen, but thats not the device, I wanna use it on, I wanna use it on my normal touchpad. So is there any possibillity to either change the target-device of touchegg or add a second one?

**Comment by urbie-mk2** [comment]
The devices are not determined by touchegg directly. Instead touchegg relies on geis (Gesture Engine Interface and Support). Geis gets the device info by dbus messages. If you have a look at the geis source file `geis_dbus_client.c`
function `_geis_dbus_client_message_handler`
message `GEIS_DBUS_DEVICE_AVAILABLE`
there is a call to `_client_device_available`
which in turn calls `geis_register_device` (file geis.c)

so it might be a problem with registering the device but could also be something else.

to see which devices are registered open a terminal, `export GEIS_DEBUG=3` and run `/usr/bin/touchegg` from there. 

you should see the debug messages from geis, I hope this helps for a start.

**Comment by Wursteintopf** [comment]
Thanks for the hint! As far as I'm able to interpret the debug messages its excactly what you said, only my ELAN Touchscreen get registered, but not my ALPS GlidePoint. But, how do I change that? (Sorry for my stupid questions, but I'm completely new to Linux.)

**Comment by Wursteintopf** [comment]
Thanks for the hint! As far as I'm able to interpret the debug messages its excactly what you said, only my ELAN Touchscreen get registered, but not my ALPS GlidePoint. But, how do I change that? (Sorry for my stupid questions, but I'm completely new to Linux.)

**Comment by urbie-mk2** [comment]
please post the deubg log here.

**Comment by Wursteintopf** [comment]
If I'm not to dumb this should be the input driver:

filename:       /lib/modules/4.10.0-40-generic/kernel/drivers/input/input-leds.ko
license:        GPL v2
description:    Input -> LEDs Bridge
author:         Dmitry Torokhov <dmitry.torokhov@gmail.com>
author:         Samuel Thibault <samuel.thibault@ens-lyon.org>
srcversion:     9F9CBD7AB65E9DA2C3DD5EA
alias:          input:b*v*p*e*-e*11,*k*r*a*m*l*s*f*w*
depends:        
intree:         Y
vermagic:       4.10.0-40-generic SMP mod_unload 

And I've attached the debug log in a txt file:
[log.txt](https://github.com/JoseExposito/touchegg/files/1582820/log.txt)

**Comment by urbie-mk2** [comment]
check /var/log/Xorg.0.log for drivers in use. look for lines with 
`Loading /usr/lib/xorg/modules/input/`
where you can see the driver and the version
and
`Using input driver '<drivername>' for '<touchdevicename>'`
where you see which driver is being used for the touch device

**Comment by Wursteintopf** [comment]
I can find the following lines for my two touch devices:

```
Loading /usr/lib/xorg/modules/input/evdev_drv.so
Using input driver 'evdev' for 'ELAN Touchscreen'
```

```
Loading /usr/lib/xorg/modules/input/synaptics_drv.so
Using input driver 'synaptics' for 'AlpsPS/2 ALPS GlidePoint'
```

**Comment by urbie-mk2** [comment]
Driver version would have been important here, so I just suspect the driver is too new. Install the synaptics driver version at https://github.com/urbie-mk2/xf86-input-synaptics and it will work.

**Comment by Wursteintopf** [comment]
Well, since its a freshly installed ubuntu thats possible. But now I'm stuck with:
`configure: error: Package requirements (x11 inputproto xi >= 1.2) were not met:

No package 'xi' found`

And I'm not able to find the required package.

**Comment by urbie-mk2** [comment]
the authors of the synaptics drivers decided to remove a part beginning in version 1.8.99 onwards that is required by touchegg. I just reverted the required changes. You can as well install an older driver before version 1.8.99 and have the same effect. I did no change the driver version since it is an inofficial driver only required to make touchegg run and my assumption is that it will not be bundled in distributions. I made a small change to indicate whether the original or the modified version is being loaded by X11 (1.9.1).

Install, reboot, check if it is actually loaded and run touchegg with debug variable again.

**Comment by Wursteintopf** [comment]
Sorry for asking stupid question again, but how do I check, if it's actually loaded? Cause I still get the same debug log and touchegg is still not running on my touchpad.

[debug.txt](https://github.com/JoseExposito/touchegg/files/1584723/debug.txt)

**Comment by urbie-mk2** [comment]
you have to download the github repository again that I linked above, recompile it, install it, reboot and check `/var/log/Xorg.0.log` for the synaptics version. it should be 1.9,1

**Comment by Wursteintopf** [comment]
So, I cloned the github repository, run the autogen.sh, run make, run sudo make install and rebooted. Nevertheless my Xorg.0.log still displays the following:
```
 [    20.214] (II) Loading /usr/lib/xorg/modules/input/synaptics_drv.so
 [    20.215] (II) Module synaptics: vendor="X.Org Foundation"
 [    20.215]    compiled for 1.19.3, module version = 1.9.0
```

**Comment by urbie-mk2** [comment]
this indicates that either the wrong module is loaded or you have an old version of the repository. check the file configure.ac and look for the AC_INIT macro, second argument should be the version and recompile with ./configure --prefix=/usr , then make and reinstall.

**Comment by Wursteintopf** [comment]
Well, did that, now I get the Errormessage "Couldn't find synaptics properties. No synaptics driver loaded?" as soon as I log in.

**Comment by urbie-mk2** [comment]
Ok it seems you dont have a configuration file for the driver installed, try 
`sudo cp /usr/share/X11/xorg.conf.d/50-synaptics.conf /etc/X11/xorg.conf.d/50-synaptics.conf`
or
`sudo cp /usr/share/X11/xorg.conf.d/70-synaptics.conf /etc/X11/xorg.conf.d/50-synaptics.conf`
depending on the driver name you might need to make changes to the reference configuration file.
merry christmas as well

**Comment by Wursteintopf** [comment]
I had a 70-synaptics.conf in `/usr/share/X11/xorg.conf.d` and tried copying it to `/etc/X11/xorg.conf.d` as 70-synaptics.conf and as 50-synaptics.conf but neither of the options worked, I still get the same error message on login. (And my Touchpad isn't working anymore at all.)

**Comment by Wursteintopf** [comment]
Oh, and just for context, my Xorg.0.log says this now:
```
508 [    13.927] (II) LoadModule: "synaptics"
509 [    13.927] (II) Loading /usr/lib/xorg/modules/input/synaptics_drv.so
510 [    13.928] (II) Module synaptics: vendor="X.Org Foundation"
511 [    13.928]    compiled for 1.18.4, module version = 1.9.1
512 [    13.928]    Module class: X.Org XInput Driver
513 [    13.928]    ABI class: X.Org XInput driver, version 22.1
514 [    13.928] (EE) synaptics: module ABI major version (22) doesn't match the server's version (2    4)
515 [    13.928] (II) UnloadModule: "synaptics"
516 [    13.928] (II) Unloading synaptics
517 [    13.928] (EE) Failed to load module "synaptics" (module requirement mismatch, 0)
518 [    13.928] (EE) No input driver matching `synaptics'
519 [    13.928] (II) Falling back to input driver `libinput'
520 [    13.928] (II) LoadModule: "libinput"
521 [    13.928] (WW) Warning, couldn't open module libinput
522 [    13.928] (II) UnloadModule: "libinput"
523 [    13.928] (II) Unloading libinput
524 [    13.928] (EE) Failed to load module "libinput" (module does not exist, 0)
525 [    13.928] (II) config/udev: Adding input device AlpsPS/2 ALPS GlidePoint (/dev/input/mouse0)
526 [    13.928] (**) AlpsPS/2 ALPS GlidePoint: Ignoring device from InputClass "touchpad ignore dup    licates"
```

**Comment by Wursteintopf** [comment]
So, I tried adding 
```
Section "Server Flags"
          Option          "IgnoreABI"
EndSection
```
to my 70-synaptics.conf which made the touchpad work for a few seconds, before crashing the whole system. Had do delete those lines via root bash to startup the system again.

**Comment by urbie-mk2** [comment]
woops, xorg server won't like that. ok, can you check the value for `ABI_XINPUT_VERSION` in your `/usr/include/xorg/xf86Module` ?
it should state at least 23 or higher. Mine is at 24.

Could some files be out of sync with the package repository ? I dont know which linux you have. Try re-installing the xorg core package

**Comment by urbie-mk2** [comment]
Of course without much hassle you could try to downgrade the synaptics driver package to a lower versiosn if possible and have the same effect (minus a few bug fixes).

**Comment by Wursteintopf** [comment]
`#define ABI_XINPUT_VERSION  SET_ABI_VERSION(22, 1)`
I dont know why any files should be out of sync with the package repository, since its a completely fresh linux. I'm using a Ubuntu 16.04 LTS btw.

**Comment by Wursteintopf** [comment]
Well, reinstalling xserver-xorg-core again killed my system completely and this time I have no idea, how to fix it :D

**Comment by urbie-mk2** [comment]
if you want to fix it, you can swap to another tty by pressing ctrl+alt+F2 / F3 / F4 ... and then continue from there. By the sound of it the system was not quite 100% functional in the beginning. Save important files , like in /home, /root, /etc and /var on a thumb drive, so you can restore just in case. 
or try arch linux if you to build your own linux system.

**Comment by urbie-mk2** [comment]
I made a xubuntu 16.04 vm. I had to install the following packages to build the driver
git
build-essential
automake
autoconf
xutils-dev
xorg-dev
libtool
libev-dev
libev-libevent-dev
libevdev-dev

**Comment by Wursteintopf** [comment]
I think I'm to lazy to work myself into Arch, I pretty much like ubuntu. But reinstalling the whole system sounds like a good idea, I also have the feeling that the system wasnt 100% functional in the beginning. I think I'll just reinstall the whole ubuntu and then try do downgrade the driver again.

**Comment by urbie-mk2** [comment]
Forgot to mention, the `/usr/include/xorg/xf86Module.h` had abi version 24 after installing the packages.
I am sure after re installing ubuntu it will work.

**Comment by Wursteintopf** [comment]
So, reinstalling the whole ubuntu worked. I was able to install your driver if I configured it the way you told me to: `./configure --prefix=/usr` With a regular `./autogen.sh` I got the same problem as before, that in my `Xorg.0.log` I was only able to find the 1.9.0 driver version. But the `xf86Module.h` now has ABI Version 24 and the driver is running fine. Also after reinstalling touchegg and running a Debug Log it seems that both devices get registered:
```
GEIS(debug)-geis_register_device:1259 registering device "ELAN Touchscreen" id 25520
GEIS(debug)-geis_register_device:1259 registering device "AlpsPS/2 ALPS GlidePoint" id 27904
```
So far so good, but now the multitouch gestures which before at least worked on the ELAN Touchscreen now dont do anything at all, neither on the Touchscreen, nor on my ALPS Glidepoint. Did I miss any dependencies for touchegg?

**Comment by Wursteintopf** [comment]
So, reinstalling the whole ubuntu worked. I was able to install your driver if I configured it the way you told me to: `./configure --prefix=/usr` With a regular `./autogen.sh` I got the same problem as before, that in my `Xorg.0.log` I was only able to find the 1.9.0 driver version. But the `xf86Module.h` now has ABI Version 24 and the driver is running fine. Also after reinstalling touchegg and running a Debug Log it seems that both devices get registered:
```
GEIS(debug)-geis_register_device:1259 registering device "ELAN Touchscreen" id 25520
GEIS(debug)-geis_register_device:1259 registering device "AlpsPS/2 ALPS GlidePoint" id 27904
```
So far so good, but now the multitouch gestures which before at least worked on the ELAN Touchscreen now dont do anything at all, neither on the Touchscreen, nor on my ALPS Glidepoint. Did I miss any dependencies for touchegg?

**Comment by Wursteintopf** [comment]
Woops, didnt do that on purpose, sorry. 

So, after creating a .xprofile in my home directory with the following content:
```
synclient TapButton2=0
synclient ClickFinger2=0
synclient TapButton3=0
synclient ClickFinger3=0
synclient HorizTwoFingerScroll=0
synclient VertTwoFingerScroll=0
touchegg &
```
I'm now able to use multitouch on my ELAN Touchscreen again, but its still not working on my ALPS Glidepoint.

Here you can find the current Geis Debug Log:
[log.txt](https://github.com/JoseExposito/touchegg/files/1587671/log.txt)

As far as I'm concerned, something is going wrong here:
```
GEIS(debug)-geis_subscription_new:409 created subscription "subscription" id 0
GEIS(debug)-geis_backend_token_activate:63 called
GEIS(debug)-_geis_grail_activate_with_filters:2351 filter 0x11a8ae0 'filter' matches ALL devices
GEIS(debug)-_geis_grail_filter_gestures:2095 mask=0x00000008 start=2 min=2 max=2
GEIS(debug)-_geis_grail_activate_for_device_region:2224 subscription='subscription' filter='filter' device=31680 'ELAN Touchscreen' window=0x00000104 ugsub=0x11a6b20
GEIS(error)-geis_grail_window_grab_store_grab:153 error 1 returned from XIGrabTouchBegin()
GEIS(error)-_geis_grail_activate_for_device_region:2236 failed to grab input on window 0x00000104
```

**Comment by urbie-mk2** [comment]
try to get the synaptics 1.9.1 (or <1.8.99) driver running

**Comment by urbie-mk2** [comment]
[synaptics_drv.tar.gz](https://github.com/JoseExposito/touchegg/files/1587730/synaptics_drv.tar.gz)
driver precompiled on the xubuntu 16.04 vm

**Comment by Wursteintopf** [comment]
Well, I currently have your 1.9.1 running

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
