### ISSUE TITLE
Stopped working after upgrading to Ubuntu 17.10

### ISSUE THREAD

**Issue by OmarElebiary** [JoseExposito/touchegg#316]
After upgrading to Ubuntu 17.10, gestures are not being detected.

**Comment by urbie-mk2** [comment]
output of touchegg command in terminal ?

**Comment by OmarElebiary** [comment]
@urbie-mk2 
this is the output in terminal 

`Reading config from  "/home/omar/.config/touchegg/touchegg.conf" 
Try to make a multitouch gesture. If everything goes well the information about the gesture must appear 
[+] Avaliable gesture: 
	 Name ->  Flick 
[+] Avaliable gesture: 
	 Name ->  Drag 
[+] Avaliable gesture: 
	 Name ->  Pinch 
[+] Avaliable gesture: 
	 Name ->  Rotate 
[+] Avaliable gesture: 
	 Name ->  Tap 
[+] Avaliable gesture: 
	 Name ->  Touch `

but nothing happens when making any gesture.

**Comment by urbie-mk2** [comment]
Good, touchegg is working.
I suspect the same problem like in issue #300.

**Comment by urbie-mk2** [comment]
I put up a repo to get the synaptics 1.9 driver that will work together with touchegg

**Comment by thebunnyrules** [comment]
Are you on Xor or Wayland, I noticed on my machine that it works on Wayland but not on Xorg.

**Comment by OmarElebiary** [comment]
@thebunnyrules Yes, I am using Xorg. I changed to libinput-gestures which works fine with gnome and Xorg.

**Comment by thebunnyrules** [comment]
@OmarElebiary thanks so much for the feedback. Are you using libinput-gestures as a replacement to touchegg or are you using it as a supplement to get it to work? Could you tell me more specifically what you did?

**Comment by OmarElebiary** [comment]
@thebunnyrules  I use libinput-gestures as replacement to touchegg, the problem wasn't in touchegg i switched from synaptics to libinput and use libinput-gestures with libinput.

**Comment by thebunnyrules** [comment]
I just read through libinput-gestures git page. I think I'll give it a skip, since I'm not planning to stick around in XOrg and since I know touch egg works in Wayland.
