### ISSUE TITLE
Doesn't work on linux mint 18.3 Cinnamon

### ISSUE THREAD

**Issue by GzhiYi** [JoseExposito/touchegg#317]
My system info :

![image](https://user-images.githubusercontent.com/21136420/34211600-90b2d3f4-e5d4-11e7-8698-13c49a509042.png)
Everything have been done for installing touchegg but it seems no working.
added 
```
touchegg &
```
in .xprofile.
Rebot it shows on system monitor.
command on termimal shows that:
![image](https://user-images.githubusercontent.com/21136420/34211822-3d4ebe16-e5d5-11e7-8336-522e73306474.png)
Do I miss something and can anyone help me out please.

**Comment by urbie-mk2** [comment]
please state input-synaptics x11 driver version.

**Comment by gottaknow** [comment]
Same issue here. Xserver-xorg-input-synaptics Version 1.8.2-1ubuntu3

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
