### ISSUE TITLE
touchegg not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by pedrosans** [JoseExposito/touchegg#318]
Hi, I couldn't make touchegg to work on Ubuntu 16.04. I followed instructions at https://askubuntu.com/questions/789915/ubuntu-16-04-multitouch-gestures
Did I miss something? Would to compile from source make a difference? I'm sending info on my setup below, let me know if I missed something important.

cheers

synaptics version: xserver-xorg-input-synaptics-hwe-16.04 (1.9.0-1ubuntu1~16.04.1) 
.xprofile file: https://pastebin.com/rYnMc77H
System infor: https://pastebin.com/g1924ESx
GEIS debug: https://pastebin.com/2y9bKmFz

**Comment by urbie-mk2** [comment]
check #316

**Comment by pedrosans** [comment]
I downgraded my synaptics driver to version 1.8.3 and touchegg started working OK. For reference:

1) remove the currenty synaptics driver using apt-get remove

```sh
sudo apt-get remove xserver-xorg-input-synaptics 
```

2) build + install the working version:

```sh
git clone git://anongit.freedesktop.org/xorg/driver/xf86-input-synaptics
cd xf86-input-synaptics/
git checkout xf86-input-synaptics-1.8.3
git co -b working-branch
sudo apt install autoconf xutils-dev xorg-dev libtool libevdev-dev
./autogen.sh 
./configure --prefix=/usr
make
sudo make install
```
