### ISSUE TITLE
Problem with sources

### ISSUE THREAD

**Issue by andelnegro6** [JoseExposito/touchegg#319]
I follow the usual instructions https://github.com/JoseExposito/touchegg/wiki/How-to-compile-Touch%C3%A9gg-source-code
to compile source code, but once I run build-dep (step 2):
"Reading package lists... Done
E: You must put some 'source' URIs in your sources.list"
What's the sources I'm missing? thanks.

Ubuntu version: xenial 16.04
(partitioned OS)

**Comment by JoseExposito** [comment]
Enable this:
https://askubuntu.com/a/857433
