### ISSUE TITLE
utouch

### ISSUE THREAD

**Issue by red-head76** [JoseExposito/touchegg#324]
Hi, i have a little problem with the installation:
`sudo apt-get install build-essential libqt4-dev utouch libgeis-dev libx11-6 libxtst-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package utouch
`
Maybe im not familiar enough with linux to solve this, but i tried via apt search / install to find something about utouch aswell as simply searching the internet. But i wasn't able to find something about it.

My System Info:
Linux Mint 18.1 Cinnamon 64-bit
Linux version 4.4.0-53-generic (buildd@lcy01-28) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #74-Ubuntu SMP

May you could help me out with this.

**Comment by Zmk55** [comment]
Did you ever get this resolved? I have the same issue with Ubuntu 18.04

**Comment by red-head76** [comment]
sadly no -.-

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
