### ISSUE TITLE
Is this insecure like libinput-gestures?

### ISSUE THREAD

**Issue by rpgdev** [JoseExposito/touchegg#325]
Will any app running under a regular user be able to read input after installing this? Is this insecure like libinput-gestures?

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

**About your question**, no, Touchégg is **not** insecure. You don't need to add your user to the `input` group allowing every app to access, for example, every key you press. 
If you are curios about the technical details, Touchégg runs in two separated processes.
One is a systemd daemon with access to libinput that only exposes the minimal input information to perform gestures.
The other one is run by your user and it doesn't require any extra privileges to run.

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
