### ISSUE TITLE
Hard-coded path to touchegg.conf

### ISSUE THREAD

**Issue by bobnewgard** [JoseExposito/touchegg#326]
I'm not familiar with the qmake build system, but is there a way to reflect the value of config.path in touchegg.pro in the assignment to the *USR_SHARE_CONFIG_FILE variable in src/touchegg/config/Config.cpp?

This is just FYI.  I've modified Config.cpp, so I'm good to go.

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
