### ISSUE TITLE
Core dumped error

### ISSUE THREAD

**Issue by felmoreno1726** [JoseExposito/touchegg#327]
Here is my ~/.config/touchegg file looks. After adding the lines 26-32 (bolded) I get a core dumped error. Also the last two gestures are recognized, but they have no apparent action on the Firefox browser.

<touchégg>	
    
    <settings>
        <property name="composed_gestures_time">0</property>
    </settings>
    

    <application name="All">
        
        <gesture type="TAP" fingers="2" direction="">
            <action type="MOUSE_CLICK">BUTTON=0</action>
        </gesture>
    
        <gesture type="TAP" fingers="3" direction="">
            <action type="MOUSE_CLICK">BUTTON=2</action>
        </gesture>

        <gesture type="TAP" fingers="5" direction="">
            <action type="CLOSE_WINDOW"></action>
        </gesture>

        <gesture type="DRAG" fingers="2" direction="ALL">
            <action type="SCROLL">SPEED=7:INVERTED=false</action>
        </gesture>
	
	**<gesture type="PINCH" fingers="2" direction="IN">
	    <action type="MAXIMIZE_RESTORE_WINDOW"></action>
	</gesture>

	<gestrue type="PINCH" fingers="2" direction="OUT">
	    <action type="MINIMIZE_WINDOW"></action>
	</gesture>**

        <gesture type="DRAG" fingers="3" direction="UP">
            <action type="MAXIMIZE_RESTORE_WINDOW"></action>
        </gesture>
        
        <gesture type="DRAG" fingers="3" direction="DOWN">
            <action type="MINIMIZE_WINDOW"></action>
        </gesture>
        
        <gesture type="DRAG" fingers="3" direction="LEFT">
            <action type="MOVE_WINDOW"></action>
        </gesture>
        
        <gesture type="DRAG" fingers="3" direction="RIGHT">
            <action type="MOVE_WINDOW"></action>
        </gesture>

        <gesture type="DRAG" fingers="4" direction="UP">
            <action type="SEND_KEYS">Alt+Control+Down</action>
        </gesture>
        
        <gesture type="DRAG" fingers="4" direction="DOWN">
            <action type="SEND_KEYS">Alt+Control+Up</action>
        </gesture>

	<gesture type="TAP" fingers="4" direction="">
		<action type="SEND_KEYS">Alt+F1</action>
	</gesture>

        <gesture type="PINCH" fingers="3" direction="ALL">
            <action type="RESIZE_WINDOW"></action>
        </gesture>
        
        <gesture type="PINCH" fingers="5" direction="ALL">
            <action type="SEND_KEYS">Alt+F1</action>
        </gesture>

    </application>

    <application name="Firefox">

        <gesture type="DRAG" fingers="4" direction="LEFT">
            <action type="SEND_KEYS">Alt+Left</action>
        </gesture>

        <gesture type="DRAG" fingers="4" direction="RIGHT">
            <action type="SEND_KEYS">Alt+Right</action>
        </gesture>
        
    </application>

</touchégg>

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
