### ISSUE TITLE
Cannot configure only 3 finger gesture in Mint 18 (Ubuntu 16)

### ISSUE THREAD

**Issue by dizzam** [JoseExposito/touchegg#328]
## System configuration

 - Operating System: Linux Mint 18.3 Sylvia
 - Desktop Environment: Cinnamon 3.6.7
 - Synaptics version: xserver-xorg-input-synaptics (1.8.2-1ubuntu3)
 - Devices: AlpsPS/2 ALPS GlidePoint 
 - Touchegg version: Touchegg (1.1.1-0ubuntu1)

## Problem

I first run touchegg with the following configuration, as suggested in Wiki:

```bash
synclient TapButton2=0
synclient TapButton3=0
synclient ClickFinger2=0
synclient ClickFinger3=0
synclient HorizTwoFingerScroll=0
synclient VertTwoFingerScroll=0
```

Then everything works fine. However, the speed of two finger scrolling is too annoying so I'm trying to **use synaptics to manage gestures with 1 and 2 fingers (left click, right click and two fingers scroll), and Touchégg to manage your personalised gestures with 3 or more fingers**, by using the following configuration:

```bash
synclient TapButton2=3
synclient TapButton3=0
synclient ClickFinger2=3
synclient ClickFinger3=0
synclient HorizTwoFingerScroll=1
synclient VertTwoFingerScroll=1
```

But at this time, touchegg doesn't work any more and there's no output in terminal.

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
