### ISSUE TITLE
touchegg doesn't work after closing the laptop lid

### ISSUE THREAD

**Issue by raspbeguy** [JoseExposito/touchegg#329]
I use touchegg on my GPD Pocket with Arch Linux and i3.
If I close the laptop lid and then open it again, touchegg don't react anymore. I looked at touchegg output, there is no error message. the programm is still running but has no effect. I have to kill it and restart it.
Is there a way to fix it?
Thanks

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
