### ISSUE TITLE
undefined symbol: _ZN12QApplication10commitDataER15QSessionManager

### ISSUE THREAD

**Issue by rtuz2th** [JoseExposito/touchegg#330]
Hi,
when I try to first run touchegg after installation this:

undefined symbol: _ZN12QApplication10commitDataER15QSessionManager

is everything I get back from my terminal, I already tried reinstalling qt and reinstalling touchegg afterwards but this did not help. ldd of qt4 gives

linux-vdso.so.1 (0x00007fff7dd96000)
	libQtGui.so.4 => /usr/local/lib/libQtGui.so.4 (0x00007f9575950000)
	libQtCore.so.4 => /usr/local/lib/libQtCore.so.4 (0x00007f957546f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f95750e6000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9574ece000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9574add000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f95748be000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f95746a1000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f9574497000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f9574285000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f9573f4d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9573baf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f95739ab000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f95737a3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f95768ef000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f957357b000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f9573377000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f9573171000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f9572f5c000)

Im running Ubuntu 18.04 x64. Thank you for your help!

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
