### ISSUE TITLE
Does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by lucechec** [JoseExposito/touchegg#331]
Hello
I have a fresh install of Ubuntu 18.04 on a Macbook Pro mid 2012 and touchegg does not seem to work.
To be more precise, when launched in a terminal I get 

`Try to make a multitouch gesture. If everything goes well the information about the gesture must appear 
[+] Available gesture: 
	 Name ->  Flick 
[+] Available gesture: 
	 Name ->  Drag 
[+] Available gesture: 
	 Name ->  Pinch 
[+] Available gesture: 
	 Name ->  Rotate 
[+] Available gesture: 
	 Name ->  Tap 
[+] Available gesture: 
	 Name ->  Touch 
`

So installation seems OK, but when I make gestures nothing happens.

I have tried the following things:
- apply patch as described in https://gist.github.com/urbie-mk2/ae80fedbeded12084b7227b0ef53aeec
- I tried both with touchegg installed from packages or recompiled locally
- followed the instructions on https://www.maketecheasier.com/add-multitouch-gestures-ubuntu/

I also went through all reported issues without finding anything particularly helpful. Any ideas?

ps: while fusuma works, it does not allow the MacOS-like three-finger drag that I am desperately missing.

**Comment by thiswillbeyourgithub** [comment]
same here on a thinkpad T480s

**Comment by lib-lab** [comment]
same
error: You should fill sources.list with URI package sources with source code... something like that

**Comment by shacharoz** [comment]
same. 
i work with WaveShare touchscreen. ubuntu 18.04 with board with intel core i7 in it (not raspberry pi).
it worked for me with same pc when i had lubuntu. does it really different?

**Comment by liuyi92** [comment]
Maybe the GNOME3 conflicts with touchegg because mutter has grabbed the touchscreen while touchegg is going to do that...

**Comment by vegerot** [comment]
Hey.  Now almost a year later this does not seem to work on my Macbook Pro running Ubuntu 18.04.  Has anybody gotten this to work in 18.04?  Has anybody gotten it to work in 19.10 (I'll update if that's the case)

Are there any other packages that will let me have natural scroll direction and tap to click in i3 in Ubuntu on Macbook Pro?  If this package isn't being maintained anymore I will try another

**Comment by antotorov** [comment]
Still not working here. Please share if you find another solution!!
Best
AR

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

This new version is 100% compatible with Ubuntu 18.04 and Ubuntu 20.04 out of the box.

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
