### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by JoseExposito** [JoseExposito/touchegg#335]
Hi all!

I'm creating this issue as reference for the people interested in the project or finding issues o run it in modern distributions.

> **TL;DR** The status of this project is:
> 
> - If you are using an "old" distro (using the synaptics driver), Touchégg will work.
> - If you are using Wayland, it is impossible for a tool like this to work, at least for the moment
> - If you are using X11 and libinput driver (the case for most distros), I'm working on a solution
>
> I'll update my Twitter with the latest news!
> https://twitter.com/Jose__Exposito

**Background:**

The linux desktop stack has changed a lot since I started this project in 2011. Let me explain it a little bit:

_uTouch aka Canonical Multitouch:_

Canonical (the company behind Ubuntu) made a tremendous effort to bring multitouch support to the Linux desktop putting together a set of tools. One of this tools, actually the only one from the community, is Touchégg:

https://launchpad.net/canonical-multitouch

Touchégg uses this technology from Canonical under the hood to work. Unfortunately uTouch is not maintained anymore and it is not even possible to use it in libinput based desktop environments.

_libinput:_

Speaking about input management in Linux, libinput is the future and most likely the driver you are using right now on X11 to handle your mouse, keyboard, touchpad and other input devices.

Unfortunately Touchégg does not have support for this library yet, but I'm working on it right in the `feature/libinput` branch right now.

_Wayland:_

Wayland compositors access hardware input (including multitouch input) using libinput.
The "problem" is that only compositors can have access to this library and not third party tools like Touchégg.
Long story sort, if your desktop environment (Gnome, KDE...) is already running on Wayland, Touchégg will not work :(

**Comment by JoseExposito** [comment]
In addition to add support to libinput, I'm working on gesture animations, here is a quick demo of the maximize animation
https://twitter.com/Jose__Exposito/status/1299634078224973824?s=20

**Comment by m-roberts** [comment]
Can't wait for v2!

Any chance you can look into packaging for easy install on popular Linux distros? Debian would be a great addition, as this would make it easy to install on Raspberry Pi with a multi-touch touchscreen for controlling IOT projects!

**Comment by JoseExposito** [comment]
> Any chance you can look into packaging for easy install on popular Linux distros?

Yes, deb and rpm packages will be available

> ... multi-touch touchscreen for controlling IOT projects!

However the goal of the project is to handle touchpads, not touchscreens, sorry :(

> Also, has anybody suggested exposing a socket interface for the gestures, to allow long-running processes to handle the events in a more resource-efficient manner than executing a script? Just a thought!

Touchégg is a C++ program, not a script, that runs in the background. It's designed to be resource efficient, so you won't have problems in hardware like the Raspberry Pi:

![Screenshot from 2020-09-01 11 15 10](https://user-images.githubusercontent.com/1335948/91831697-ad70bf00-ec44-11ea-8927-f54de21d0e0f.png)

**Comment by m-roberts** [comment]
Hi! Fortunately, touchscreen driver uses the multi-touch Linux driver in the same way as a touchpad - it actually works identically.

And with regards to the socket interface, I meant as an alternative to `RUN_COMMAND` if the gesture was to communicate with another long-running process/daemon.

Anyway, thanks again - I am very excited to see v2 of this project!

**Comment by yerbestpal** [comment]
> Hi! Fortunately, touchscreen driver uses the multi-touch Linux driver in the same way as a touchpad - it actually works identically.
> 
> And with regards to the socket interface, I meant as an alternative to `RUN_COMMAND` if the gesture was to communicate with another long-running process/daemon.
> 
> Anyway, thanks again - I am very excited to see v2 of this project!

Does this mean that the code will just automatically work for touchscreens without any specific configuration?

**Comment by m-roberts** [comment]
> Does this mean that the code will just automatically work for touchscreens without any specific configuration?

As long as it's using the standard Linux multi-touch driver, yes!

**Comment by JoseExposito** [comment]
Quick update with more animations and how they look on Ubuntu/Gnome:
https://twitter.com/Jose__Exposito/status/1304424515125022722?s=20

And also how the change desktop animation looks like:

![change_desktop](https://user-images.githubusercontent.com/1335948/92998840-abe4a800-f51c-11ea-882f-0cc2678e2d83.gif)

**Comment by dit7ya** [comment]
Great to know a v2 is under way! I have been eagerly looking for a touchscreen gesture solution for GNU/Linux and have not found any. 

Two requests:

1. Can you write a little more detailed installation and usage guide for the `libinput` branch? As I have not used the previous version I am not sure what I am supposed to know already.

2. I might be wrong but it seems like the actions are hardcoded in the library. Wouldn't it be more versatile if we can just run commands using `xdotool` or alike?

**Comment by JoseExposito** [comment]
Hi @dit7ya, thanks for your feedback :) 

> Can you write a little more detailed installation and usage guide for the libinput branch? As I have not used the previous version I am not sure what I am supposed to know already.

It is still a work in progress branch, that's why there is not many documentation yet. If you are using Ubuntu, the installation will be as simple as `apt-get install touchegg`, but I'll add more documentation before the release, don't worry.

> I might be wrong but it seems like the actions are hardcoded in the library. Wouldn't it be more versatile if we can just run commands using xdotool or alike?

Yes, that option was available in v1 and will be available in v2. I haven't implemented it yet though.

**Comment by ska2342** [comment]
Does it already make sense to compile it myself and test things out or is that too early?

**Comment by JoseExposito** [comment]
Hi @ska2342 ,

The feature/libinput branch is almost ready. I'm trying to solve a permissions issue (your user needs to be in the "input" group, and for security reasons this is not ideal) but speaking of functionality and stabillity I'm happy with the current status.

So, feel free to test it. Bug reports are welcome :)

**Comment by dit7ya** [comment]
I tried to compile it on Arch but received the following errors.

https://gist.github.com/dit7ya/c14ae8e9bd911baf468e2a173741c3fc

**Comment by JoseExposito** [comment]
@dit7ya , I created a issue so we can solve your problems:
https://github.com/JoseExposito/touchegg/issues/337

**Comment by JoseExposito** [comment]
Today I release Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme
