### ISSUE TITLE
libinput: no touchscreen gesture support

### ISSUE THREAD

**Issue by m-roberts** [JoseExposito/touchegg#336]
Hi.

The following steps work to get touchegg working on Raspberry Pi OS when used with the master branch:
```
wget http://ftp.de.debian.org/debian/pool/main/g/geis/libgeis-dev_2.2.17-1.1+b1_armhf.deb
wget http://ftp.de.debian.org/debian/pool/main/g/geis/libgeis1_2.2.17-1.1+b1_armhf.deb
sudo dpkg -i *.deb
sudo apt --fix-broken install -y
sudo apt-get install -y build-essential libqt4-dev libx11-6 libxtst-dev
git clone --depth=1 https://github.com/JoseExposito/touchegg
cd touchegg
qmake
make -j$(nproc)
sudo make install
DISPLAY=:0 touchegg
```

Note that GEIS support is not available in Debian Buster (stable), but is installable from Stretch (oldstable) without issue.

Here are my steps for attempting to use the `feature/libinput` branch:
```
# Setup
sudo usermod -a -G input pi  # add pi user to input group
sudo apt-get install git build-essential gdb cmake libudev-dev libinput-dev libpugixml-dev libcairo2-dev libx11-dev libxtst-dev libxrandr-dev  # install deps

# Build
git clone --depth=1 https://github.com/JoseExposito/touchegg.git -b feature/libinput
cd touchegg/
mkdir build
cd build/
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j$(nproc)

# Install (no 'sudo make install' available)
sudo cp touchegg /usr/bin/touchegg
sudo mkdir /usr/share/touchegg/
sudo cp ../installation/touchegg.conf /usr/share/touchegg/

# Run
DISPLAY=:0 touchegg
```

Unfortunately, my output is as follows:
```
pi@raspberrypi:~/touchegg/build $ DISPLAY=:0 touchegg
Starting Touchégg...
Parsing you configuration file...
Configuration parsed successfully
A list of detected compatible devices will be displayed below:
```

No further output is produced, but the process does not end.

How can I debug this? What is likely to be the issue? When I run `sudo evtest`, I can see the device:
```
pi@raspberrypi:~ $ sudo evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	raspberrypi-ts
Select the device event number [0-0]: 0
Input driver version is 1.0.1
Input device ID: bus 0x19 vendor 0x0 product 0x0 version 0x0
Input device name: "raspberrypi-ts"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 330 (BTN_TOUCH)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    199
      Min        0
      Max      799
    Event code 1 (ABS_Y)
      Value    228
      Min        0
      Max      479
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max        9
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max      799
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max      479
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
Properties:
  Property type 1 (INPUT_PROP_DIRECT)
Testing ... (interrupt to exit)
^C
pi@raspberrypi:~ $
```

**Comment by JoseExposito** [comment]
Hi @m-roberts 

Fist of all thanks a lot for your bug report!!

Is that a touch screen? My understanding is that libinput does not support touchscreen gestures:

https://wayland.freedesktop.org/libinput/doc/latest/gestures.html#gestures-touchscreens

Only devices with the "gesture" capability are supported. For example, this is the output for my Magic Trackpad:

```
$ sudo libinput list-devices
[...]
Device:           Apple Inc. Magic Trackpad 2
Kernel:           /dev/input/event19
Group:            5
Seat:             seat0, default
Size:             162x115mm
Capabilities:     pointer **gesture**
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    button-areas *clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a
```

I don't know why the libinput team took this decision, but there is not much we can do. I guess you can ask for support in their mailing list.

**Comment by m-roberts** [comment]
For posterity, here is what I found on my touchscreens:
```
Device:           ILITEK ILITEK-TP
Kernel:           /dev/input/event4
Group:            2
Seat:             seat0, default
Size:             309x174mm
Capabilities:     touch
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a
```

This means that I will be stuck using v1.1.1 as this still works for my use-case.

**Comment by m-roberts** [comment]
I would love to see the option of choosing a backend - libinput vs geis. That way, I could continue to use this project as it develops!

**Comment by JoseExposito** [comment]
Have you tried to ask to the libinput developers if there is a way to enable the gesture capability for touchscreens?
I understand that they don't want to force a way of using touchscreens due to the variety of use cases they can have (from mobile to tablet to IoT) but it'd be nice to be able to opt in the gesture capability.

About the geis backend:
I wrote v2 with multiple backend support in mind, it is only necessary to implement this interface using the geis backend:

https://github.com/JoseExposito/touchegg/blob/feature/libinput/src/gesture-gatherer/gesture-gatherer.h

However I wasn't able to configure the synaptic driver on Ubuntu 18 or 20. Did you manage to switch the driver?

Another option, better in my opinion, could be implement gestures from touch events, but I don't have a touch screen to test with 😞

**Comment by m-roberts** [comment]
Hi @JoseExposito - I have emailed you directly to discuss this matter further 😄

**Comment by NICHOLAS85** [comment]
[Gebaar](https://github.com/NICHOLAS85/gebaar-libinput) (Another gesture daemon) supports touchscreen gestures. Take a glance at how it was implemented there! 

That link is a personal fork of the project merging a couple features in, all the relevant info/links are at the top of the README.

**Comment by dit7ya** [comment]
@NICHOLAS85 Many many thanks for your work! I have been trying to get a Touchscreen gestures app to work for last two weeks after getting a 2-in-1 laptop but could not find any that worked (including the original Gebaar). I hope Touchscreen gestures become mainstream in GNU/Linux and many great projects such as Touchegg integrates support for it.

**Comment by NICHOLAS85** [comment]
@dit7ya I believe @gabrielstedman is responsible for the code adding touch support, I'm sure they'll appreciate your thanks!

**Comment by DarkFighterLuke** [comment]
> Another option, better in my opinion, could be implement gestures from touch events, but I don't have a touch screen to test with 😞

If you need a hand to test features on a non-touchegg-working touchscreen call on me!

**Comment by JoseExposito** [comment]
Just started the development of this feature in the feature/touchscreen branch: https://github.com/JoseExposito/touchegg/tree/feature/touchscreen

Not much going on yet, I'll let you know when it is ready for some testing :smile:

**Comment by JoseExposito** [comment]
Touchscreen support is merged into master now :tada:
I'll release a new version today so you can test it

**Comment by DarkFighterLuke** [comment]
> Touchscreen support is merged into master now tada
> I'll release a new version today so you can test it

Now events are recognized in the terminal window, except for tap&hold, it doesn't work. For example, I want to open the right-click menu on a file by holding on it on touchscreen, but it does nothing.

**Comment by JoseExposito** [comment]
Hi!

You can check the available gestures here:
https://github.com/JoseExposito/touchegg#available-gestures

Touchégg is in charge of "global" gestures. The feature you mention should be handled by the app... Some apps do it really well, like chrome for example, but some others are not quiet yet.

**Comment by parkerlreed** [comment]
KDE for example doesn't have any right click abilities on long hold. touchegg could be one solution to this issue. A long hold with any <x> fingers would be great.

**Comment by DarkFighterLuke** [comment]
Ok thank you @JoseExposito , so I'll try some other gesture and I'll let you know. 

Just while I am writing parkerlreed answered:


> KDE for example doesn't have any right click abilities on long hold. touchegg could be one solution to this issue. A long hold with any <x> fingers would be great.

Yes it would be very useful. KDE Plasma is far behind in this field, it seems they don't even try to support any touch feature...

**Comment by parkerlreed** [comment]
They do though. Long hold desktop or widgets for the actions. Drag in the Settings. It's fiarly well supported just not with all the expected actions. Here are the KDE and QT issues tracking this

https://phabricator.kde.org/T10783

https://bugreports.qt.io/browse/QTBUG-84179

**Comment by JoseExposito** [comment]
Have a look to this issue: https://github.com/JoseExposito/touchegg/issues/378
I'll implement it in a future release. Not sure if it is going to be 2.0.3 or 2.0.4
