### ISSUE TITLE
[libinput] Arch Linux compilation

### ISSUE THREAD

**Issue by JoseExposito** [JoseExposito/touchegg#337]
@dit7ya reported issues compiling the `feature/lininput` branch on Arch Linux:
https://github.com/JoseExposito/touchegg/issues/335#issuecomment-694939629

This is the output:
https://gist.github.com/dit7ya/c14ae8e9bd911baf468e2a173741c3fc

I moved the report to a new issues so it can be discussed here with more detail.

@dit7ya could you attach your gcc and cmake versions, please? This is my output:

```
➜  ~ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  ~ cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by pobrn** [comment]
I get the same error. `gcc` 10.2.0, `cmake` 3.18.3. Unconditionally including including `<filesystem>` solves the problem. Possibly the cmake configuration could be extended to check whether `#include <filesystem>` works.

**Comment by pobrn** [comment]
A better solution is to check for the existence of `<filesystem>` first, and then fall back to `<experimental/filesystem>`:

```
#if __has_include(<filesystem>)

#include <filesystem>

#else

#include <experimental/filesystem>
namespace std {
namespace filesystem = experimental::filesystem;
}

#endif
```

This compiles cleanly.

**Comment by yochananmarqos** [comment]
Preliminary [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/tree/master/touchegg) for 2.0.0
[Build log](https://pastebin.com/LAdWNCJk)

**Comment by JoseExposito** [comment]
Thank you very much for the report! I'll try to spare some time this week to install ArchLinux (not something you do in a couple of clicks 😄) and test your fix @pobrn, making sure it works with previous versions of GCC.

@yochananmarqos thanks for putting together the PKGBUILD! One little think it is missing is registering the systemd daemon on postinstall. Something similar to https://github.com/JoseExposito/touchegg/blob/master/installation/debian/postinst

Thanks again!

**Comment by yochananmarqos** [comment]
See the install file I my link above. 😉

**Comment by awesomehaircut** [comment]
Hello, I maintain the Aur repo and as much as I love to prothesise Arch Linux, I can take care of that for you. Thanks!

**Comment by parkerlreed** [comment]
@JoseExposito Post install enabling is up to the user. Usually a PKGBUILD will have a pkgname.install file that gets printed after installing letting the user know what needs to be done.

**Comment by parkerlreed** [comment]
@pobrn Where does that fix need to be placed?

**Comment by yochananmarqos** [comment]
I haven't tested it yet, but the `touchegg-git` AUR package [places](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=touchegg-git#n28) it in `/src/utils/`.

**Comment by JoseExposito** [comment]
Hi all,

The compilation on Arch Linux should be fixed now. I also tested the fix on openSUSE as issues where reported as well with GCC 10.

Can you confirm that you can build it @yochananmarqos @awesomehaircut ? Once you confirm that the issue is solved I'll create a new release with the fix :+1: 

Jose

**Comment by pobrn** [comment]
I can confirm that it compiles.

**Comment by parkerlreed** [comment]
Working here as well

**Comment by yochananmarqos** [comment]
Yes, it builds now.

**Comment by JoseExposito** [comment]
Thank you very much for the quick feedback and your support guys!

Here is the release: https://github.com/JoseExposito/touchegg/releases/tag/2.0.1

**Comment by NICHOLAS85** [comment]
I can confirm this also fixed compilation on a Debian testing system.

**Comment by yochananmarqos** [comment]
@awesomehaircut I updated my [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/tree/master/touchegg) for 2.0.1.
