### ISSUE TITLE
touchegg crashes on some gestures

### ISSUE THREAD

**Issue by magnus-gross** [JoseExposito/touchegg#341]
I use the default configuration. Some gestures work fine (e.g. the minimize gesture, by swiping down with 3 fingers). Some others always make touchegg crash, like e.g. `MAXIMIZE_RESTORE_WINDOW`, which is configured on swiping up with 3 fingers.

Here is the crash log:
```
Successfully connected to Touchégg daemon
Gesture begin detected
        Gesture information:
                Fingers: 3
                Type: SWIPE
                Direction: UP
        Gesture performed on app: konsole
        Action configured for this gesture
        Starting action
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0x0
  Serial number of failed request:  46
  Current serial number in output stream:  46
```

I have to mention that I use a laptop with an external monitor attached, while having the internal laptop display disabled, which might be a very weird setup.

I use Arch Linux with KDE(X11) 5.19.5 and Xorg 1.20.9.

Any idea what might be going wrong?
If you need any other output, feel free to contact me.

Edit: I just tested with only the internal laptop display on and the external monitor disconnected, and now everything is working.
I don't really need the gestures so much, when I have the external monitor connected, but if this is an easy fix, that would still be cool. :)

**Comment by JoseExposito** [comment]
Hi!

First of all, thanks for the bug report!

You are right, it crashes because it is not able to figure out the screen the animation should be displayed on.

It is a bit of an edge case, but I'll try to fix it.
Could you attach the output of the `xrandr` command when the external monitor is connected and the laptop screen is disconnected please?

**Comment by magnus-gross** [comment]
Sure,
here you go:

```bash
xrandr
Screen 0: minimum 8 x 8, current 3840 x 2160, maximum 32767 x 32767
eDP1 connected (normal left inverted right x axis y axis)
    1920x1080     60.02 +  59.93
    1680x1050     59.88
    1400x1050     59.98
    1600x900      60.00    59.95    59.82
    1280x1024     60.02
    1400x900      59.96    59.88
    1280x960      60.00
    1368x768      60.00    59.88    59.85
    1280x800      59.81    59.91
    1280x720      59.86    60.00    59.74
    1024x768      60.00
    1024x576      60.00    59.90    59.82
    960x540       60.00    59.63    59.82
    800x600       60.32    56.25
    864x486       60.00    59.92    59.57
    640x480       59.94
    720x405       59.51    60.00    58.99
    640x360       59.84    59.32    60.00
HDMI1 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 700mm x 390mm
    3840x2160     30.00*   25.00    24.00    29.97    23.98
    2560x1600     59.94
    2560x1440     59.95
    1920x1080     60.00    60.00    50.00    59.94    30.00    25.00    24.00    29.97    23.98
    1920x1080i    60.00    50.00    59.94
    1680x1050     59.88
    1600x900      60.00
    1280x1024     75.02    60.02
    1280x800      59.91
    1152x864      75.00
    1280x720      60.00    50.00    59.94
    1024x768      75.03    60.00
    832x624       74.55
    800x600       75.00    60.32
    720x576       50.00
    720x480       60.00    59.94
    640x480       75.00    60.00    59.94
    720x400       70.08
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```


Perhaps there is a way to know which screen a window belongs to? Then 
you could display the animation on the screen of the window that the 
gesture was started on.

Let me know if you need anything else.
