### ISSUE TITLE
Tile desktop: restore

### ISSUE THREAD

**Issue by jbouter** [JoseExposito/touchegg#345]
# Observation

If I tile a window to the right side of the screen (for example) using super + L on my keyboard, and press super+L again after, it restores to the original window. If I use the gesture, and use the gesture again, it doesn't restore. I can only ping it back and forth between left and right on the desktop. To restore, I have to manually re-adjust the window again.

# Expected result

To either "restore" the window when I use the gesture to tile to the other side of where I just tiled, or to use the same tile gesture to restore the window.

**Comment by JoseExposito** [comment]
Thanks for the bug report. Yes, this definitely needs to be improved :+1:

**Comment by JoseExposito** [comment]
Check @sk22 possible workaround: https://github.com/JoseExposito/touchegg/issues/345

**Comment by JoseExposito** [comment]
https://github.com/JoseExposito/touchegg/issues/505 can be used to use a keyboard shortcut or run a command while displaying the animation.

It's suboptimal... but I couldn't find a better solution for this issue. It doesn't seem like the window manager supports this :S
