### ISSUE TITLE
Swipe direction: natural scrolling

### ISSUE THREAD

**Issue by jbouter** [JoseExposito/touchegg#346]
# Observed behavior

When using the default four finger swipe up and down to move to another desktop, I would assume things to be *just* the other way around as I am using natural scrolling.

# Expected behavior

Four finger swipe "up" == Move to desktop below
Four finger swipe "down" == Move to desktop above

Pretty much like how you'd expect to scroll on a smartphone.

Since natural scrolling is a libinput feature, perhaps it can be read in order to determine the scroll direction.

**Comment by JoseExposito** [comment]
Hi! Thanks for your issue report.

I don't think this is a bug. I think the configuration file describes what is going on and it is up to you to configure the action to use natural scrolling or not.

**Comment by JoseExposito** [comment]
Hi @jbouter 

Thanks again for your bug report. I'm finally going to add some option to fix this, check this issue: https://github.com/JoseExposito/touchegg/issues/382

**Comment by jbouter** [comment]
Brilliant! Thanks :-)
