### ISSUE TITLE
(Feature request) add appimage package

### ISSUE THREAD

**Issue by Lvaskz** [JoseExposito/touchegg#348]
Hi, it would be great if this software could be packaged as appimage.

**Comment by JoseExposito** [comment]
Hola @Lvaskz ,

Thanks you very much for your request.

In my opinion, AppImage is not a good format for a command line tool that requires to register a systems service like this one.
The installation process would be more complex than just using the native system package (deb, rpm, AUR on Arch etc) plus I'd have to maintain another package format.

Jose
