### ISSUE TITLE
repeatKeys and reverseModifiers option for SEND_KEYS

### ISSUE THREAD

**Issue by alvesvaren** [JoseExposito/touchegg#351]
I would like to be able to write gestures that can press different keys after the initial press. It would also be nice to be able to change what modifiers are used when reversing the gesture.

This could be useful if you for example would like to scroll through the windows in Alt+Tab, and then changing to Alt+Shift+Tab when reversing the gesture, or pressing Alt+Tab and then use the arrow keys when repeating and reversing

**Comment by JoseExposito** [comment]
I think this configuration should do it:

```xml
<gesture type="SWIPE" fingers="3" direction="LEFT">
  <action type="SEND_KEYS">
    <repeat>true</repeat>
    <modifiers>Alt_L</modifiers>
    <keys>Shift_L+Tab</keys>
    <decreaseKeys>Tab</decreaseKeys>
  </action>
</gesture>

<gesture type="SWIPE" fingers="3" direction="RIGHT">
  <action type="SEND_KEYS">
    <repeat>true</repeat>
    <modifiers>Alt_L</modifiers>
    <keys>Tab</keys>
    <decreaseKeys>Shift_L+Tab</decreaseKeys>
  </action>
</gesture>
```

I'm closing the issue as I think more options are not required. In case you find some limitation feel free to reopen it.

**Comment by alvesvaren** [comment]
Oh, I guess that was a bad example. When using Ctrl+Tab/Ctrl+Shift+Tab in for example firefox, just pressing Ctrl+Shift+Tab directly does not activate the UI.

**Comment by JoseExposito** [comment]
That's not a problem with Touchégg, it is how Firefox works. Control+Shift+Tab (on the keyboard) doesn't navigate to the previous tab. However, you can use this shorcuts:
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly?redirectslug=Keyboard+shortcuts&redirectlocale=en-US#w_windows-tabs

I believe this is what you need:

```xml
  <application name="Firefox">
    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>Page_Up</keys>
        <decreaseKeys>Page_Down</decreaseKeys>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="3" direction="RIGHT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>Page_Down</keys>
        <decreaseKeys>Page_Up</decreaseKeys>
      </action>
    </gesture>
  </application>
```
