### ISSUE TITLE
Click-hold, multi-click, rotate options

### ISSUE THREAD

**Issue by Surgikill** [JoseExposito/touchegg#353]
Hi all,

Just discovered fushuma, and then stumbled upon this. Touchegg definitely seems more powerful, but I'm wondering if there is any planned integration for some multi-click/rotate/click-hold functionality. I can get some of that in fushuma, but am still looking for the multi-click and click-hold functionality.

Thanks.

**Comment by JoseExposito** [comment]
At the moment there are other priorities on my road map, like touchscreen support and a GUI to configure gestures. Maybe once that is done and if this ends up being a requested feature, I could look into this.

So, not in the near future, sorry :(
