### ISSUE TITLE
Touchegg only recognize my trackpad, but not my touchscreen

### ISSUE THREAD

**Issue by DarkFighterLuke** [JoseExposito/touchegg#355]
I have a computer with an ELAN touchscreen monitor, but looking at the logs in systemd I read that in the list of compatible devices, touchegg lists only my SynPS/2 Synaptics TouchPad.

Here is the output of `xinput --list` about pointer devices:
```
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ ELAN0732:00 04F3:2727                     id=15   [slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad                id=19   [slave  pointer  (2)]
```
And here is what systemd shows:
![immagine](https://user-images.githubusercontent.com/31162436/95658923-27d30f80-0b1e-11eb-9c26-2787180da382.png)

Obviously Touchegg doesn't work because it recognizes the wrong device onto apply its rules.
How can I solve?

**Comment by JoseExposito** [comment]
Hi!

Thank you very much for your report.

I'm working on touchscreen support. Progress will be notified in this issue: https://github.com/JoseExposito/touchegg/issues/336

Jose
