### ISSUE TITLE
<gesture type="SWIPE" fingers="2" direction="DOWN"> has no effect

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [JoseExposito/touchegg#357]
Actually, at one point, it seemed to have this effect:

```
Your configuration file changed, reloading your settings
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error parsing configuration file
```

`<gesture type="SWIPE" fingers="3" direction="DOWN">` works.

Touchégg v2.0.0
Linux Mint 20 x64 Cinnamon
Kernel 5.8.12-050812-generic
```
$ apt list libinput*
Listing... Done
libinput-bin/focal,now 1.15.5-1 amd64 [installed]
libinput-bin/focal 1.15.5-1 i386
libinput-dev/focal 1.15.5-1 amd64
libinput-dev/focal 1.15.5-1 i386
libinput-pad-dev/focal 1.0.3-4 amd64
libinput-pad-xtest/focal 1.0.3-4 amd64
libinput-pad1/focal 1.0.3-4 amd64
libinput-tools/focal,now 1.15.5-1 amd64 [installed]
libinput-tools/focal 1.15.5-1 i386
libinput10/focal,now 1.15.5-1 amd64 [installed]
libinput10/focal 1.15.5-1 i386
libinputsynth-0.13-0/focal 0.13.2-2 amd64
libinputsynth-dev/focal 0.13.2-2 amd64
```

**Comment by JoseExposito** [comment]
Hi!

Thanks for you bug report.

SWIPE is mean to be used with 3 or more fingers: https://github.com/JoseExposito/touchegg#swipe . Swipes with 2 fingers are used by the system to scroll and are not mean to be configured.

About the crash, it is not caused by your configuration, it was a bug (https://github.com/JoseExposito/touchegg/issues/350) but I already solved it.

Jose

**Comment by LinuxOnTheDesktop** [comment]
Right.

Should not the program report a configuration error when it encounters an attempt to configure a two-finger swipe?

**Comment by JoseExposito** [comment]
Yes, you are right, a warning could be convenient. However, I prefer to spend that time building a GUI to configure the gestures that only allows to select valid settings, hopefully it will be ready soon.

Thank you very much for your report!!

**Comment by LinuxOnTheDesktop** [comment]
I look forward to the GUI. In the meantime, please at least put something about this matter in the README. Otherwise others will waste time as I did.

**Comment by JoseExposito** [comment]
Cool. It was already there:
https://github.com/JoseExposito/touchegg#swipe

**Comment by LinuxOnTheDesktop** [comment]
Right, but it is not emphatic or even especially clear. The relevant text is:

> From libinput documentation: Swipe gestures are executed when three or more fingers are moved synchronously in the same direction.

The reader may not realise that what goes for libinput goes for your program. Even if she does, the text hardly stresses that three fingers is the unalterable minimum. Why not add the following to your page? (Note: I'd submit this as a pull request but for various reasons that is hard for me to do.) 'Note that _three_ is the minimum number of fingers that touchégg allows for swipe gestures. (At present, any line in the configuration file that specifies fewer than three fingers for a swipe will be ignored silently.'

**Comment by JoseExposito** [comment]
Thanks for your suggestion @LinuxOnTheDesktop , I added your clarification note to the README.md file. Hopefully, it'll be more clear to other users.
