### ISSUE TITLE
Crash on any gesture

### ISSUE THREAD

**Issue by Brin-o** [JoseExposito/touchegg#358]
Hi!

After installing Touchegg 2.0.0 (no binaries for 2.0.1) and running it I always run into this issue. I'm running Pop OS 20.04 on Intel i7-8550u.

If there is any other info I can provide to help you out, please let me know.

Thanks for spending the time on developing this!

```
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: RIGHT
	Gesture performed on app: Gnome-terminal
	Action configured for this gesture
	Starting action
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0x0
  Serial number of failed request:  40
  Current serial number in output stream:  40
```

**Comment by JoseExposito** [comment]
Hi! 

First of all, thanks for the bug report.

It looks like it is a problem with your screen configuration. Do you have multiple screens connected? If so, are any of them (or your laptop's screen) switched off?

It could be already solved here https://github.com/JoseExposito/touchegg/issues/341 . If you could compile and test the latest code it'd be very useful.

Jose

**Comment by Brin-o** [comment]
Hi Jose!

I  just wanna let you know, this was happening with 2 screens both of them having a different resolution.

I was on the road for the past 2 days and during this time touchegg worked perfectly. I won't be near the monitor I used before for a while so unfortunately I can't really test it with the exact same set up.

**Comment by JoseExposito** [comment]
Ok, no problem. I think it should be already fixed by the bug I mentioned.
I'm going to close the issue, if you find problems in the future with the latest code just let me know.
