### ISSUE TITLE
Gentoo ebuild for touchegg.

### ISSUE THREAD

**Issue by undrwater** [JoseExposito/touchegg#362]
This ebuild will install either version 2.0.1 (currently), or if you change the name to ```touchegg-9999.ebuild``` it will build from git.

Remove the .txt.
[touchegg-2.0.1.ebuild.txt](https://github.com/JoseExposito/touchegg/files/5403818/touchegg-2.0.1.ebuild.txt)

**Comment by JoseExposito** [comment]
Hi!

Thank you very much for the ebuild.

I'm not a Gentoo user (actually, I have never used Gentoo). Is there a repo where you can upload it? Something like AUR in Arch Linux. I'm not sure what is the best way of distributing this.

After a quick look, I think the ebuild is missing a post-install step to enable the systemd daemon. I'm not sure it is possible to do something like https://github.com/JoseExposito/touchegg/blob/master/installation/debian/postinst

Jose

**Comment by undrwater** [comment]
You are welcome. I've added the ebuild to Genntoo bug tracker where application ebuilds not in tree can be placed.  Interested users can search here as well. I'll try and keep up with the changes.

As for the init, the following line details the install of the daemon:
```
src_install(){
	cmake_src_install
        doinitd "${FILESDIR}"/${PN}
}
```
I forgot to attach the init script, which I have now.

[touchegg.txt](https://github.com/JoseExposito/touchegg/files/5409935/touchegg.txt)

**Comment by JoseExposito** [comment]
Cool, is this your request?
https://bugs.gentoo.org/541448

Let's wait until it gets added to the repo and then we will add it to the README install instructions. I don't think there is anything
else we can do, right?

Let me know when it is ready please.

**Comment by undrwater** [comment]
The initial request was made in 2015. Since it was still open, I used it. Gentoo won't add it to the repo until a maintainer has been identified (I think, not exactly sure what the policy is). I'll see if I can reach out to one of the layman (similar to AUR) repo owners to add it to their repo.

For now, users can search issues here or at gentoo bugs for the ebuild if desired. I'll respect whatever decision you make about putting the ebuild in the readme. I believe most gentoo users are savvy enough to find it on their own.

Thanks for your development of this! It's truly welcomed!

**Comment by JoseExposito** [comment]
Thank you very much! I also believe Gentoo users have no problem compiling C++ hehehehe I'll close the issue for the moment. Feel free to reopen it in case the situation changes. And thank you very much for the ebuild!!

**Comment by danielittlewood0** [comment]
@undrwater Thanks very much for making this ebuild! I had an issue using it: 
The ebuild refers to a patch "bindir.patch", which I can't find. I had to remove that line for the build to succeed. I also missed your comment about the init script, so am repeating it here for visibility.

To be clear, the following worked for me to set up touchegg in my local overlay:
```
cd /var/db/repos/danielittlewood
mkdir -p x11-misc/touchegg && cd x11-misc/touchegg
wget -O touchegg-9999.ebuild
# remove PATCHES
vim touchegg-9999.ebuild
mkdir files && cd files
wget -O touchegg https://541448.bugs.gentoo.org/attachment.cgi?id=667562
cd ..
ebuild touchegg-9999.ebuild manifest
emerge --ask touchegg
rc-service touchegg start
```

@JoseExposito I found the docs regarding compilation perfectly good for my needs. However, i got stuck because I don't use systemd (I use openrc instead). I believe undrwater's init script is agnostic about the details of the init system, and appears to work for openrc. It is possible that the average Gentoo user is aware of how to set up services, but I'm not :)

If you don't mind, I think it would be helpful to mention openrc near the systemd setup, but I would not mind if it was just a link to this discussion.

**Comment by undrwater** [comment]
@danielittlewood0
I'm glad you found the ebuild useful! I thought I had included the patch here, but I guess not. I'll do that. For me the Makefile installed the application to ```/usr/usr/bin```, did it not for you? You can check with ```equery files touchegg``` (assuming you have gentoolkit installed).

I have a new patch for the latest version of touchegg, and I'll upload here and at Gentoo bugs.

**Comment by undrwater** [comment]
patch to install in correct directories. Rename to bindir.patch (remove .txt)
[bindir.patch.txt](https://github.com/JoseExposito/touchegg/files/5506971/bindir.patch.txt)

**Comment by danielittlewood0** [comment]
Oh, that! Yes, I noticed the error but ignored it - I notice now that it was only working because I had previously compiled touchegg without the ebuild and that was on my path, so I have some cleaning up to do.

**Comment by undrwater** [comment]
new patch file attached.
[bindir.patch.txt](https://github.com/JoseExposito/touchegg/files/5654308/bindir.patch.txt)

@JoseExposito , can you check the patch file to see if it's a global change you can make in terms of paths? As mentioned earlier, your CMakelists.txt file installs binaries in /bin/bin at least on Gentoo. The patch corrects this. 

Thanks!

**Comment by JoseExposito** [comment]
Thank for the patch @undrwater , yes, I just included your changes upstream:
https://github.com/JoseExposito/touchegg/commit/8daff917b1abd0e37d336615a37c99dc33da1979

I'm not sure why are you removing `/lib/systemd/system/touchegg.service` and `/etc/xdg/autostart/touchegg.desktop` but I guess you'll have to still remove those.

Let me know if this works for you :)

**Comment by undrwater** [comment]
Everything works as expected, thank you!
