### ISSUE TITLE
Consider Add Flatpak / Snap support

### ISSUE THREAD

**Issue by andirsun** [JoseExposito/touchegg#363]
Hi Jose, I not a expert developer for apps in linux but I want to know if its possible to avoid distribute multiple version of your amazing app in tons of linux version like #362 .
Its possible make this kind of packaging for touchegg ?

**Comment by JoseExposito** [comment]
Actually, I don't know if it is possible.
Touchégg runs in 2 different processes, one of them is a systemd service. I'll to investigate if it is possible to run a flatpak/snap a systemd daemon.

**Comment by andirsun** [comment]
I hope will be implemented here #390
