### ISSUE TITLE
Animation not being shown when a new screen is connected

### ISSUE THREAD

**Issue by nmendozam** [JoseExposito/touchegg#364]
Hello,

### Observation 
When using two screens the animations of the gestures get rendered only in one screen when the pointer is in it. But, if the pointer is in another screen the gestures work, but the animation does not happen.

### Expected
To see the animation in the screen the pointer is when using multiple screens.

**Comment by JoseExposito** [comment]
Hi!

How many screens are you using? Also, what distro are you running? I have 2 monitors and I haven't experiment that issue testing on elementary OS, Ubuntu or Kubuntu.

Could copy and paste the output of this command please?

```
$ xrandr
```

The issue could be already fixed, so if you feel confortable compiling C++, it'll be helpful if you could test the latest code.

**Comment by nmendozam** [comment]
I'm using fedora 32 with two monitors in a laptop, the external screen (HDMI-1) is the one that show animations when connected.
 
The xrandr output is:
```
Screen 0: minimum 320 x 200, current 3840 x 1080, maximum 16384 x 16384
eDP-1 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 309mm x 174mm
   1920x1080     60.06*+  60.01    59.97    59.96    59.93  
   1680x1050     59.95    60.06    59.88  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.06    60.02  
   1440x900      60.06  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1280x800      59.99    60.06    59.97    59.81    59.91  
   1280x720      60.00    60.06    59.99    59.86    59.74  
   1024x768      60.06    60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.06    60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.06    60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
HDMI-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 480mm x 270mm
   1920x1080     60.00*+  50.00    59.94    59.93  
   1680x1050     59.95    59.88  
   1400x1050     74.76    59.98    59.95  
   1600x900      59.95    60.00    59.82  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      59.97  
   1368x768      59.88    59.85  
   1280x800      59.97    59.81    59.91  
   1152x864      75.00  
   1280x720      60.00    59.99    59.86    60.00    50.00    59.94    59.74  
   1024x768      60.04    75.03    70.07    60.00  
   960x720       75.00    60.00  
   928x696       75.00    60.05  
   896x672       75.05    60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   832x624       74.55  
   960x540       59.96    59.99    59.63    59.82  
   800x600       75.00    70.00    65.00    60.00    72.19    75.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   720x576       50.00  
   700x525       74.76    59.98  
   800x450       59.95    59.82  
   720x480       60.00    59.94  
   640x512       75.02    60.02  
   700x450       59.96    59.88  
   640x480       60.00    75.00    72.81    75.00    60.00    59.94  
   720x405       59.51    58.99  
   720x400       70.08  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   576x432       75.00  
   640x360       59.86    59.83    59.84    59.32  
   512x384       75.03    70.07    60.00  
   512x288       60.00    59.92  
   416x312       74.66  
   480x270       59.63    59.82  
   400x300       72.19    75.12    60.32    56.34  
   432x243       59.92    59.57  
   320x240       72.81    75.00    60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  

```

**Comment by JoseExposito** [comment]
Hi!

Sorry for the delay answering, it's being a busy week.

Your screen configuration seems to be fine.

Do you think you could test this with the latest master branch code? You just need to follow the instructions in the "Compilation" section here: https://github.com/JoseExposito/touchegg/blob/master/HACKING.md#compilation and after `make -j$(nproc)` run:

```bash
$ killall -9 touchegg
$ ./touchegg
```

This will end the currently running Touchégg and run the one you just compied.
I'd need to install Fedora on my PC to test this, and it could take me a while.

**Comment by nmendozam** [comment]
Hi, don't worry and thank you for your awesome work.

Ok, I will try that and report the results. Also, I've found out that this behavior only happens when I power on the computer without the second screen connected. But, when I power on the computer with it connected the animations work, even upon disconnection and reconnection of the external screen. (I hope this help you)

**Comment by nmendozam** [comment]
I tried the master branch and I have the same behavior.

When touchegg is stared while the external screen is disconnected; the animation only works in the external screen after connecting it. But, if touchegg is started at the time the second screen is connected the animation works in both screens.

Maybe this is the lack of a hot pug functionality, rather than a bug...

**Comment by JoseExposito** [comment]
Cool, this is a big then. Thanks for reporting it!
