### ISSUE TITLE
event processing lagging behind when external keyboard is attached

### ISSUE THREAD

**Issue by gricertg** [JoseExposito/touchegg#366]
When my USB keyboard is attached i get these error messages in the log of the daemon process:

```
libinput error: event16 - Das Keyboard Das Keyboard P13: client bug: event processing lagging behind by 34ms, your system is too slow
```
A similar message appears every few minutes. It looks like touchegg is trying to get input from my keyboard device. 

I'm happy to help if someone can tell me which information I should provide.

**Comment by JoseExposito** [comment]
Hi!

This is most likely not an issue with Touchégg (and probably not an issue at all). Let me explain it a little bit.

Touchégg get touch information from libinput. However, libinput handles all your input devices, including your keyboard, and it is libinput, and not Touchégg, the one printing that warning.

Let's try something, stop Touchégg:

```bash
$ killall -9 touchegg
```

Attach you USB keyboard  and run this command: (in Ubuntu you need to install the `libinput-tools` package)

```bash
$ sudo libinput debug-events
```

Is the same log being displayed there? If so, it could be a problem on libinput or with your keyboard's driver. However, if your keyboard works this is totally fine.

**Comment by gricertg** [comment]
Hi Jose!

Thank you very much for your reply (and for providing touchegg too, of course!)

You're assumptions are correct. I could have thought of it myself when seeing a `libinput error:` in the touchegg log. I was just a bit confused why log messages regarding other input devices appeared in the touchegg log. But I think (without checking it out any further, my C++ skills are too bad :sweat_smile: ) that touchegg receives all libinput events to check if any actions have to be applied? If it's no problem it's fine for me too (btw: the keyboard is working without any issues). 

I'll close this issue.

**Comment by JoseExposito** [comment]
Cool, thanks for double checking :)

Yes, you are right, in case you are curios about how it works, here is where it receives the input events and ignores everything except the gesture events:
https://github.com/JoseExposito/touchegg/blob/master/src/gesture-gatherer/libinput-gesture-gatherer.cpp#L100
