### ISSUE TITLE
Screen is black while gesturing (Plasma 5.20/Arch)

### ISSUE THREAD

**Issue by MatthiasSaihttam** [JoseExposito/touchegg#370]
This tool seems to be working great in terms of converting my movement into a percentage of a gesture, and displaying the animation. But for some reason it is also covering the entire screen with black as it does it.

![Screenshot_20201024_144818](https://user-images.githubusercontent.com/19734415/97091187-0a1aa580-1608-11eb-9938-ad2f42fc3100.png)

Touchégg 2.0.1, KDE Plasma 5.20.1

**Comment by JoseExposito** [comment]
Hi! That black area that you show is mean to be transparent. It looks like you don't have compositing enabled.
Are you using Kwin as your window manager? (It is the default one, so you probably are)

Try to enable composition: https://wiki.archlinux.org/index.php/KDE#Enable_transparency

**Comment by MatthiasSaihttam** [comment]
Thank you! That fixed it. (OpenGL compositing had apparently caused a crash it the past so it had been automatically disabled.)
