### ISSUE TITLE
Unable to start client as lock file was not properly cleaned up from previous session

### ISSUE THREAD

**Issue by m-roberts** [JoseExposito/touchegg#379]
Unfortunately I have no details about how I managed to do this. I was in a rush, so I had to delete the lock file to proceed with my work. However, I am logging this here as this may affect others. Derives from #369

**Comment by JoseExposito** [comment]
In theory this is not possible as the kernel cleans locks when a process gets killed.

However, this may be derived from: https://github.com/elementary/os-patches/issues/140
Touchégg (client) gets re-executed by the session manager the first time you kill it, so you actually need to kill it twice. I also thought it was a bug when I was testing this feature and took me a while to realise it.
However, that configuration should not be in the desktop file, so it should not happen any more.

Feel free to reopen the issue if you manage to reproduce it again.
