### ISSUE TITLE
Unable to install on Fedora 33

### ISSUE THREAD

**Issue by sarru1291** [JoseExposito/touchegg#380]
I encountered this error while installing v2.0.2 on F33. Is it because Fedora 33 has Btrfs file system by default?
![Screenshot from 2020-10-31 12-30-17](https://user-images.githubusercontent.com/22962336/97773381-42286800-1b75-11eb-8595-496e2beaa1e0.png)

**Comment by JoseExposito** [comment]
Hi @sarru1291 

No, it was a problem with the package it self. I just updated the RPM package:
https://github.com/JoseExposito/touchegg/releases/tag/2.0.2

This one should work :smile:
