### ISSUE TITLE
Crashes on a number of gestures when panels are set to auto-hide

### ISSUE THREAD

**Issue by Stormcheetah98** [JoseExposito/touchegg#381]
Running Manjaro/KDE over here. Touchegg v2.0.2

Only affects a small fraction of users, so not a big deal

If a session is started with panels(or taskbars) set to "auto-hide", gestures that provoke the change desktop and minimize/maximize actions (maybe others as well, but I haven't tested) result in a `segmentation fault (core dumped)` crash. Changing the panel settings to "always visible" seems to fix the issue for the rest of the session, even if the change is reverted afterwards and touchegg is restarted. 

I suspect that X11::getDesktopWorkarea() is having a hard time figuring out the info it needs, from running it using gdb.

Sorry if I messed anything up. This is my first ever issue submit on any repository. Though, thanks for all the work that went into this project!

**Comment by JoseExposito** [comment]
Thanks for the bug report, it is very detailed. I'll take a look into it as soon as possible

**Comment by mcking230** [comment]
Same thing here with latte-dock on opensuse tumbleweed
@Stormcheetah98 thanks for that hint.

**Comment by JoseExposito** [comment]
Fixed, thanks again for the bug report!

**Comment by Stormcheetah98** [comment]
Thanks for fixing this!
