### ISSUE TITLE
Swipe directions to follow natural scrolling

### ISSUE THREAD

**Issue by cassidyjames** [JoseExposito/touchegg#382]
elementary OS ships with "Natural Scrolling" on by default for touchpads, so e.g. swiping three fingers left should go to the next desktop. However, if someone turns off natural scrolling, that will feel backwards (see: https://github.com/elementary/os-patches/pull/137#issuecomment-724301661)

That said, I don't think it always makes sense for all gestures to be inverted when natural scrolling is used. Would it be possible to introduce new swipe directions that were aware of and followed the natural scrolling setting? E.g. something like `direction="NATURAL_RIGHT"` could mean `RIGHT` with natural scrolling off, and `LEFT` with natural scrolling on. Exact naming and logic tbd.

**Comment by JoseExposito** [comment]
Hi!

Yes, this is something required as with this integration users will not have even open their config file... And honestly, I'm so glad for the users :)

I think we can solve this issue and the accent color one https://github.com/JoseExposito/touchegg/issues/360 in a similar way. What do you think about an `auto` option? Both for colors and natural direction.

I think it only makes sense in following actions:

 - TILE_WINDOW
 - CHANGE_DESKTOP

The configuration will look similar to:

```
<touchégg>
  <settings>
    <property name="animation_delay">150</property>
    <property name="action_execute_threshold">20</property>
    <property name="color">auto</property>
    <property name="borderColor">auto</property>
  </settings>
  <application name="All">
    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="TILE_WINDOW">
        <direction>auto</direction>
        <animate>true</animate>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="3" direction="RIGHT">
      <action type="TILE_WINDOW">
        <direction>auto</direction>
        <animate>true</animate>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="4" direction="LEFT">
      <action type="CHANGE_DESKTOP">
        <direction>auto</direction>
        <animate>true</animate>
        <animationPosition>auto</animationPosition>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="4" direction="RIGHT">
      <action type="CHANGE_DESKTOP">
        <direction>auto</direction>
        <animate>true</animate>
        <animationPosition>auto</animationPosition>
      </action>
    </gesture>
  </application>
</touchégg>
```

Speaking about tiling, this needs to be addressed as well https://github.com/JoseExposito/touchegg/issues/345 is there a command in Gala to tile windows? I can add a custom tile command so the window remembers its old size without loosing the 1:1 animation.

**Comment by cassidyjames** [comment]
@JoseExposito I don't think it actually makes sense for tiling. :smile: I think you would always want moving your fingers to the left side of the display to tile a window to the left, because you're controlling the window in that context; with "natural" scrolling, the idea is that **the thing you're controlling tracks with your fingers.** So move a window to the left by dragging fingers to the left. For the workspaces, you're "dragging" the existing workspace off to the left in order to switch to the one on the right, so this auto behavior makes more sense.

**Comment by cassidyjames** [comment]
@JoseExposito That said, for workspaces, I think the `<direction>auto</direction>` makes perfect sense. In the docs, I would just mention that it will follow your trackpad setting's scrolling direction.

Something interesting to note: on a touchscreen, I think that "auto" should always use the natural scrolling direction since you're interacting directly with the content, just like scrolling. And the natural scrolling preference applies to touchpads, not touchscreens, anyway.

**Comment by JoseExposito** [comment]
You are absolutely right, that's a much better UX. I'm going to update my previous comment to reflect this.

**Comment by rbreaves** [comment]
Does not seem like this works for me on version 2.0.12. I try to add the auto option and no change of behavior occurs when restarting the service. Also I would prefer it to not be sole tied to the scroll direction of the touchpad as I prefer to have normal scrolling (not natural) while retaining a natural swipe left to right.

**Comment by JoseExposito** [comment]
Hi @rbreaves 

Please, open a new bug report with the required information/logs so we can investigate the cause.

Thanks!
