### ISSUE TITLE
Segfault on 3-finger-gesture in Firefox on default config (i3 window manager)

### ISSUE THREAD

**Issue by nabijaczleweli** [JoseExposito/touchegg#383]
When built and run with default config, current HEAD (df47bff2e77e5f42321d860d9e20da78707370e3) segfaults when doing a triple-finger-swipe in Firefox under i3.

LLDB log:
```
nabijaczleweli@babtop:~/src/touchegg/build$ lldb-11 touchegg
(lldb) target create "touchegg"
Current executable set to '/home/nabijaczleweli/src/touchegg/build/touchegg' (x86_64).
(lldb) run
Process 17538 launched: '/home/nabijaczleweli/src/touchegg/build/touchegg' (x86_64)
Touchégg v2.0.2.
Usage: touchegg [--daemon [threshold animation_finish_threshold]] [--client]

Multi-touch gesture recognizer.
Touchégg is an app that runs in the background and transform the gestures you make on your touchpad into visible actions in your desktop.
For more information please visit:
https://github.com/JoseExposito/touchegg

Option          Meaning
 --daemon       Run Touchégg in daemon mode. This mode starts a service that gathers gestures but executes no actions
 --client       Connect to an existing Touchégg daemon and execute actions in your desktop
Without arguments Touchégg starts in client mode

Starting Touchégg in client mode
Parsing you configuration file...
Configuration parsed successfully
Connecting to Touchégg daemon...
Successfully connected to Touchégg daemon
Gesture begin detected
        Gesture information:
                Fingers: 3
                Type: SWIPE
                Direction: RIGHT
        Gesture performed on app: Firefox Developer Edition
        Action configured for this gesture
        Starting action
Process 17538 stopped
* thread #1, name = 'touchegg', stop reason = signal SIGSEGV: invalid address (fault address: 0x20)
    frame #0: 0x00000000004e31c5 touchegg`X11::getDesktopWorkarea() const + 917
touchegg`X11::getDesktopWorkarea:
->  0x4e31c5 <+917>: movq   (%rax), %rax
    0x4e31c8 <+920>: movl   %eax, -0x10(%rbp)
    0x4e31cb <+923>: leaq   -0x80(%rbp), %rdi
    0x4e31cf <+927>: callq  0x4e4760                  ; std::vector<unsigned long, std::allocator<unsigned long> >::operator[](unsigned long)
(lldb)
```

Working diff:
```diff
diff --git a/src/window-system/x11.cpp b/src/window-system/x11.cpp
index d84e032..6bf1b52 100644
--- a/src/window-system/x11.cpp
+++ b/src/window-system/x11.cpp
@@ -420,6 +420,11 @@ void X11::sendKeys(const std::vector<std::string> &keycodes,
   XFlush(this->display);
 }
 
+       #include <sys/types.h>
+       #include <sys/stat.h>
+       #include <fcntl.h>
+       #include <unistd.h>
+
 Rectangle X11::getDesktopWorkarea() const {
   // When multiple physical screens are connected, the root window's size is the
   // sum of all of them. Use Xrandr to get the screen size of the physical
@@ -471,6 +476,10 @@ Rectangle X11::getDesktopWorkarea() const {
   std::vector<unsigned long> workareas = this->getWindowProperty<unsigned long>(
       rootWindow, "_NET_WORKAREA", XA_CARDINAL);
 
+  auto l = currenDesktop.size();
+  write(creat("/tmp/owo", 0777), &l, sizeof(l));
+  l = workareas.size();
+  write(creat("/tmp/awa", 0777), &l, sizeof(l));
   Rectangle workarea;
   workarea.x = workareas[0 + (currenDesktop[0] * 4)];
   workarea.y = workareas[1 + (currenDesktop[0] * 4)];
```

`/tmp/owo` is 1, which matches the expectations of the code below it, but `/tmp/awa` is 0, which, well

**Comment by JoseExposito** [comment]
Hi!

It looks like i3 doesn't support the `_NET_WORKAREA` hint:
https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm46165187160080

> This property MUST be set by the Window Manager upon calculating the work area for each desktop. Contains a geometry for each desktop. These geometries are specified relative to the viewport on each desktop and specify an area that is completely contained within the viewport. Work area SHOULD be used by desktop applications to place desktop icons appropriately.

There is not much I can do here. I have never used i3, but, does it make sense to maximize a window?

**Comment by nabijaczleweli** [comment]
It seems that i3 [actively removes](https://github.com/i3/i3/blob/f233245a6c3505662274b85c0071be250e87fe20/src/ewmh.c#L225) `_NET_WORKAREA` because it causes problems.

The closest you can get visually would be to full-screen it, I guess? But maximisation as such is not a thing I think.

Given all that, I mean, the default config clearly makes no sense semantically for my set-up; still, though, it's a segfault, and printing something along the lines of "The WM doesn't support _NET_WORKAREA" instead of crashing (and, in my case, requiring a reexec of i3 to get anything other than a black screen) would be nice.

**Comment by JoseExposito** [comment]
I guess you can always edit your configuration to use [SEND_KEYS](https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys) and handle windows with the gestures you like.

> it's a segfault, and printing something along the lines of "The WM doesn't support _NET_WORKAREA" instead of crashing (and, in my case, requiring a reexec of i3 to get anything other than a black screen) would be nice.

Yes of course, this is a bug and needs to be fixed. I'll spend some time on it ASAP :wink:

**Comment by JoseExposito** [comment]
Hi @nabijaczleweli 

The issue with `_NET_WORKAREA` should be fixed in the current master. Could you confirm that it works on i3 WM, please?

Thanks

**Comment by nabijaczleweli** [comment]
Indeed, it doesn't crash. Thanks!
