### ISSUE TITLE
Improve Debian package

### ISSUE THREAD

**Issue by JoseExposito** [JoseExposito/touchegg#384]
The package available in the Ubuntu official repo is outdated and it doesn't even work on the latest Ubuntu versions.

A better Debian package is required. 

Merge in master the original Ubuntu package:
https://launchpad.net/touchegg

And add the changes made by @danrabbit for elementary OS:
https://github.com/elementary/os-patches/tree/touchegg-focal-patched

**Comment by m-roberts** [comment]
pi-top has a decent amount of experience with this - we are happy to help however we can!

**Comment by JoseExposito** [comment]
Thanks @m-roberts , I just added the debian folder mixing the changes made by the Ubuntu mantainers and @danrabbit and added some improvements to how systemd was managed. You can check the changes here:
https://github.com/JoseExposito/touchegg/commit/0a4b6f36436b7fa43268deee246c868e7e453a3b
