### ISSUE TITLE
Finding strings for actions

### ISSUE THREAD

**Issue by creativiii** [JoseExposito/touchegg#386]
Touchegg is absolutely fantastic, best gesture experience I've used on Linux. However I'm kind of unclear on some of its usage.

The config files sometimes use "actions" to bind a gesture to a specific functionality, like:
```
  <action type="MAXIMIZE_RESTORE_WINDOW">
```

Where are these defined? Are these OS-level actions defined by my distro? Or are they defined by touchegg?

I'm trying to bind a shortcut that is assigned to fn+f11, but since I can't use the `fn` key my only option is to find what the shortcut is called at OS level.

**Comment by JoseExposito** [comment]
Actions are defined by Touchégg. You can find the available actions with examples and GIFs here: https://github.com/JoseExposito/touchegg#available-actions

What action are you trying to bind to a gesture? Maybe there is a command you can use...

**Comment by creativiii** [comment]
> Actions are defined by Touchégg. You can find the available actions with examples and GIFs here: https://github.com/JoseExposito/touchegg#available-actions
> 
> What action are you trying to bind to a gesture? Maybe there is a command you can use...

Ah, I assumed those were just some of the actions!

I'm trying to bind an ElementaryOS shortcut that fullscreens the selected window and pins it to a new workspace.

On my laptop this is activated by pressing fn+F11, but as you probably know there's no way to emulate pressing the "Function" key, which means I have no idea how to connect this shortcut to a gesture.

Unsure what command it could be connected to, I couldn't find much by googling!

**Comment by JoseExposito** [comment]
Cool, this is the action you are looking for: https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys

I'm on elementary OS as well and this is doing the job:

```
    <gesture type="SWIPE" fingers="4" direction="DOWN">
      <action type="SEND_KEYS">
        <repeat>false</repeat>
        <modifiers></modifiers>
        <keys>F11</keys>
        <on>begin</on>
      </action>
    </gesture>
```

Just change the gesture type, fingers or direction so it matches your expectations :+1:
