### ISSUE TITLE
Use GNUInstallDirs with CMake

### ISSUE THREAD

**Issue by tintou** [JoseExposito/touchegg#387]
### Is your feature request related to a problem? Please describe

The installation directories are not the same on every distribution, some will complain at some point

### Describe the solution you'd like

Use [GNUInstallDirs](https://cmake.org/cmake/help/v3.4/module/GNUInstallDirs.html), it is quite simple to use and included with CMake

### Describe alternatives you've considered

Leaving it up to the packager

### Additional context

N/A

**Comment by JoseExposito** [comment]
Thanks! I'll implement it. I'll require some changes in code as well :+1:
