### ISSUE TITLE
Add documentation on supported devices and drivers

### ISSUE THREAD

**Issue by matthijskooijman** [JoseExposito/touchegg#391]
### Is your feature request related to a problem? Please describe

I'm trying to get more configurable gestures on my Wacom touch tablet, and touchegg has been recommended as a way to achieve this (by disabling in-driver gesture support for `wacom_drv` using `xsetwacom` and then running touchegg), but no gestures seem to be recognized when I just run "touchegg".

### Describe the solution you'd like

Currently, there is no documentation on what kind of hardware is supported by touchegg and how it works. Such documentation would be helpful in general to asses if touchegg is useful for a particular usecase, and in my case could help figuring out what's wrong in my setup.

From reading up a bit on gesture/multitouch support, it seems that a rather new solution to multitouch in X is "libinput", which handles most input devices under X now. The README links to libinput docs, so I suppose that libinput is somehow used, but how exactly? Is this through the Xorg libinput driver? Is the Xorg `wacom_drv` driver maybe also supported? Or does touchegg talk to `/dev/input/eventxx` directly, bypassing Xorg? Is Xinput2 (which I've also seen mentioned) involved here?

### Describe alternatives you've considered

I've looked around the README and wiki, but found no such information.

**Comment by matthijskooijman** [comment]
I did a little digging in the source, and it seems that:
 - touchegg 1.x used GEIS for gathering gestures. It's not entirely clear where that takes its input from (it predates libinput, I think, but I couldn't find any active website or useful documentation fore GEIS, so I suspect it's unmaintained).
 - touchegg 2.x uses libinput and (AFAICS) connects directly to `/dev/input/event*`, bypassing all X handling of input AFAICS, so this would not be tied to the use of "libinput" in Xorg at all.

I also saw that touchegg 2.x has a daemon/client model, which could be useful to document.

**Comment by matthijskooijman** [comment]
I was previously using 1.x from Ubuntu, which did not seem to detect any gestures on my setup. Installing the latest 2.x version seems to work for me. However, it does seem that, 2.x only supports the PINCH and SWIPE gestures. TAP gestures (i.e. two-finger tap for right-click) or DRAG (scroll) gestures do not seem to be supported (unlike 1.x, which supported them and mapped them to mouse-clicks by default). I suspect that this is intentional, assuming that the libinput driver inside Xorg will already provide these "default" gestures, and touchegg intends to add "extra" gestures only? Or are those gestures yet to be implemented?

Note that for wacom tablets using the `wacom_drv` driver, for touchegg 1.x (I've read) need to disable in-Xorg-driver gesture support, which causes raw touch events to be emitted through XInput2, where I assume GEIS/touchegg reads them from (though this did not seem to work for me). This disables *all* gestures, including click, so it's good that touchegg emulates the click/scroll too. For touchegg 2.x, which bypasses X, the `wacom_drv` gesture setting can be left enabled, and probably should to make sure the default tap/scroll behavior stays working. This does mean that some gestures (probably just 2-finger pinch, the driver does not do swipe gestures) might be interpreted by both the wacom driver and touchegg, but also that it is impossible to use touchegg to reconfigure the basic tap/scroll gestures.

**Comment by JoseExposito** [comment]
Hi!

Great to know that v2 is working on your hardware.

You are right in your investigations, that's a pretty good explanation of how it works :smile: 

About you questions, the old `DRAG` is equivalent to the new `SWIPE`.
`TAP` is not supported by libinput (as a gesture) and you are right, the system is in charge of handling taps with 1, 2 and 3 fingers.
You explained it better than I could have done.

About the issue, I can not maintain documentation about supported hardware, it's a ton of work and libinput already do it. Closing it as it is out of the scope of the project.

**Comment by matthijskooijman** [comment]
Thanks for the extra clarifications.

> About the issue, I can not maintain documentation about supported hardware, it's a ton of work and libinput already do it. Closing it as it is out of the scope of the project.

I wasn't suggesting to add a list of supported hardware, which I agree is not feasible. But I was suggesting to add more docs about how touchegg works (things like I figured out above), to help new users figure out themselves whether their hardware is supported. For example, had I known at the start that 1.x and 2.x are completely different, I would have known to upgrade right away, or if I knew that touchegg uses libinput to talk to the `/dev/input/event*` devices directly, without using Xorg input devices at all, I knew to look at libinput for supported devices, ignoring the X input drivers, or had I known that touchegg does not do any scroll or tap events, I would have known I should make sure Xorg drivers keep doing that part, etc.

**Comment by JoseExposito** [comment]
I don't find this kind of information useful for the majority of users. However, I can add some extra information here, as thiis is intended for developers and/or advanced users:
https://github.com/JoseExposito/touchegg/blob/master/HACKING.md

Libinput is mentioned, but I'll try to add more details about what's going on under the hood.

**Comment by matthijskooijman** [comment]
> I don't find this kind of information useful for the majority of users. However, I can add some extra information here, as thiis is intended for developers and/or advanced users:

I disagree with you there, my previous examples of how things would have helped me likely apply to more users. Maybe these things about how touchegg works can be documented in less detail than I suggested, but some info that helps people figure out what it is that touchegg can do for them, and within what limitations, would seem useful. Hiding such info in a HACKING document (which I, maybe naively, haven't actually looked at because I wouldn't expect such info in there) is IMHO not the best approach.

Having said all that, I'm just sharing my POV and experience, I'll leave it to you to figure out if that warrants any changes and if so, which and where :-)

**Comment by sebadamus** [comment]
Just to say it works fine on Macbook Pro 8.2 2010 (RadeonGate one), I dont miss osX anymore! Thanks.

**Comment by JoseExposito** [comment]
Added basic information in FAQs
