### ISSUE TITLE
Configuring invalid keysym does not show error

### ISSUE THREAD

**Issue by matthijskooijman** [JoseExposito/touchegg#392]
### Describe the bug

Using an invalid keysym is silently ignored and sends a `NoSymbol` (keysym 0) instead of showing an error message. For example, using the following gesture:

```
    <gesture type="PINCH" fingers="3" direction="OUT">
      <action type="SEND_KEYS">
        <keys>SomeRandomValue</keys>
      </action>
    </gesture>
```

### Expected behaviour

I would expect an error to be shown on stdout/stderr, preferably on toucheg startup, or otherwise when the action is triggered.

### Actual behaviour

Touchegg sends a `NoSymbol` (keysym 0) instead of showing an error message, according to `xev`:

```
KeyPress event, serial 40, synthetic NO, window 0x5800001,
    root 0x124, subw 0x0, time 657301371, (156,80), root:(157,145),
    state 0x0, keycode 204 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x5800001,
    root 0x124, subw 0x0, time 657301372, (156,80), root:(157,145),
    state 0x0, keycode 204 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

### Your environment

 * Version of Touchégg: Touchégg v2.0.3.
 * Operating System: Ubuntu
 * Desktop Environment: Gnome

**Comment by JoseExposito** [comment]
Thanks a lot for your bug report @matthijskooijman, I'll look into this ASAP
