### ISSUE TITLE
Suggestion: Use XF86ZoomIn/Out in default config

### ISSUE THREAD

**Issue by matthijskooijman** [JoseExposito/touchegg#395]
### Describe the solution you'd like

Currently, the default config has some application-specific pinch-zoom mapping, using the application-specific CTRL+ and CTRL- keystrokes. However, X supports special zoom keys: `XF86ZoomIn` and `XF86ZoomOut`. These keys are more generally understood by applications, so could be more suitable for a default configuration.

There is one caveat, though: These keysyms are not mapped to keycodes by default (at least not on my Ubuntu Focal), so they cannot be used (see also #393 and #394). So actually implementing this suggestion would require lifting this limitation first, possibly by implementing an "automatically map unmapped keysyms" feature, as suggested in #394.

I've tested this by adding the mapping with `xmodmap -e 'keycode any=XF86ZoomOut' -e 'keycode any=XF86ZoomIn'` and using the following config:

```
    <gesture type="PINCH" fingers="3" direction="IN">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <keys>XF86ZoomOut</keys>
        <decreaseKeys>XF86ZoomIn</decreaseKeys>
      </action>
    </gesture>

    <gesture type="PINCH" fingers="3" direction="OUT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <keys>XF86ZoomIn</keys>
        <decreaseKeys>XF86ZoomOut</decreaseKeys>
      </action>
    </gesture>
```

This works as expected in at least Firefox.

**Comment by JoseExposito** [comment]
While it is great to have this option, adding this as the default will cause crashes and/or not work for many users.
I think that Control +/- is OK as an example and easier to understand. It is up to the user to configure more shortcuts if wanted.

**Comment by matthijskooijman** [comment]
> will cause crashes and/or not work for many users.

What crashes? The one reported in #393? Of course, a condition for implementing this suggestion, is to fix that issue first. As for not working, it seems to work in Firefox, but (just tested this) apparently not in Chrome, so it's not necessarily a more general approach, I guess...

Anyway, it was just a suggestion in case you weren't aware of this, I can totally understand keeping the example simpler :-)
