### ISSUE TITLE
root tag in default config contains non-ascii symbol

### ISSUE THREAD

**Issue by igorfraa** [JoseExposito/touchegg#397]
### Describe the bug
/usr/share/touchegg/touchegg.conf starts with <touchégg> tag which contains **e** with diacritics
Character: é U+00E9
Name: LATIN SMALL LETTER E WITH ACUTE

### Expected behaviour
Config file do not use extended symbols
### Your environment

 * Version of Touchégg: 2.0.3:
https://github.com/JoseExposito/touchegg/releases/download/2.0.3/touchegg_2.0.3_amd64.deb

**Comment by JoseExposito** [comment]
Hi! Thanks for the bug report. Is this causing any problems in you machine?

**Comment by igorfraa** [comment]
Hello Jose,

I do not think it causes big problems, but it once caused me to wipe screen hard until I realized it is a diacritics. 

Also, it got highlighted (likely wrong) in red by Kate when I switched to XML mode.

**Comment by JoseExposito** [comment]
If it is not causing problems, I'll leave as it is. That's been the opening tag since ~2011 and I don't to change and potentially break any third party tool relaying on that specific tag.

Thanks for the bug report anyway!!!
