### ISSUE TITLE
Executable not reloading when service is restarted

### ISSUE THREAD

**Issue by vaskark** [JoseExposito/touchegg#398]
First, truly eggcellent work.

A few questions ...

1) I noticed the binary isn't started/reloaded when the service is restarted. Is this normal?
2) Is Touchegg only meant for GNOME? What about just window managers like berry or bspwm?
3) Can we set up different config files for different environments? Some gestures that make sense in GNOME aren't much use in other places.

I'm on Ubuntu 20.10.
Thanks.

**Comment by JoseExposito** [comment]
Hi @vaskark 

> I noticed the binary isn't started/reloaded when the service is restarted. Is this normal?

What do you mean? If I run `touchegg` in the terminal and in another tab I restart the daemon with `sudo systemctl restart touchegg`, `touchegg` keeps running:

```
Connection with Touchégg daemon lost. Reconnecting in 5 seconds...
Successfully connected to Touchégg daemon
```

> Is Touchegg only meant for GNOME? What about just window managers like berry or bspwm?

No, Touchégg works in any window manager that is compatible with EWMH:
https://en.wikipedia.org/wiki/Extended_Window_Manager_Hints
Some window manager don't implement all of those hints, so some actions may not work.

> Can we set up different config files for different environments? Some gestures that make sense in GNOME aren't much use in other places.

If you have different users yes. If you use the same user to run different WMs then no, you'll have to manually replace your config file (or run a script on session login to do it for you).

**Comment by vaskark** [comment]
Hi Jose. Thanks so much for responding.
Sorry for the stupid question. I assumed the service would start the binary automatically, and it didn't. I've got scripts running for different environments now which reload the touchegg binary and a symlink that points to the appropriate config file. Seems to work okay.
Once again, many thanks.

**Comment by JoseExposito** [comment]
There's no such thing as a stupid question :) The service does not start the binary. In case you are curious, this desktop file starts it:
https://github.com/JoseExposito/touchegg/blob/master/installation/touchegg.desktop

Best wishes,
Jose
