### ISSUE TITLE
Arrow keys

### ISSUE THREAD

**Issue by reesericci** [JoseExposito/touchegg#402]
### Is your feature request related to a problem? Please describe

Use of arrow keys in keyboard shortcuts

### Describe the solution you'd like

The ability to use arrow keys in keyboard shortcuts,

**Comment by JoseExposito** [comment]
Hi!

You should be able to use them already. For example:

```xml
    <gesture type="SWIPE" fingers="4" direction="RIGHT">
      <action type="SEND_KEYS">
        <repeat>false</repeat>
        <modifiers>Super_L</modifiers>
        <keys>Right</keys>
        <on>begin</on>
      </action>
    </gesture>
```
