### ISSUE TITLE
Allow showing animation without executing action

### ISSUE THREAD

**Issue by sk22** [JoseExposito/touchegg#403]
### Is your feature request related to a problem? Please describe

Since touchégg apparently doesn't use the window manager's method of tiling to the left and right sides of the screen (in GNOME, left/right-tiled windows appear to have some different kind of fullscreen-like state, while touchégg keeps them in their restored state, or something like that), I thought I'd instead use `SEND_KEYS` to emulate `Super+Right/Left` instead. While this works, it obviously doesn't show me the animation any more.

### Describe the solution you'd like

I would like to be able to write something like this:

```xml
<gesture type="SWIPE" fingers="3" direction="RIGHT">
  <action type="TILE_WINDOW">
    <direction>right</direction>
    <animate>true</animate>
    <noAction>true</noAction> <!-- for example -->
  </action>
  <action type="SEND_KEYS">
    <repeat>false</repeat>
    <modifiers>Super_L</modifiers>
    <keys>Right</keys>
    <on>end</on>
  </action>
</gesture>
```

This should instruct touchégg to show the animation, but not to actually run the action. Or alternatively, maybe something like this:

```xml
<gesture type="SWIPE" fingers="3" direction="RIGHT">
  <animation type="TILE_WINDOW"> <!-- animation instead of action -->
    <direction>right</direction>
  </animation>
  <action type="SEND_KEYS">
    <repeat>false</repeat>
    <modifiers>Super_L</modifiers>
    <keys>Right</keys>
    <on>end</on>
  </action>
</gesture>
```

### Describe alternatives you've considered

There could be an option to have touchégg make right/left tiled windows use GNOME's "method" (like what is usually mapped to `Super+Left/Right`). The main difference is that on GNOME, windows tiled to the left/right edge can be restored, while with touchégg, they are already in a restored state.

Anyway, I think disabling actions while keeping animations could be beneficial in other occasions as well.

Thanks for this great piece of software!

**Comment by JoseExposito** [comment]
Hi!

Yes, the tile actions need some improvements: https://github.com/JoseExposito/touchegg/issues/345

I don't know if it is possible to make it behave like when you drag the window to the edge of the screen, but I'll try. I'm closing this issue as there is already a bug report for this. I'll post updates in the other one.

Thanks for suggesting this workaround!
