### ISSUE TITLE
Option to target active window instead of below mouse cursor

### ISSUE THREAD

**Issue by sk22** [JoseExposito/touchegg#404]
### Is your feature request related to a problem? Please describe

I'm not used to the gestures getting applied on the window below the mouse cursor's position, but rather on the active window. I first thought the gestures weren't working correctly, but I just didn't understand that the gestures are dependent on the cursor position. It's probably a matter of getting used to it, but I think I prefer my gestures applied on the active window.

### Describe the solution you'd like

There could be an option (global or per-gesture, or both) to specify the target window (`targetWindow`) to be either `"BELOW_CURSOR"` or `"ACTIVE"`

### Describe alternatives you've considered

Well, I'm considering just getting used to it.

**Comment by JoseExposito** [comment]
Hi!

I think that having to perform an extra click is a little bit slow and I wouldn't like to add an extra flag to the configuration file because it is already quiet complicated. So, I'm not going to implement this for the moment.

But anyways, thank you very much for the feature request!

**Comment by sk22** [comment]
On the other side, one could argue that you would need an extra swipe if you've accidentally swiped a window to the right, but wanted it on the left, etc. But okay, fair point!
