### ISSUE TITLE
Touchscreen 4-finger-swipe collides with and crashes GNOME Shell

### ISSUE THREAD

**Issue by sk22** [JoseExposito/touchegg#405]
### Describe the bug

I've got this (and the same for the opposite direction) config item, and it works fine with my touchpad. But even without Touchégg, GNOME supports switching the workspace using the touchscreen (and even animates it).
**Edit:** Apart from the integrated 4-finger-swipe gesture, GNOME also has 3-finger-pinch gestures (in and out) that opens the overview (like Super+S).

```xml
<gesture type="SWIPE" fingers="4" direction="UP">
  <action type="CHANGE_DESKTOP">
    <direction>auto</direction>
    <animate>true</animate>
    <animationPosition>auto</animationPosition>
  </action>
</gesture>
```

### Expected behaviour

Well, first of all, GNOME Shell shouldn't crash. Adding a setting to make this gesture only apply to the touchpad (and not the touchscreen) would therefore make sense.

### Actual behaviour

Since I have the four-finger swipe in my configuration, Touchégg interfers and crashes GNOME Shell when trying to change workspaces using the touchscreen.

### Your environment

 * Version of Touchégg: v2.0.4
 * Operating System: Fedora 33
 * Desktop Environment: GNOME 3.38.2 on X11

**Comment by JoseExposito** [comment]
Hi, thanks for your bug report!

Unfortunately, I don't think I can do much on my side, it seems like a bug in Mutter. You can always try to report it to the Gnome devs to see if they can help you or just map the action to another gesture.
