### ISSUE TITLE
Task Switcher gesture similar to Windows

### ISSUE THREAD

**Issue by siddhantladdha** [JoseExposito/touchegg#406]
### Is your feature request related to a problem? Please describe

Is there any plan for implementing support for task switcher? To be specific the system I am using is KDE.

### Describe the solution you'd like

The basic idea is similar to what is used in [windows](https://www.windowscentral.com/mastering-three-finger-gestures-windows-10). With a 3-finger left/right swipe, task switcher is launched and 3 fingered scrolling within the task switcher helps to switch between the tasks.

### Describe alternatives you've considered

Considered using KWin Scripts for launching "Walk Through Windows" using the gestures to run the command
`qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Walk Through Windows"`. However, this just switches to the next recent window.
Additionally, I have tried using a script as follows
```
xdotool keydown alt
xdotool key Tab
sleep 1
xdotool keyup alt
```
This is a lazy emulation which gives enough time to select, but again feels unnatural.

And thank you for writing this awesome software.

**Comment by JoseExposito** [comment]
Hi!

You can already emulate this with the SEND_KEYS action:

```xml
<gesture type="SWIPE" fingers="3" direction="LEFT">
  <action type="SEND_KEYS">
    <repeat>true</repeat>
    <modifiers>Alt_L</modifiers>
    <keys>Shift_L+Tab</keys>
    <decreaseKeys>Tab</decreaseKeys>
  </action>
</gesture>

<gesture type="SWIPE" fingers="3" direction="RIGHT">
  <action type="SEND_KEYS">
    <repeat>true</repeat>
    <modifiers>Alt_L</modifiers>
    <keys>Tab</keys>
    <decreaseKeys>Shift_L+Tab</decreaseKeys>
  </action>
</gesture>
```

I just added the example to the README as this is a frequently requested feature:
https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys
