### ISSUE TITLE
Add a "sensitivity" option

### ISSUE THREAD

**Issue by Sclafus** [JoseExposito/touchegg#410]
While testing this software out on my medium sized trackpad, i had to move my fingers way more than excepted to perform an action.
### Describe the solution you'd like
A sensitivity option, in the form of multiplier defined in the `touchegg.conf` file could be an easy and straight forward way to approach the problem. Distinguishing between a global sensitivity and a local (per gesture) sensitivity could be a nice touch.

**Comment by JoseExposito** [comment]
There is already a way to do this, check this section:
https://github.com/JoseExposito/touchegg#daemon-configuration

Just check your current values and modify them in `/lib/systemd/system/touchegg.service`.
Let me know if you find any problems
