### ISSUE TITLE
Gestures don't work after logout/login on Raspberry Pi [FYI, with workaround]

### ISSUE THREAD

**Issue by imabuddha** [JoseExposito/touchegg#411]
### Describe the bug

1. Install touchegg on Raspberry Pi. Follow directions in HACKING.md. ⇒ Gestures work fine.
2. Logout
3. Login ⇒ Gestures don't work. At this point if you reboot then login gestures work until you logout/login again.

### Expected behaviour

Gestures should work after every login, whether immediately after booting or not.

### Actual behaviour

As described above gestures don't work after logout/login. I dug into this & found that after logout/login the daemon is still running but the client is not running even though ` /etc/xdg/autostart/touchegg.desktop` is present. Very strange since it does run properly after reboot/login. Looking at the logs I saw msgs like this after the logout/login:

```
Dec 16 19:50:53 buddhaPi touchegg[398]: New client connected with ID: 17
Dec 16 19:50:57 buddhaPi touchegg[398]: Error sending message to client with ID 16. Client disconnected
```

I've seen similar behavior with shairport-sync after the latest Raspi OS update that added pulseaudio (ugh), so I applied the same fix (detailed [here](https://gist.github.com/imabuddha/85d90acd71c155f08949764cd2cbef68)) and it works! Basically I just created a script that kills touchegg (client) on logout.

### Your environment

 * Version of Touchégg: v2.0.4
 * Operating System: Raspberry Pi OS (Dec 2020 release, debian based), Linux 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
 * Desktop Environment: LXDE
 * Device: Apple Magic Trackpad 2 connected via USB (same behavior via BT)
 * Raspberry Pi 4, 8GB

### Note

I'm not sure whether any other systems are affected by this, probably not since the pi os is a bit "unique". I'm fine with my current workaround since I need it for shairport-sync, but I thought you might like to know about this & perhaps it might help other users in the future. 

Thanks for all your work on this project! 🙇

**Comment by imabuddha** [comment]
Probably unrelated, but do you think it's worth upgrading my libinput from v1.12.6 to the latest 1.16.900? 

The raspi repo's latest is v1.12.6 so I'd have to build & manually install in order to upgrade.

**Comment by JoseExposito** [comment]
Hi!

I'm glad you found a workaround to fix this, I'm sure someone else will use it :D 

After watching your logs, it is weird that no gesture is recognised:

```
New client connected with ID: 17 <-- New sessions client connected
Error sending message to client with ID 16. Client disconnected <-- Old session client disconnected
```

Is the process running after login/logout?

This seems like a Raspberry Pi OS issue... Just curious, does this happens if you generate a deb package and install it from deb?

> Probably unrelated, but do you think it's worth upgrading my libinput from v1.12.6 to the latest 1.16.900?

Honestly, I don't know if there are any improvements for Raspberry PI on that version, so up to you.


I'm closing the issue since you already fixed it

**Comment by imabuddha** [comment]
> 
> After watching your logs, it is weird that no gesture is recognised:
Since the neither the old nor the new were running no gestures get recognized.

> 
> Is the process running after login/logout?
> 
After logout/login without my scripts (as installed per instructions) only the daemon is running. My guess is that the new client starts then quits because it thinks the old one is still running. Maybe because it didn't disconnect properly on logout? If I had time to dig into your source that's where I'd start ⇒ how does the client detect when there's a client already running? Maybe the daemon does not know the old client is no longer running on logout?

> This seems like a Raspberry Pi OS issue... Just curious, does this happens if you generate a deb package and install it from deb?

I haven't tried that, so I don't know. Kinda busy at the moment so probably won't try it since it's working fine for me now. Perhaps some future person will? 😉

One other minor point is that I set all animations to false because I'm not running a compositor for video playback performance reasons. Hopefully Pi 5 will be significantly more powerful, esp. the gpu!

Good luck with your work on Elemental!

**Comment by JoseExposito** [comment]
> One other minor point is that I set all animations to false because I'm not running a compositor for video playback performance reasons

I test Touchégg on a Raspberry PI 4 regularly, as it is my only device with a touchscreen, and the  animation is quite smooth:
https://youtu.be/7gKONPKNZlc

But I don't know about how a compositor could impact on general performance.

Thanks for the workaround again!

**Comment by imabuddha** [comment]
> I test Touchégg on a Raspberry PI 4 regularly, as it is my only device with a touchscreen, and the animation is quite smooth:
> https://youtu.be/7gKONPKNZlc

Very interesting! I tried enabling the compositor, rebooting, but still got black screen during animations which is why I just disabled them. BTW, is that Raspberry Pi OS? It looks like it might be another distro or DE.

> But I don't know about how a compositor could impact on general performance.

It does affect youtube video playback performance. The Pi 4, at least with the current drivers, still struggles with hd video. For example, even with overclocking & adjusting Chromium settings (https://www.dedoimedo.com/computers/rpi4-ubuntu-mate-hw-video-acceleration.html) etc., playback of 1920x1080 30fps still drops frames occasionally. Higher framerates (50, 60) drop many frames. Enabling the compositor makes it noticeably worse.

Since the gesture animations work well with your Pi & the compositor there must me an issue on my side. My guess is you're using another distro. For now I'm staying with Raspberry Pi OS/LXDE, but might try Mate DE or elemental if it becomes officially supported on Pi.

Thanks for your feedback!

**Comment by imabuddha** [comment]
Followup: I manually started the compositor & was able to get the gesture animations working, yea! It seems that just enabling the compositor with raspi-config doesn't actually run it even after reboot! 

In any case I've disabled the animations & compositor after confirming that enabling the compositor makes video performance noticeably worse.
