### ISSUE TITLE
Application name in Application specific gestures configuration

### ISSUE THREAD

**Issue by siddhantladdha** [JoseExposito/touchegg#414]
### Describe the bug
The following is a modification of what is shown on the `README.md` for Application specific gestures.
```
<application name="Firefox">
  <gesture type="PINCH" fingers="2" direction="IN">
  ....
  ....
  ....
  </gesture>
</application>                               
```
### Expected behaviour

The pinch in gesture should zoom in within firefox.

### Actual behaviour

Nothing happens. The gesture is not recognized by application.

### Solution

Changing to `<application name="firefox">` works. Similar thing with `konsole` instead of `Konsole`. 
Fortunately `Google-chrome` works. 

### Possible Suggestion

Making it clear, how touchegg handles application names will clear few things. Possibly adding a linux command to README which gets the application name so that it can be added to `touchegg.conf` in correct manner, will help. Currently, the user has to keep touchegg client in another terminal ready and then perform the gestures, where the `Gesture Performed on: <appname>` is displayed.

### Your environment

 * Version of Touchégg: Touchégg v2.0.4.
 * Operating System: Arch Linux
 * Desktop Environment: KDE

**Comment by JoseExposito** [comment]
Good point, I forgot about documenting this :sweat_smile: 

I'll add some docs, meanwhile, this is the command you need:

```
$ xprop | grep WM_CLASS
```
