### ISSUE TITLE
Inconsistent behaviour of send_keys with application-specific settings

### ISSUE THREAD

**Issue by d86leader** [JoseExposito/touchegg#420]
### Describe the bug

If I have a different keys configured to be sent to different applications, and those applications are opened together, then it will select the keys for the application under cursor, but send them to the active application, even if they are not the same.
For example, I have this configuration:
```xml
  <application name="Firefox">
    <!-- Open new private window -->
    <gesture type="SWIPE" fingers="4" direction="UP">
      <action type="SEND_KEYS">
        <modifiers>Control_L+Shift_L</modifiers>
        <keys>P</keys> <!-- P for firefox -->
        <repeat>false</repeat>
        <on>end</on>
      </action>
    </gesture>
  </application>
  <application name="Chromium-browser">
    <!-- Open new private window -->
    <gesture type="SWIPE" fingers="4" direction="UP">
      <action type="SEND_KEYS">
        <modifiers>Control_L+Shift_L</modifiers>
        <keys>N</keys> <!-- N for chrome -->
        <repeat>false</repeat>
        <on>end</on>
      </action>
    </gesture>
  </application>
```
And i have both browsers open at the same time side by side. I click on firefox to give it focus, then I move my cursor over chrome, and swipe my four fingers up. The ctrl-shift-n keys get incorrectly sent to firefox, which triggers a wrong action.

### Expected behaviour

Either the keys should be selected for an active application, or the keys should be sent to an application under cursor (i prefer the second).

### Actual behaviour

Keys are selected for application under cursor, but are sent to the active application

### Your environment

 * Version of Touchégg: v2.0.4
 * Operating System: opensuse 15.1
 * Desktop Environment: KDE 5.12.8

**Comment by d86leader** [comment]
Alright, this one is caused by focus-stealing prevention in my kde. When focus-stealing prevention is set to none, the window under cursor is activated and shortut is sent to it; and when set to low (which is the next by severity), the window under cursor is not activated, but the shortcut is still sent.
Also, there's another bit of undesirable behaviour: when a window is activated, it's raised above other windows, which I don't necessarily want.

**Comment by JoseExposito** [comment]
Hi! Thanks for your bug report.

As far as I know, there is no way to send keys to a window that is not the active window, but I might be wrong.
That's why the first step in the send keys action is to raise up the window under the cursor. I'm afraid that's not something I can avoid :disappointed:

**Comment by d86leader** [comment]
First, I think you're wrong, because I can send input to a window from a kwin script without activating the window.
Second, in kde it must be possible to activate a window without raising it, because well it's the default behaviour when clicking inside a window with the right mouse button.
Well, I'm already looking into kde docs to see how it's done, so if you wontfix it, I will (=

**Comment by JoseExposito** [comment]
Cool. It might be a Kwin specified thing though. But maybe, combining Kwin scripting + run command you can do something that solves your use case :+1:
