### ISSUE TITLE
Touchegg not working upon login

### ISSUE THREAD

**Issue by vaskark** [JoseExposito/touchegg#422]
### Describe the bug

Touchegg is not loading when I login. My startup file has a script that is set to launch touchegg with a symlink to the appropriate config file (I have several for different env's). This was happening fine with 2.0.3 so I assume it stopped working with 2.0.4

### Expected behaviour

Touchegg should be loaded and gestures working upon login.

### Actual behaviour

Touchegg does not load. I have to start it manually.

### Your environment

 * Version of Touchégg: 2.0.5
 * Operating System: Ubuntu Groovy (20.10)
 * Desktop Environment: Several (GNOME, berry, bspwm, ...)

### Log

```
$ journalctl -u touchegg -b -f
-- Logs begin at Wed 2021-01-06 02:50:02 EST. --
Jan 06 02:50:05 jabberwookiee touchegg[609]:         Calculating start_threshold and finish_threshold. You can tune this values in your service file
Jan 06 02:50:05 jabberwookiee touchegg[609]:         start_threshold: 135.704
Jan 06 02:50:05 jabberwookiee touchegg[609]:         finish_threshold_horizontal: 1629.67
Jan 06 02:50:05 jabberwookiee touchegg[609]:         finish_threshold_vertical: 1085.63
Jan 06 03:30:09 jabberwookiee touchegg[609]: New client connected with ID: 4
Jan 06 09:21:06 jabberwookiee touchegg[609]: libinput error: event6  - ELAN1300:00 04F3:3059 Touchpad: kernel bug: Touch jump detected and discarded.
Jan 06 09:21:06 jabberwookiee touchegg[609]: See https://wayland.freedesktop.org/libinput/doc/1.16.2/touchpad-jumping-cursors.html for details
Jan 06 15:16:10 jabberwookiee touchegg[609]: libinput error: event0  - Lid Switch: client bug: event processing lagging behind by 719ms, your system is too slow
Jan 06 15:17:17 jabberwookiee touchegg[609]: libinput error: event6  - ELAN1300:00 04F3:3059 Touchpad: kernel bug: Touch jump detected and discarded.
Jan 06 15:17:17 jabberwookiee touchegg[609]: See https://wayland.freedesktop.org/libinput/doc/1.16.2/touchpad-jumping-cursors.html for details
```
If other info is needed, please specify and let me know. As I stated earlier, touchegg works fine when I start my script manually. The binary also seems to still be open at the GDM screen when I logout. Not sure if this is expected.

Thanks. Terrific app, btw.

**Comment by JoseExposito** [comment]
So, I've being doing some testing with your script:
https://github.com/JoseExposito/touchegg/issues/409#issuecomment-755053057

And it seems to work. To test it, I run Touchégg in a terminal (to see the output) and, in a different terminal I executed your script step by step:

```bash
Starting Touchégg in client mode
Parsing you configuration file...
Using configuration file "/home/jose/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Successfully connected to Touchégg daemon

# Here I deleted the configuration file with:
# rm -f $HOME/.config/touchegg/touchegg.conf
# And it uses the conguration form /usr
Your configuration file changed, reloading your settings
Using configuration file "/usr/share/touchegg/touchegg.conf"

# Here I create the symlink
# ln -s $HOME/.config/touchegg_copy/touchegg.conf $HOME/.config/touchegg/touchegg.conf
# And it reloads the config
Your configuration file changed, reloading your settings
Using configuration file "/home/jose/.config/touchegg/touchegg.conf"
```

No need to kill and restart the process by the way. Let me know if it works without the kill.

**Comment by vaskark** [comment]
Thanks for doing all that testing, Jose. I really appreciate it.

I think the source of the problem is that the touchegg binary is still in memory when I log out and is frozen. Barring that, I believe my problem would be solved. The kill command would not be necessary (as you pointed out), and the rest of my solution would be sufficient.

**Comment by JoseExposito** [comment]
It shouldn't be in memory, maybe it is executed on login before your script... But that depends on your system configuration, so it could be.

Anyway, glad it worked without the kill command. I'm closing the issue, feel free to reopen it if you find more problems.
