### ISSUE TITLE
Libinput crash on manjaro (Magic trackpad 2)

### ISSUE THREAD

**Issue by geowarin** [JoseExposito/touchegg#425]
### Describe the bug

I'm getting some random crashes on manjaro with a magic trackpad over bluetooth.
The trackpad sometimes gets disconnected over bluetooth, IDK if it's relevant.

This seems to crash libinput so the only recourse is a hard reset (no keyboard).

Here is the output of `journalctl`.

```
janv. 08 16:30:47 geowarin-manjaro systemd-coredump[7227]: Process 1314 (touchegg) of user 0 dumped core.
                                                           
                                                           Stack trace of thread 1314:
                                                           #0  0x00007f94e028a615 raise (libc.so.6 + 0x3d615)
                                                           #1  0x00007f94e0273862 abort (libc.so.6 + 0x26862)
                                                           #2  0x00007f94e060c86a _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9686a)
                                                           #3  0x00007f94e0618d9a _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xa2d9a)
                                                           #4  0x00007f94e0618e07 _ZSt9terminatev (libstdc++.so.6 + 0xa2e07)
                                                           #5  0x00007f94e06190ae __cxa_throw (libstdc++.so.6 + 0xa30ae)
                                                           #6  0x000055e432a19cdd n/a (touchegg + 0x19cdd)
                                                           #7  0x00007f94e136268e n/a (libinput.so.10 + 0x2568e)
                                                           #8  0x00007f94e136872d n/a (libinput.so.10 + 0x2b72d)
                                                           #9  0x00007f94e136898d n/a (libinput.so.10 + 0x2b98d)
                                                           #10 0x00007f94e134c3b7 libinput_dispatch (libinput.so.10 + 0xf3b7)
                                                           #11 0x000055e432a27e9a _ZN23LibinputGestureGatherer3runEv (touchegg + 0x27e9a)
                                                           #12 0x000055e432a1b34f main (touchegg + 0x1b34f)
                                                           #13 0x00007f94e0275152 __libc_start_main (libc.so.6 + 0x28152)
                                                           #14 0x000055e432a1b4fe _start (touchegg + 0x1b4fe)
                                                           
                                                           Stack trace of thread 1335:
                                                           #0  0x00007f94e076813f accept (libpthread.so.0 + 0x1313f)
                                                           #1  0x000055e432a25620 n/a (touchegg + 0x25620)
                                                           #2  0x00007f94e0645c24 execute_native_thread_routine (libstdc++.so.6 + 0xcfc24)
                                                           #3  0x00007f94e075e3e9 start_thread (libpthread.so.0 + 0x93e9)
                                                           #4  0x00007f94e034d293 __clone (libc.so.6 + 0x100293)
```

### Your environment

 * Version of Touchégg: 2.0.5 (via AUR)
 * Operating System: Linux 5.9.16-1-MANJARO 
 * Desktop Environment: KDE plasma 5.20.4

Too bad I had to disable it, I love your software :). Tell me how I can help!

**Comment by JoseExposito** [comment]
Hi!

I also use a Magic Trackpad 2 and it is quiet unstable over Bluetooth.
Does your trackpad get disconnected without Touchégg running? In my case it does. Sometimes even the keyboard gets disconnected because of the trackpad crashing (without running Touchégg), so I usually connect it using the cable.

Is there any log related to libinput in your journalctl?

It seems like a problem calling `libinput_dispatch`, I'll need to install a newer kernel in order to fix this.
It looks like there are similar issues on other projects. What's your libinput version?
https://bbs.archlinux.org/viewtopic.php?id=240772
https://forum.archlabslinux.com/t/xorg-crashes-possible-libinput-bug/276/3
https://gitlab.gnome.org/GNOME/mutter/-/issues/1037

**Comment by geowarin** [comment]
Hi!

Libinput version is 1.16.4.
I've had the disconnection problem with my MacBook pro as well so I wouldn't be surprised if it got carried over to linux :)

Anyway, I'm testing this right now, I'll keep you posted.
The reason I mentioned that is I thought it could have something to do with the crash, like sending a signal to a disconnected device or something.

There are in fact more errors related to libinput and the trackpad. Here is the full log between 16:29:00 and 16:35:00 (at wich I might have reset the computer):

https://0x0.st/-sR6.txt

**Comment by geowarin** [comment]
Confirmed: The trackpad does quitely disconnect over bluetooth even without touchegg.

After further inspection, I had 3 crashes today:

 -3 bd3c131b46b14292a81d05645e48fb2c Thu 2021-01-07 16:17:36 CET—Fri 2021-01-08 16:02:43 CET <= CRASH (playing game)
 -2 d9232fe6baa446e784011afdeb61bb16 Fri 2021-01-08 16:04:46 CET—Fri 2021-01-08 17:06:07 CET <= CRASH (firefox)
 -1 4cba5d4f97934b99a9f768640bca8113 Fri 2021-01-08 17:07:53 CET—Fri 2021-01-08 17:16:58 CET <= CRASH (trying to `systemctl stop touchegg`)
  0 cf1f85574c7c42d3a4adc944e0d2fb3e Fri 2021-01-08 17:20:17 ...

---

First crash mentions a lot of libinput errors
`touchegg[3531]: libinput error: client bug: timer event21 debounce: scheduled expiry is in the past (-3ms), your system is too slow`
log leading to the crash: https://0x0.st/-s7s.txt


Second crash mentions a CPU lock after what looks like a connect/disconnect loop with the trackpad:
log leading to the crash: https://0x0.st/-s7z.txt


Third crash, same thing as the second one:
log leading to the crash: https://0x0.st/-s7-.txt

---

So the stacktrace mentionning touchegg happens 30 minutes before the second crash:

```
16:30:47 geowarin-manjaro systemd-coredump[7227]: Process 1314 (touchegg) of user 0 dumped core.
```

---

Here is the error log only `journalctl --since yesterday --priority=3`

https://0x0.st/-s7K.txt


So my conclusion is: I have a proble with baloo_file more than touchegg probably.
There are some stacktraces related to touchegg, which seems to be restarted by systemctl.

The reason why I opened the bug is I opened journalctl --priority=3 and found as many error with touchegg than reboots.
It is incidentally one of the last component I installed on my seemingly stable system.

Maybe you can see something in these logs I don't :)

**Comment by JoseExposito** [comment]
I think that the bug is happening on `libinput`, but, because Touchégg uses `libinput` as a library, the log show on its process. The fact that this disconnections also happen without Touchégg running make me think that the problem could be somewhere else. But I could be wrong.

I think it is worth it to report this, with your logs, in the `libinput` project. Maybe you can get more help there:
https://gitlab.freedesktop.org/libinput/libinput/-/issues
