### ISSUE TITLE
Make application name case insensitive

### ISSUE THREAD

**Issue by manjaronoob** [JoseExposito/touchegg#432]
### Describe the bug
By default the file /usr/share/touchegg/touchegg.conf contains the line
<application name="Google-chrome,Chromium-browser,Firefox">
In manjaro (and I guess other distros as well) Firefox is named firefox (all lower case), hence the gestures defined under this section does not catch when performed in Firefox. To make this failsafe it should look like this:
<application name="Google-chrome,Chromium-browser,Firefox,firefox">

As this may be distro dependent and version dependent, it could be a good idea to make touchegg ignore case when looking up application names.

### Expected behaviour

Default gestures work as defined in default config

### Actual behaviour

Default gestures defined for firefox outputs no action defined

### Your environment

 * Version of Touchégg: 2.0.5
 * Operating System: manjaro
 * Desktop Environment:  Xfce

**Comment by JoseExposito** [comment]
It looks like the XML you pasted has been removed, but I get the idea.
This is a great enhancement to add, I'll include this in the next release.

**Comment by manjaronoob** [comment]
Reposting the config lines in text only.
The default config contains the line
application name="Google-chrome,Chromium-browser,Firefox"
As the default name of Firefox is firefox in manjaro (and probably other distros), the gesture defined under this line in does not take effect. By modifying the line into
application name="Google-chrome,Chromium-browser,Firefox,firefox"
it works as expected.
