### ISSUE TITLE
Allow to easily override the default settings

### ISSUE THREAD

**Issue by JoseExposito** [JoseExposito/touchegg#439]
### Is your feature request related to a problem? Please describe

Default settings are fine for distros that just want to package Touchégg as it is.
However, when more personalisation is required it can be tricky to distribute good defaults and update them.

### Describe the solution you'd like

At the moment, there are 2 configuration files:

 - `/usr/share/touchegg/touchegg.conf`: Default settings. Packaged upstream and potentially changed on every update.
 - `~/.config/touchegg/touchegg.conf`: User settings. Takes precedence over `/usr/share`. For user configuration.

With this approach it is difficult to distribute updates by distros without upstream overriding them.

A good solution could be include an extra configuration file that I will not package upstream but that will take precedence over `/usr/share`.

**Maybe `/etc/touchegg/touchegg.conf`??**

In this way, the file used for settings will follow this order:

/home > /etc > /usr

I believe this approach will simplify the process for everyone.

### Describe alternatives you've considered

elementary OS is patching the package. We also tried to override the settings in `/usr/share/touchegg/touchegg.conf` but it seems like there are [some](https://github.com/elementary/default-settings/issues/209) [problems](https://github.com/elementary/os-patches/issues/161).

Adding a configuration file not packaged upstream should simplify the distribution process.

### Additional considerations

Changes will be required on [default-settings](https://github.com/elementary/default-settings), [switchboard](https://github.com/elementary/switchboard-plug-mouse-touchpad) and my [GUI](https://github.com/JoseExposito/touchegg-gui)

**Comment by cassidyjames** [comment]
I might not understand all of the complexity here, but I still don't _really_ see the need to do anything different than the configurations in `/usr/share/` and `~/`. By default Touchégg could install to `/usr/share/`. A user who wants to provide a custom configuration could then copy that to somewhere in `~/` and any conflicting rules would override the system-wide defaults. Distros can then patch/provide their own `/usr/share/`. I think the case where a user has customized their own local configuration is always going to potentially cause problems, but if someone is editing text files in their home directory, I don't know that there's anything we can reliably do to prevent conflicts.

This is consistent with how things like .desktop files work, as well; if a user customizes one in their home directory, they will no longer get changes from the system one unless they re-copy and modify it.

I should also clarify that I don't personally feel very strongly about any of this; for elementary, I don't think we are optimizing for anyone to edit text files, but should just make sure it works when a user changes their own settings in the Switchboard plug. In that case, ideally: if they have modified a setting, that setting should remain regardless of system updates, and if they have not modified a setting, it should follow the system default—this is how GSettings works for us with other settings.

Sorry if that's all tangential to this specific conversation. 😅

**Comment by danrabbit** [comment]
I'm not sure it's necessary to add more complexity. It's easy enough to just patch the default configuration :)

**Comment by JoseExposito** [comment]
If patching is ok, I'm fine with that.
I was worried about the linked bugs, but a properly patched package will avoid them.

Closing the issue, thanks for your input guys!

**Comment by LeoniePhiline** [comment]
@JoseExposito Am I missing something regarding disabling global (/usr/share) gestures in user configuration? 
I can't seem to disable them - only change their actions.
I'm having trouble with three finger swipe often pasting (three finger tap, middle mouse button) Xorg clipboard content, and wanted to disable the three finger tab in user config, while keeping the global config file untouched.

**Comment by JoseExposito** [comment]
Hi @LeoniePhiline ,

Please open a new bug report if you are having issues after trying this:

The easiest way to disable gestures is:
https://github.com/JoseExposito/touche#readme

3 finger tap to copy&paste is unrelated to Touchégg, you can disable it in your DE's settings:
 - GNOME: https://askubuntu.com/a/1214767
 - KDE: https://askubuntu.com/a/1356360

**Comment by LeoniePhiline** [comment]
Thanks for your response!
