### ISSUE TITLE
Go Back and Forward in chrome

### ISSUE THREAD

**Issue by victoruyy** [JoseExposito/touchegg#441]
Hi i've just downloaded the app and is really amazing, i loved it, it's very practical and useful, as i am most of my time using the browser one of the gestures that i like most is the swipe left or right that i can actually use just in windows (as usual) but i work at linux every day, and this would be very useful i think, it would be possible to add as an enhancement of the app something like this under the /usr/share/touchegg/touchegg.conf to go back and forward through pages? 

   ```
<gesture type="SWIPE" fingers="2" direction="LEFT">
      <action type="RETURN">
        <direction>left</direction>
        <animate>true</animate>
      </action>
    </gesture>

```
And the same for Right and forward to the next page, 

Just an idea, as a simple consumer,

Thank you,
Regards

**Comment by JoseExposito** [comment]
Hi!

Thanks for your feature request.

I'm afraid it is not possible to use swipe gestures with 2 fingers. The minimum number of fingers is 3 for touchpads and 2 for touchscreens, as documented here:
https://github.com/JoseExposito/touchegg#swipe

I absolutely agree with you, this is one of the features I miss the most in Chrome for Linux, but, it must be implemented in Chrome, not in a third party tool. It is in my to do list, but I just don't have enough time and too many stuff in mind.

If you want to emulate something similar, you can use [SEND_KEYS](https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys) and a 3 fingers swipe... But it is not the same.

Closing the issue as it is not something I can implement here, sorry.
