### ISSUE TITLE
How to Scroll in Touchscreen Linux Mint 20.1 Cinnamon

### ISSUE THREAD

**Issue by leomnzes** [JoseExposito/touchegg#445]
Hi, Im using Linux Mint 20.1 Cinnamon, with Dell Inspiron 11-3168-A10.

I have installed this new version 2.0, but I can't scroll in touchscreen with it.

I downgrade to Touchegg version 1.1 - ubuntu and it works with some issues. So I upgrade to this new version, it works but without scrolling.

I tried to write a new entry in ~/.config/touchegg/touchegg.conf, but I don't know how is the Action I need to use to scroll with 2 fingers in touchscreen.

Could some one help me with it?

Tks a lot.

**Comment by JoseExposito** [comment]
Hi!

I think this is a duplicated of https://github.com/JoseExposito/touchegg/issues/438

I'm afraid there is not much I can do here to offer a decent user experience...
