### ISSUE TITLE
Tile a Window doesn't work with two screens arranged vertically

### ISSUE THREAD

**Issue by gurolcay** [JoseExposito/touchegg#447]
### Describe the bug

Tiled window is moving wrong screen when window is on external screen.
I recorded a video. You can watch https://drive.google.com/file/d/14mmeN-9y_5uG3iD6gx7bGFV2zVCG8t04/view?usp=sharing

### Expected behaviour

When I swipe left with three finger to tile a window, window is tiling same screen.

### Actual behaviour

I am using an external screen. When I swipe left with three finger to tile a window, window is moving second screen.

### Your environment

 * Version of Touchégg: 2.0.7
 * Operating System: Ubuntu 20.04.2
 * Desktop Environment: Gnome 3.36.8
 * Windowing System: X11
 * uname -a
    * uname -a
Linux gurol-ThinkPad-L13 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by JoseExposito** [comment]
Thanks for the bug report. Yes, it looks like, when the screens are arranged vertically, the tile action fails and also animations are not displayed.

I'll look into it :+1:

**Comment by gurolcay** [comment]
Thank you for your attention.

**Comment by gurolcay** [comment]
Hello Jose.
Thank you new release. I tried again but now my screens side by side and there is still bug. There is another video for you: 
horizontal: https://drive.google.com/file/d/1F05neqmsO7jO_yx3CGHBs0-d2S-F-S2O/view?usp=sharing
vertical: https://drive.google.com/file/d/1TMZZcgpSXOt94xnJX7jnfdNyDGwKauxr/view?usp=sharing

If you need some specifical information about my system, I can give you.

**Comment by JoseExposito** [comment]
Mmmm OK, I'll try it again, thanks for reporting it!

**Comment by JoseExposito** [comment]
Hi @gurolcay 

I am not able to reproduce the issue on v2.0.8 using the same Ubuntu version and same arrangement.
Did you restart after upgrading to v2.0.8? The old version keeps running until you restart.

**Comment by gurolcay** [comment]
Hi @JoseExposito 

I didn't know the old version was running until I restarted my computer. I was thinking it's OK when I restarted the service.

Now, this problem is solved. Thank you.

**Comment by JoseExposito** [comment]
Cool, I'm glad it is fixed, thanks for your feedback :+1:
