### ISSUE TITLE
[QUESTION] How to configure key combination

### ISSUE THREAD

**Issue by dodalovic** [JoseExposito/touchegg#448]
Hi, thanks for you wonderful tools! I'm really enjoying using them!

I have a question: Is there a way to say: 

* In Chrome
* while holding `ALT`
* and swiping 3 fingers up

-> Fire key combination `ctrl+functionkey+Up`

Thanks!

**Comment by JoseExposito** [comment]
Hi!

You can not map the function key, instead, you need to map the key that is really triggered.

This is what you need to change tabs in Chrome:

```xml
  <application name="google-chrome">
    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>Page_Up</keys>
        <decreaseKeys>Page_Down</decreaseKeys>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="3" direction="RIGHT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>Page_Down</keys>
        <decreaseKeys>Page_Up</decreaseKeys>
      </action>
    </gesture>
  </application>
```

If you already have a `<application name="google-chrome">` tag, copy and paste the gestures inside it, don't duplicate the tag or it won't wotk.
