### ISSUE TITLE
Daily PPA builds for Ubuntu on Launchpad

### ISSUE THREAD

**Issue by shoogle** [JoseExposito/touchegg#451]
@JoseExposito, would you like me to setup PPA builds for touchegg on Ubuntu? I've done this before for a few projects:

- MuseScore [team](https://launchpad.net/~mscore-ubuntu/+members) / [PPA](https://launchpad.net/~mscore-ubuntu/+archive/ubuntu/mscore-stable) (recognised by upstream [here](https://musescore.org/en/download#Ubuntu))
- AppImageLauncher [team](https://launchpad.net/~appimagelauncher-team/+members) / [PPA](https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable) (recognised by upstream [here](https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian), discussion [here](https://github.com/TheAssassin/AppImageLauncher/issues/201))

The touchegg PPA would automatically create a new build once per day, whenever you have pushed new commits to a particular branch of the [JoseExposito/touchegg](/JoseExposito/touchegg) repository here on GitHub. The build would be of the [master branch](https://github.com/JoseExposito/touchegg/tree/stable), or (ideally) a new branch called `stable` that would always track the latest release.

__The only effort required from you would be to make sure that the `stable` branch always points to the latest release.__

(Also, twice per year, you or I would need to log-in to Launchpad and tick a box to enable builds for the newest Ubuntu release.)

### First time setup

The initial setup is a 4 step process, but I can take care of it all for you if you like:

1. [Create a team](https://launchpad.net/people/+newteam) for touchegg on launchpad (I'd invite [you](https://launchpad.net/~jose-exposito89) to be an Administrator of this team to make it official).
2. Create a PPA under this team to build and host DEB binary packages.
3. Setup [code imports](https://help.launchpad.net/Code/Imports) from GitHub (creates a mirror git repo of [JoseExposito/touchegg](/JoseExposito/touchegg) on Launchpad).
4. Create a [Recipe](https://help.launchpad.net/Packaging/SourceBuilds/Recipes) to build a DEB source package (tarball) and upload to PPA where it gets built into a binary package.

Let me know if you'd like me to set this up for you, or if you'd prefer to do it yourself :wink: (I can talk you through it if you like).

Alternatively, you could do step 1 yourself (i.e. create the team) then make me an Admin and I'd do the rest.

**Comment by JoseExposito** [comment]
Hi @shoogle and thanks for offering to do this :smile: 

I think that having a PPA will be nice. The version in the official repo is just too old (https://launchpad.net/ubuntu/+source/touchegg) and I don't think there is any interest on updating it.

If you don't mind, I'd like to create the official PPA myself following your steps.
Thanks a lot, labeling the issue and leaving it open so I can ask you questions if I find problems.

I'll try to look into this the this weekend.

**Comment by shoogle** [comment]
@JoseExposito, you're welcome! I understand why you'd prefer to do this yourself, and that suits me just fine too 😉 

I'll post some tips here in the coming days to make it easy for you, but in the meantime, I recommend creating the team sooner rather than later so that you can claim the obvious URL before anyone else does. The other steps can wait until afterwards.

**Comment by shoogle** [comment]
Ok, here's a more detailed guide. It might look a bit complicated but really there's not much to it. Its just long because I tried to explain the reasons behind each step, and also added some optional hints and tips that can probably be ignored in most cases.

Before you begin, you should create a new branch called `stable` here on GitHub. This branch should always point to the commit / tag corresponding to the latest stable release (currently [78b85c6](https://github.com/JoseExposito/touchegg/commit/78b85c6278f624bd63fddf1a4e9334c0f33a0aa9) / [2.0.7](https://github.com/JoseExposito/touchegg/releases/tag/2.0.7)). You will need to manually update this branch with each new release, but it only takes a couple of lines of Bash and could be added to a release script or TODO list.

### Step 0: Create personal launchpad account

Looks like you already have one. Either way, visit https://launchpad.net/ and click "Log in / Register" in the top right.

**Comment by shoogle** [comment]
### Step 1: Create team

Basically equivalent to a GitHub organisation but on Launchpad. Visit [this page](https://launchpad.net/people/+newteam) while signed into your personal account and enter:

__Name:__ `touchegg` or `touchegg-team` (will appear in URLs, e.g. `https://launchpad.net/~touchegg` or `~touchegg-team`)
__Display Name:__ Touchégg
__Description:__ *whatever* (see [this team](https://launchpad.net/~appimagelauncher-team)'s description for inspiration)
__Membership:__ moderated or restricted
__Subscription period:__ *leave blank* (membership never expires)
__When someone's membership is about to expire, notify them and:__ *any option* (ignored due to unlimited subscription period).

Optional: invite other Launchpad users to join the team to help manage the PPA, code import and recipe.

Note: using `touchegg-team` as the team name helps to distinguish it from the Touchegg "project" at https://launchpad.net/touchegg. Projects in Launchpad are just neutral markers that are used to group related code. If a random user creates their own touchegg build they can add it to the Touchegg project (neutral) but not the Touchégg team (owned by you). Luckily the team usually appears higher in search results than the project, so appending `-team` to the name is not strictly necessary. I did it for [AppImageLauncher](https://launchpad.net/~appimagelauncher-team) but probably wouldn't bother again in future because leaving it off gives a nicer URL. Alternatively, you could use `touchegg-ubuntu` as the team name since the Lauchpad team only serves Ubuntu.

**Comment by shoogle** [comment]
### Step 2: Create PPA(s)

*Tip: I recommend creating two PPAs: one for daily builds of the master branch, and one for stable releases. Start with the daily one so you get the hang of it before creating the stable one. The daily one allows experienced users to find bugs quickly so you can fix them before releasing the next stable build.*

Visit team page, scroll down to "Personal package archives" and click "Create a new PPA".

__Name:__ `daily` (will appear in URL, e.g. https://launchpad.net/~touchegg/+archive/ubuntu/daily)
__Display Name:__ Touchégg - Daily PPA - Highly Unstable, Perfect for Testers
__Description:__ *whatever* (see [this daily PPA](https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/daily)'s description for inspiration)

__Name:__ `stable` (will appear in URL, e.g. https://launchpad.net/~touchegg/+archive/ubuntu/stable)
__Display Name:__ Touchégg - Stable PPA - Official Releases
__Description:__ *whatever* (see [this stable PPA](https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable)'s description for inspiration)

Note that the PPA name and description will be displayed in the terminal when users run the `add-apt-repository` command.

**Comment by shoogle** [comment]
### Step 3: Setup code imports

Visit the [code import page](https://code.launchpad.net/+code-imports/+new) while signed into your personal account.

__Owner:__ Choose the Touchégg team (not your personal account)
__Project:__ `touchegg` (associates it with https://launchpad.net/touchegg, a neutral marker for all touchegg content on Launchpad)
__Name:__ `touchegg` (appears in URLs but PPA users don't need to know it)
__Git: Repo URL:__ https://github.com/JoseExposito/touchegg
__Target version control system:__ Git (otherwise Launchpad will try to convert it to [Bazaar](https://en.wikipedia.org/wiki/GNU_Bazaar) during import, which creates [problems](https://stackoverflow.com/q/36414732))

Click "Request Import". The import should happen within a few minutes, and from then on it will be updated automatically every few hours to match the GitHub repo.

Notes:

1. This single code import includes all branches, so there's no need to create a separate import for the master and stable branches. The same code import can be used by both daily and stable recipes.
2. The final import will appear at https://code.launchpad.net/~touchegg/touchegg/+git/touchegg (i.e. https://code.launchpad.net/~[team]/[project]/+git/[repo]) and referred to with the alias `lp:~touchegg/touchegg/+git/touchegg`.
    - You should be able to remove at least one instance of `touchegg`s from the URL/alias by visiting the repository page, clicking "Change repository details", and clicking the "Owner default" checkbox. However, users don't need to know the import URL, so there's no real need to make it shorter.
3. Notice that if you visit your team page and click "Code" it says "There are no branches...". This is because it shows Bazaar repos by default. You need to click "View Git repositories" on the right hand side to see your new import.

**Comment by shoogle** [comment]
### Step 4a: Create daily recipe

Recipes contain instructions to take the imported code and turn it into a DEB source package. This source package is then uploaded to a PPA where it gets built into a binary package.

Visit the page for the code import created in Step 2 (probably https://code.launchpad.net/~touchegg/touchegg/+git/touchegg). Scroll down to "Related source package recipes" and click "Create packaging recipe".

__Name:__ `touchegg-daily` (appears in URLs but PPA users don't see it)
__Description:__ Write something or leave blank (PPA users don't see it)
__Owner:__ Choose the Touchégg team (not your personal account)
__Built daily:__ yes
__Use an existing PPA:__ Choose the Daily PPA
__Default distribution series:__ Tick all that are [still supported](https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions) by Canonical and by you

__Recipe text:__

```
# git-build-recipe format 0.4 deb-version {time}-master-{git-commit}
lp:~touchegg/touchegg/+git/touchegg master
```

That's it, just 2 lines! (Some recipes need more though.) Here's what the lines mean:

- Top line: `# git-build-recipe format 0.4 deb-version {time}-master-{git-commit}`
- Meaning: Use version 0.4 of the recipe format. Create a new entry in [debian/changelog](https://github.com/JoseExposito/touchegg/blob/master/debian/changelog) with a version that incudes the current day and time (e.g. `202102131704`, the fixed string "-master-", and the git short commit SHA (7 hex digits).

Notes on `deb-version`:

- The version for each build must always be [greater than](https://www.debian.org/doc/manuals/maint-guide/first.en.html#namever) the one before or updating will fail
- You could use "{debupstream}" to use the number that's already there, but that's not really useful for daily builds, you'd still need to append something like "-{time}" to ensure it increases, and there's a risk you screw up the version number in the original file or find it conflicts with the version number of an actual distribution package of touchegg
- PPA builds use tarball rather than git repositories, so adding branch and commit information to the version is the only way to get that information into the build

Second line: `lp:~touchegg/touchegg/+git/touchegg master`
Meaning: Use the master branch of the repository at `lp:~touchegg/touchegg/+git/touchegg`.

Many recipes contain additional lines starting `merge`, `nest` or `nest-part` that pull in code from other repositories on Launchpad. Their meanings are explained in [this guide](https://help.launchpad.net/Packaging/SourceBuilds/Recipes). Here's an example with `merge`:

Possible third line: `merge packaging lp:~[team]/[project]/+git/touchegg-packaging master`
Meaning: Also include all files from the master branch of the repository at `lp:~[team]/[project]/+git/touchegg-packaging` (the files will keep their relative paths in the merged repo). Label this line "packaging" for use further down the recipe.

The extra lines are usually used to insert a `debian` folder with packaging information into the root of the project (or to replace the `debian` folder that's already there with a new one). However, you don't need to do this for Touchegg because you already have a [debian folder](https://github.com/JoseExposito/touchegg/tree/master/debian), and if you need to make changes to it then you can do so right here on GitHub. Additional recipe lines can also be used to add more code folders (e.g. with sources for upstream libraries), but your build scripts will need to check for these folders and make use of them if they are found.

Once done entering the recipe text, click "Create Recipe". If you enabled "build daily" then you should see a build scheduled for some time soon, but your can request one immediately using the "Request build(s)" link near the bottom of the page. Future daily builds will happen roughly once every 24 hours the first one, only on days where code in the relevant branch(es) has actually changed.

Make sure the daily recipe works and builds appear in the daily PPA (and that they work) before moving onto the stable recipe.

**Comment by shoogle** [comment]
### Step 4b: Create stable recipe

Repeat step 4a with the following changes:

__Name:__ `touchegg-stable` (appears in URLs but PPA users don't see it)
__Description:__ New description or leave blank (PPA users don't see it)
__Use an existing PPA:__ Choose the Stable PPA (not the Daily PPA)

__Recipe text:__

```
# git-build-recipe format 0.4 deb-version {time}-stable-{debupstream}
lp:~touchegg/touchegg/+git/touchegg stable
```

Line 1: notice we use `{debupstream}` to include the actual version number instead of a commit SHA, but we still put `{time}` first to avoid conflicts with distribution packages.

Line 2:  notice this now points to the branch called "stable". It doesn't have to be a branch name, it could be a tag or even a [commit message based on regex](https://github.com/TheAssassin/AppImageLauncher/issues/201#issuecomment-553622848) (e.g. `:^Release`), although this [might not be such a good idea](https://github.com/TheAssassin/AppImageLauncher/issues/201#issuecomment-557857685). It would be great if we could say "always use the latest tag" but unfortunately that's not possible. In practice the best thing to do is use a branch and remember to keep it up to date.

The stable PPA should still be built daily. Remember it will only be built on days that code in the `stable` branch has changed. Of course you could trigger the stable builds manually if you really want to, and even edit the recipe manually to point to a specific tag, but that just creates extra work for you, so it's best to leave it to be build automatically.

**Comment by shoogle** [comment]
### Recipe Tips:

- If necessary, you can add conditional code to your build scripts that only runs on Lauchpad (i.e. not on normal Debian or Ubuntu build machines). To do this, use `grep` or similar within build scripts to check whether the version number in [debian/changelog](https://github.com/JoseExposito/touchegg/blob/master/debian/changelog) matches the format of the one given in the recipe (after `deb-version`). You can also use `sed` to extract information from the version number, such as the branch name or git commit SHA (if your version number contains them).

- When building somebody else's repository you often need to create a debian folder yourself and add it using a third recipe line. This new debian folder might be the only thing you have control over in the entire repository. In that case, a good place to put conditional code is in [debian/rules](https://github.com/JoseExposito/touchegg/blob/master/debian/changelog) (e.g. under `override_dh_auto_configure:`). If building your own repository (like touchegg) then you can add conditional code to any build scripts anywhere in the repository and wait for the next Launchpad import.

- Every year in April and October you should login to Launchpad and enable builds for the latest Ubuntu version released that month. You can do it before the official release date and it will build against pre-release versions of the distro.

**Comment by shoogle** [comment]
### Step 4b: Create stable recipe

Repeat step 4a with the following changes:

__Name:__ `touchegg-stable` (appears in URLs but PPA users don't see it)
__Description:__ New description or leave blank (PPA users don't see it)
__Use an existing PPA:__ Choose the Stable PPA (not the Daily PPA)

__Recipe text:__

```
# git-build-recipe format 0.4 deb-version {time}-stable-{debupstream}
lp:~touchegg/touchegg/+git/touchegg stable
```

Line 1: notice we use `{debupstream}` to include the actual version number instead of a commit SHA, but we still put `{time}` first to avoid conflicts with distribution packages.

Line 2:  notice this now points to the branch called "stable". It doesn't have to be a branch name, it could be a tag or even a [commit message based on regex](https://github.com/TheAssassin/AppImageLauncher/issues/201#issuecomment-553622848) (e.g. `:^Release`), although this [might not be such a good idea](https://github.com/TheAssassin/AppImageLauncher/issues/201#issuecomment-557857685). It would be great if we could say "always use the latest tag" but unfortunately that's not possible. In practice the best thing to do is use a branch and remember to keep it up to date.

The stable PPA should still be built daily. Remember it will only be built on days that code in the `stable` branch has changed. Of course you could trigger the stable builds manually if you really want to, and even edit the recipe manually to point to a specific tag, but that just creates extra work for you, so it's best to leave it to be build automatically.

**Comment by JoseExposito** [comment]
Holy :hankey: mate! What a great guide! This is going right into my bookmarks. Navigating launchpad's interface is not always easy, you saved me a ton of googling... and tears.

I managed to setup both the daily PPA and the stable one in about 1 hour thanks to your guide:
https://launchpad.net/~touchegg

For the stable one I created a `ppa` branch (instead of `stable`). It is a pain to have to maintain an extra branch, so I created a GitHub action to merge `master` into `ppa` every time I create a release so I don't forget the extra step:
https://github.com/JoseExposito/touchegg/blob/master/.github/workflows/release-ppa.yml

Now I'll try to include [Touché](https://github.com/JoseExposito/touche) in the same PPAs.

Thanks again for taking the time to write this guide!

**Comment by shoogle** [comment]
No problem! I figured I could copy this into a gist or something so other people can find it.

I tried the Stable PPA on Ubuntu 20.04 and its working fine.

Good idea to use a GitHub Action to keep the branch up to date!

**Comment by martinpescador** [comment]
PPA is great, but I get:

:~$ sudo apt update

W: GPG error: http://ppa.launchpad.net/touchegg/stable/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0FCE32AF6B96252

and

:~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C0FCE32AF6B96252

Executing: /tmp/apt-key-gpghome.IPxVXs9M7G/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys C0FCE32AF6B96252
gpg: keyserver receive failed: No data

**Comment by shoogle** [comment]
@martinpescador, try removing it, updating, then adding it again:

```bash
sudo add-apt-repository --remove ppa:touchegg/stable
sudo apt update
sudo apt upgrade
sudo add-apt-repository ppa:touchegg/stable
sudo apt update
sudo apt install touchegg
```

You'll need to copy these one-at-a-time because some steps require manual confirmation.

**Comment by endorama** [comment]
Hello, I've been trying to use this PPA with elementary Hera, based on Ubuntu Bionic and I noticed there are no releases available. As I would love to be able to use Touchegg on elementary would you think it could be supported? Willing to help if needed.

@shoogle your guide is :star_struck: :clap::clap: awesome job, thank you!

**Comment by JoseExposito** [comment]
Hi @endorama 

As far as I know, it is not possible to use the PPA in elementary OS 5. You can always install from deb package. If you find problems in the process, please open a new issue.
Touchégg will be included out of the box on elementary OS 6 by the way.

**Comment by JoseExposito** [comment]
> I'm able to use them after installing the required Python package. In any case I understand if you don't consider this useful, and deb installation works as expected.

Cool! I'd appreciate if you could create a merge request adding the install instruction in the README file. If creating a merge request is complex, feel free to open a new issue with the instructions and I'll add them for you :)
