### ISSUE TITLE
Segfault on Ubuntu 20.04 (Wayland)

### ISSUE THREAD

**Issue by carallo** [JoseExposito/touchegg#455]
Hi!
First of all thank you for your amazing work!

I have an issue though. I installed touchegg with your latest .deb on Ubuntu 20.04 (Wayland session). I started it in the terminal and it was working. I also installed Touché from flathub and could configure it without issues. Then I restarted my system and it's not working anymore, it starts but as soon as I try a gesture I get a segfault. I tried uninstalling and purging both touchegg and Touché but I still cannot make it work, I get a segfault error. From the log I found this, that might be the issue:

`touchegg[8147]: segfault at 0 ip 000055c4d4a89e77 sp 00007ffdb2dd98c0 error 4 in touchegg[55c4d4a59000+47000]`

Do you know what could the problem be? I don't know how to get more relevant info from the log.

Thank you again and have a nice day!

**Comment by JoseExposito** [comment]
Hi, and thanks for your bug report.

Unfortunately, Touchégg does not work on Wayland:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

And it is not possible to port it to Wayland... At lest with the current protocols :disappointed:

**Comment by carallo** [comment]
Ouch! I thought I had read somewhere something like "improved Wayland support" for the latest version. I should have checked more thoroughly... 
So bad it isn't supported, Wayland has some "pixel-perfect" gestures but they're not configurable as with touchegg.

Thank you so much anyway and keep up the great work! :)
