### ISSUE TITLE
32 bit linux

### ISSUE THREAD

**Issue by JueGoWinDo** [JoseExposito/touchegg#461]
I didn't find a 32 bit .deb file
Would you make a 32 bit .deb file?

**Comment by JoseExposito** [comment]
Hi, and thanks for you feature request.

At the moment not many distros support 32 bits, and it is also not supported by the PPA, so, I'm afraid I can not add support for this architecture.
However, you can compile the source code yourself following this instructions:
https://github.com/JoseExposito/touchegg/blob/master/HACKING.md#compilation

Let me know if you find any issues so I can help you.
