### ISSUE TITLE
Wont work on fresh install of elementary os 5.1

### ISSUE THREAD

**Issue by lantgabor** [JoseExposito/touchegg#463]
### Describe the bug

Fresh install of elementray os 5.1. Installed touchegg and touché using apt.

### Expected behaviour

Touch gestures should be working afteer reboot or running touchegg

### Actual behaviour

Nothing happens. No error messages.

### Your environment

![image (1)](https://user-images.githubusercontent.com/44365153/109072485-634d2f80-76f5-11eb-8ae5-dc87136315c2.png)

Microsoft precision trackpad

**Comment by JoseExposito** [comment]
Hi!

Unfortunately, the version of Touchégg available in the repository (apt) is too old. You will need to install the latest version.

Start by removing the version you just installed:
```bash
$ sudo apt remove touchegg
$ rm -fr ~/.config/touchegg # This command will delete the old configuration
```

And now download install the latest version from deb:
https://github.com/JoseExposito/touchegg/releases

Instructions:
https://github.com/JoseExposito/touchegg#installation
