### ISSUE TITLE
GNOME shell gestures overriding Touchegg assigned Application gestures.

### ISSUE THREAD

**Issue by StAletheus** [JoseExposito/touchegg#464]
### Describe the bug

A clear and concise description of what the bug is and how to reproduce it.

Gestures for desktop management under GNOME keep me from using gestures i've set in Touchegg for Krita. i've Turned off GNOME gestures and tweaks for mouse emulation, but krita still doesn't seem to be accepting gestures assigned by touchegg.

### Expected behaviour

It would be fantastic if i could run both seamlessly, and disable GNOME globally when in krita. 

### Actual behaviour

*I can't seem to figure out how to print the output of whether touchegg is responsive in terminal.*
*edit*--okay thats what --debug is for. so yes, i am getting output. moving on to see if its responding directly to krita.
*2nd edit* apparently I am the bug, and only have a QUESTION:

**how do I assign pg up, tab, and other keys as keyboard shortcuts?** 

*it looks like i just needed to find the [keyboard mapping codes](https://gist.github.com/matoken/5c2b9d2f0b92c21452cf8b4f01f7e149)*

---and the keymapping section of the configuration guide...

### Logs

If required, include logs of the bug:

```
$ touchegg --debug
`Gesture begin detected
	Gesture information:
		Fingers: 4
		Type: SWIPE
		Direction: UP
	Gesture performed on app: krita
	Action configured for this gesture
	Starting action
Error performing keyboard shortcut. Unknown key: Ctrl
Error performing keyboard shortcut. Unknown key: .
Error performing keyboard shortcut. Unknown key: .
`

```

### Your environment

 * Version of Touchégg: Run `touchegg --version` in the terminal to check the version 
     2.0.7.1

 * Operating System: Ubuntu, Fedora, Arch Linux...
    Fedora 33

 * Desktop Environment: Gnome, KDE, Xfce...
    GNOME

running on a Samsung Notebook 9 pro 15 2 in 1. i'm an artist, so being able to operate completely from the display is something i'm dedicated to figuring out. 

Thanks for the time!

**Comment by JoseExposito** [comment]
Hi and thank you for the detailed bug report.

Are you using the Wayland session? Touchégg is only compatible with X11:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland
You can check if you are using Wayland or X11 in Setings -> About -> Windowing System.

Some actions might work on Wayland (like SEND_KEYS or RUN_COMMAND) but as soon as you try to execute any action that displays an animation it'll crash.

About your problem: Unfortunately, I can not avoid GNOME Shell using the same gestures that are configured in Touchégg, so, you won't be able to use 4 fingers up/down swipes. You can still use the other gestures though.

You can find more information and examples about the SEND_KEYS action here:
https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys

Feel free to reopen the issue if you are not using Wayland or have problems configuring your shortcuts.
