### ISSUE TITLE
Touchegg ubuntu ppa installation does not work

### ISSUE THREAD

**Issue by martinmaehlmann** [JoseExposito/touchegg#466]
Installing touchegg with the ppa repository `ppa:touchegg/stable` results in a not working system.

> System: !Pop_OS 20.10
> Laptop: HP Envy x360 15''

I followed the installation steps described in Readme.MD
```
$ sudo add-apt-repository ppa:touchegg/stable
$ sudo apt update
$ sudo apt install touchegg
```

This did not install the systemd file into the directory `/lib/systemd/system/touchegg.service` or any other systemd directory (checked `/etc/systemd/system`). As a result the touchegg daemon did not start accordingly.
I tried creating the file manually, but failed.

Additionally, I tried running touchegg from the command line and no gestures were registered.

As a workaround, the installation with the latest .deb package does work like a charm.

**Comment by martinmaehlmann** [comment]
PS: cool project, I like using it very much :)

**Comment by JoseExposito** [comment]
Are you getting a similar error to https://github.com/JoseExposito/touchegg/issues/462 ?

**Comment by martinmaehlmann** [comment]
No, unfortunately not. The installation itself runs fine, the application does not launch afterwards. As stated, the systemd files are missing.

```
sudo add-apt-repository ppa:touchegg/stable
Repository: 'deb http://ppa.launchpad.net/touchegg/stable/ubuntu/ groovy main'
Description:
Latest stable version of Touchégg for all Ubuntu flavours.

Touchégg is an app that runs in the background and transform the gestures you make on your touchpad or touchscreen into visible actions in your desktop. Learn more at https://github.com/JoseExposito/touchegg
More info: https://launchpad.net/~touchegg/+archive/ubuntu/stable
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/touchegg-ubuntu-stable-groovy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/touchegg-ubuntu-stable-groovy.list
Adding key to /etc/apt/trusted.gpg.d/touchegg-ubuntu-stable.gpg with fingerprint 7EA12677D47B593CE22727D4C0FCE32AF6B96252
Hit:1 http://ppa.launchpad.net/system76/pop/ubuntu groovy InRelease
Get:2 http://ppa.launchpad.net/touchegg/stable/ubuntu groovy InRelease [18.1 kB]
Get:3 https://mega.nz/linux/MEGAsync/xUbuntu_20.10 ./ InRelease [2,441 B]      
Hit:4 http://us.archive.ubuntu.com/ubuntu groovy InRelease                     
Hit:5 http://us.archive.ubuntu.com/ubuntu groovy-security InRelease            
Hit:6 http://apt.pop-os.org/proprietary groovy InRelease                       
Get:7 http://ppa.launchpad.net/touchegg/stable/ubuntu groovy/main amd64 Packages [600 B]
Hit:8 http://us.archive.ubuntu.com/ubuntu groovy-updates InRelease             
Hit:9 https://download.sublimetext.com apt/stable/ InRelease                   
Get:10 http://ppa.launchpad.net/touchegg/stable/ubuntu groovy/main Translation-en [340 B]
Hit:11 http://us.archive.ubuntu.com/ubuntu groovy-backports InRelease          
Fetched 21.5 kB in 1s (15.9 kB/s)
Reading package lists... Done

sudo apt update
Hit:1 http://ppa.launchpad.net/system76/pop/ubuntu groovy InRelease
Hit:2 http://ppa.launchpad.net/touchegg/stable/ubuntu groovy InRelease         
Get:3 https://mega.nz/linux/MEGAsync/xUbuntu_20.10 ./ InRelease [2,441 B]      
Hit:4 http://us.archive.ubuntu.com/ubuntu groovy InRelease                     
Hit:5 http://us.archive.ubuntu.com/ubuntu groovy-security InRelease            
Hit:6 http://apt.pop-os.org/proprietary groovy InRelease                       
Hit:7 http://us.archive.ubuntu.com/ubuntu groovy-updates InRelease  
Hit:8 https://download.sublimetext.com apt/stable/ InRelease
Hit:9 http://us.archive.ubuntu.com/ubuntu groovy-backports InRelease
Fetched 2,441 B in 1s (1,841 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

**Comment by JoseExposito** [comment]
It looks like adding the PPA and `apt update` run successfully. What's the log for `sudo apt install touchegg`? After installing it, what the version installed? (`touchegg --version`)

**Comment by martinmaehlmann** [comment]
```
sudo apt install touchegg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libframe6 libgeis1 libgrail6 libqt5xml5
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  touchegg
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 122 kB of archives.
After this operation, 423 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/touchegg/stable/ubuntu groovy/main amd64 touchegg amd64 202102250736-stable-2.0.8~ubuntu20.10.1 [122 kB]
Fetched 122 kB in 0s (1,158 kB/s)
Selecting previously unselected package touchegg.
(Reading database ... 218665 files and directories currently installed.)
Preparing to unpack .../touchegg_202102250736-stable-2.0.8~ubuntu20.10.1_amd64.d
eb ...
Unpacking touchegg (202102250736-stable-2.0.8~ubuntu20.10.1) ...
Setting up touchegg (202102250736-stable-2.0.8~ubuntu20.10.1) ...

touchegg --version
Touchégg v2.0.8.
```

**Comment by JoseExposito** [comment]
There is a very old version of Touchégg (1.1.1) available in the official Ubuntu repo:
https://launchpad.net/touchegg

Because of this log:

```
The following packages were automatically installed and are no longer required:
  libframe6 libgeis1 libgrail6 libqt5xml5
```

It seems like something failed in your previous installation and you installed the old version.

Now, the service file and everything else should be in place. Can you confirm it?
Make sure that your config file (`~/.config/touchegg/touchegg.conf`) is the one from v2 or you'll get some random crashes.

**Comment by martinmaehlmann** [comment]
Well, hard to tell, as I got it working beforehand by using the .deb package.

But yes, it is now working.

**Comment by Rohit-code** [comment]
I'm getting this error
sudo add-apt-repository ppa:touchegg/stable
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'

**Comment by dpere122** [comment]
@Rohit-code I had to download this package to fix that error
`sudo apt install  python3-launchpadlib`
on debian 12
