### ISSUE TITLE
Three/3 finger drag support

### ISSUE THREAD

**Issue by JJGadgets** [JoseExposito/touchegg#468]
### Is your feature request related to a problem? Please describe

I much prefer macOS's 3 finger drag to single click drag & drop, especially when not on a ThinkPad where the dedicated buttons are on top (that makes it easier for me rather than cramping fingers to hold the left click while dragging). I find it provides more precision and ease of use. However, 3 finger drag on Linux seems to be a feature missing from many Linux gesture programs.

### Describe the solution you'd like

Implement optional 3 finger drag into Touchegg.

### Describe alternatives you've considered

Add support for https://github.com/marsqing/libinput-three-finger-drag which I now use with Touchegg but it is buggy when Touchegg is launched, both seem to conflict at times, mostly Touchegg blocking libinput-three-finger-drag.

**Comment by JoseExposito** [comment]
Make sure you disabled every 3 fingers swipe gesture in Touchégg. If you are using [Touché](https://github.com/JoseExposito/touche) for configuration, every checkbox in the section "Swipe with 3 fingers" must be disabled.
