### ISSUE TITLE
Touchegg doesn't work unless i enable touchegg.service

### ISSUE THREAD

**Issue by KonstantMan** [JoseExposito/touchegg#469]
### Describe the bug

After installing touchegg  touche and the extesnion ,the gestures don't  work unless i enable touchegg.service

### Expected behaviour
Touchegg should work after rebooting

### Actual behaviour
touchegg                                                      
Touchégg v2.0.8.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/usr/share/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Error connecting to Touchégg daemon: Could not connect: Connection refused

### Your environment

 * Version of Touchégg: Touchégg v2.0.8.
 * Operating System: Arch Linux
 * Desktop Environment: Gnome

**Comment by JoseExposito** [comment]
Hi

That's the default behaviour on Arch:
https://github.com/JoseExposito/touchegg/issues/413#issuecomment-748502847

However it wasn't documented, so I added some docs:
https://github.com/JoseExposito/touchegg#arch-linux-manjaro-and-derivatives
