### ISSUE TITLE
Thumb detection, thumb clicking + index finger on Trackpad, and palm detection

### ISSUE THREAD

**Issue by ylluminate** [JoseExposito/touchegg#474]
I'm attempting to emulate macOS feel and experience while using Apple Magic Trackpad 2 devices on Linux.

There is a tutorial that claims to emulate the experience perhaps nearly completely here:
https://howchoo.com/linux/the-perfect-almost-touchpad-settings-on-linux-2

But someone suggested that I give Touchegg a try instead thinking it might work (better) and be better supported.

Is it possible to accomplish the same designs of that tutorial with Touchegg?

**Comment by JoseExposito** [comment]
Hi! I use a Magic Trackpad and I have not tested the `mtrack` because the [libinput](https://wayland.freedesktop.org/libinput/doc/latest/features.html) driver already ships all those features and honestly, it works *really* well.

My sugestion is, give it a try to the libinput driver + Touchégg + [Touché](https://github.com/JoseExposito/touche) first, mostly because your distro is most likely shipping the libinput driver preinstalled. 
Then, if you don't like the user experience, go ahead and try the `mtrack` driver... And let me know how that worked :smile: 

By the way, Touchégg will only work over libinput.

**Comment by ylluminate** [comment]
I'm struggling a bit finding an up-to-date package for OpenSUSE TumbleWeed (GeckoLinux specifically; note https://github.com/geckolinux/geckolinux-project/issues/207).

While I'm hunting: what did you do specifically to facilitate the "thumb functionality" that seems to be the dilemma and requires additional configuration in all Linux distros I've tried so far (which interestingly do detect the Magic Trackpad 2, but fail to provide native-like experiences, particularly with thumb detection/usage)?

**Comment by ylluminate** [comment]
I don't know how package management updates work there yet - I've dabbled with OpenSUSE in the past, but just starting back in on it with GeckoLinux Pantheon.  This OpenSUSE TumbleWeed rolling updates + elementary's Pantheon is really awesome since it's a better model than the elementary OS guys' normal release cycle, but there are some package age issues on some of the outlying packages.

It appears `libinput10` is at 1.16.4-2.2 with an update to 1.17.0-1.2 if an upgrade is desirable. `xf86-input-libinput` is at 0.30.0-1.4 with an upgrade available to 0.30.0-2.1.

So far my biggest problem is that I rest my thumb on my trackpad while I use it and everything I've tried so far seems to not default to having thumb detection on by default and so when I click with my thumb while my index finger is still on the trackpad, it makes it nearly impossible to click things accurately and thus jerks the cursor or moves the horizontal or vertical scroll.  That's probably the biggest problem I have and makes it impossible to do nearly anything.

**Comment by JoseExposito** [comment]
1.16.4 already includes the [changes](https://lists.freedesktop.org/archives/wayland-devel/2020-October/041640.html) for the Magic Trackpad 2, so it should be good enough.

I'm afraid I can not help you, it just works here. I wish I could give you some advice.

**Comment by JoseExposito** [comment]
Here is a demo using `libinput-debug-gui` to show what I mean. The blue circles in the square placed on the right are my finger. As you can see I can rest my thumb on the touchpad and move the cursor (that line that is painted), scroll (the green rectangles) or swipe (yellow-ish circles in the middle + the actions triggered on my desktop).

You should be able to do something similar:

https://user-images.githubusercontent.com/1335948/113191748-32b16600-925e-11eb-8d91-305fea9dffe6.mp4
