### ISSUE TITLE
libstdc++.so.6(GLIBCXX_3.4.26)(64bit) is needed by touchegg-2.0.8-1.x86_64 on centos 8

### ISSUE THREAD

**Issue by habom2310** [JoseExposito/touchegg#475]
I got this error when trying install touchegg on centos 8.3.2011. However I can't find any installation of the  `libstdc++.so.6(GLIBCXX_3.4.26)(64bit)` available for centos 8 yet. Is there any way to solve this problem? Thanks

**Comment by JoseExposito** [comment]
I usually test on Fedora, but it looks like CentOS has some trouble finding `libstdc++` and probably `pugixml-devel`?

I'd like to spend some time in the RPM package, but for the moment you can try to compile Touchégg yourself: 
https://github.com/JoseExposito/touchegg/blob/master/HACKING.md

**Comment by JoseExposito** [comment]
Hi @habom2310 

I just released [v2.0.9](https://github.com/JoseExposito/touchegg/releases/tag/2.0.9), including a package compatible with Centos 8/RHEL 8.

Remember to enable the EPEL repo:

```
$ sudo dnf install epel-release
```

Let me know if you find any problem.
