### ISSUE TITLE
Keep getting Ubuntu 20.04 Internal Error, touchegg crashed with SIGABRT

### ISSUE THREAD

**Issue by koshyviv** [JoseExposito/touchegg#476]
### Describe the bug

I keep getting `Sorry Ubuntu 20.04 has experienced an internal error`, every time i start my system. There are details provided, but i was not able to copy them - if there's a better way to extract the dump please let me know.

### Logs

Attaching screenshots of the error messages.
https://imgur.com/yfBjDeQ
https://imgur.com/UycShYL

```
$ touchegg --debug

```

### Your environment

 * Version of Touchégg: 2.0.8
 * Operating System: Ubuntu 20.04
 * Desktop Environment: Gnome

**Comment by JoseExposito** [comment]
I can read at the end of your second log: "gdm-wayland-session". Are you on Wayland? Touchégg doesn't work on Wayland.

You can check it in Settings - About - Windowing system

**Comment by koshyviv** [comment]
I'm on x11

https://imgur.com/lEuGuMY

**Comment by JoseExposito** [comment]
Great, thanks for checking it.

I can not see any relevant information in your log. The easiest way to get a crash log is to install `systemd-coredump`:

```bash
$ sudo apt install systemd-coredump
```

And once the crash happens again, execute:

```bash
$ sudo coredumpctl debug /usr/bin/touchegg
```

(type "quit" to exit)

That'll print a log of the crash, hopefully we'll see some useful information there.

**Comment by koshyviv** [comment]
Thanks, I'll get the information for you.

Also, I missed to mention - Touchégg is generally working fine for me, its just that these messages keep coming often.

**Comment by sidevesh** [comment]
Facing this too intermittently on Ubuntu 21.04 with Gnome 40 and X11 gestures plugin
