### ISSUE TITLE
Touchegg only executes command when debug client is connected

### ISSUE THREAD

**Issue by chgardener** [JoseExposito/touchegg#483]
### Describe the bug

Touchegg worked fine, then gestures did not result in keystrokes or commands. I checked here and read about the debug client. As soon as I turn on the debug client, all gestures work fine. When I kill that process or terminal window, it stops working again. 

I recently installed gnome-network-displays from source to stream my desktop using wifi direct, could this interfere with touchegg?

### Expected behaviour
Gestures should work without connecting the debug client

### Actual behaviour

Touchegg only works with a connected debug client running

### Logs

If required, include logs of the bug:

```
$ touchegg --debug

```

### Your environment

 * Version of Touchégg: 2.0.9
 * Operating System: Ubuntu 20.04
 * Desktop Environment: Gnome

**Comment by JoseExposito** [comment]
You need to make sure that, after restart, in GNOME System Monitor a process with name `touchegg` is being run by your user (in my case "jose"):

![Screenshot from 2021-04-13 08 37 56](https://user-images.githubusercontent.com/1335948/114507613-a3c82480-9c33-11eb-9ec9-6659cab138b3.png)

For your description I believe that the problem is that the client is not being executed on startup or that for some reason it crashed.

**Comment by chgardener** [comment]
Hm, the client is running: 
![Screenshot from 2021-04-13 12-24-39](https://user-images.githubusercontent.com/69203903/114538126-4cd24780-9c53-11eb-8f26-a622a2b7ebd9.png)
The problem persists...

**Comment by JoseExposito** [comment]
Interesting. What happens if you run `touchegg` in the command line? It should exit reporting than another instance is running:

```
$ touchegg
Touchégg v2.0.9.
Starting Touchégg in client mode
terminate called after throwing an instance of 'std::runtime_error'
  what():  Another instance of Touchégg is already running. If you are sure that Touchégg is not already running, delete the lock file with the following command and try again:
$ rm /home/jose/.config/touchegg/.touchegg.lock
```

Because you didn't reported this, I though you client wasn't running.


Could you run `touchegg --debug` and attach the logs when you try to perform one of the gestures that aren't working, please?
Also, it'd be nice to have a look to your config file (`~/.config/touchegg/touchegg.conf`), just in case something is wrong there.

**Comment by chgardener** [comment]
Alright, after a reboot I ran touchegg in the command line with the following output:
```
Touchégg v2.0.9.
Starting Touchégg in client mode
terminate called after throwing an instance of 'std::runtime_error'
  what():  Another instance of Touchégg is already running. If you are sure that Touchégg is not already running, delete the lock file with the following command and try again:
$ rm /home/richard/.config/touchegg/.touchegg.lock
Aborted (core dumped)
```
I then usually delete the .lock file and run the debog client. Then everything works. As soon as I stop the debug client, no gestures are recognized (or no commands are executed, not sure).

For example, a 4 finger swipe I use to start/show the onboard keyboard results in the following:

```Touchégg v2.0.9.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/richard/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 4
		Type: SWIPE
		Direction: LEFT
	Gesture performed on app: Gnome-terminal
	Action configured for this gesture
	Starting action
Gesture update detected (2.60142%)
Gesture update detected (0%)
Gesture update detected (6.22484%)
Gesture update detected (3.5305%)
Gesture update detected (0.867142%)
Gesture update detected (6.19387%)
Gesture update detected (7.55652%)
Gesture update detected (4.73831%)
Gesture update detected (10.4986%)
Gesture update detected (10.096%)
Gesture update detected (11.9232%)
Gesture update detected (8.67142%)
Gesture update detected (15.0201%)
Gesture update detected (14.2149%)
Gesture update detected (16.5686%)
Gesture update detected (19.3558%)
Gesture update detected (18.0861%)
Gesture update detected (12.6665%)
Gesture update detected (23.4438%)
Gesture update detected (21.0901%)
Gesture update detected (16.6615%)
Gesture update detected (21.8644%)
Gesture update detected (25.1781%)
Gesture update detected (20.5946%)
Gesture update detected (27.4079%)
Gesture update detected (25.6426%)
Gesture update detected (29.1731%)
Gesture update detected (24.4658%)
Gesture update detected (31.4029%)
Gesture update detected (29.5138%)
Gesture update detected (33.1991%)
Gesture update detected (35.6147%)
Gesture update detected (33.7876%)
Gesture update detected (28.3989%)
Gesture update detected (40.2292%)
Gesture update detected (37.2871%)
Gesture update detected (32.363%)
Gesture update detected (38.402%)
Gesture update detected (41.6538%)
Gesture update detected (36.389%)
Gesture update detected (45.0294%)
Gesture update detected (43.2022%)
Gesture update detected (46.0824%)
Gesture update detected (40.384%)
Gesture update detected (49.9226%)
Gesture update detected (48.0025%)
Gesture update detected (50.4491%)
Gesture update detected (54.8157%)
Gesture update detected (52.7098%)
Gesture update detected (44.441%)
Gesture update detected (59.7708%)
Gesture update detected (54.8777%)
Gesture update detected (48.5909%)
Gesture update detected (57.3242%)
Gesture update detected (59.3992%)
Gesture update detected (52.8647%)
Gesture update detected (64.8808%)
Gesture update detected (62.0006%)
Gesture update detected (64.1065%)
Gesture update detected (57.0146%)
Gesture update detected (70.3004%)
Gesture update detected (68.9997%)
Gesture update detected (76.0917%)
Gesture update detected (61.2574%)
Gesture update detected (73.9548%)
Gesture update detected (65.5931%)
Gesture update detected (78.8789%)
Gesture update detected (70.1146%)
Gesture end detected```

Here is my config file: (created with Touché)
[touchegg.zip](https://github.com/JoseExposito/touchegg/files/6316851/touchegg.zip)

**Comment by JoseExposito** [comment]
Hi! Usually, when you get the first error message ("Another instance of Touchégg is already running...") is because Touchégg is already running. My understanding is that, at that point, gestures doesn't work, right? 

Would you mind to attach the output of this command after a restart? Just to make sure it is running:

```
$ ps -aux | grep touchegg
```

In case it is not running, it is because it crashed. The easiest way to get a crash log is to install systemd-coredump:

```
$ sudo apt install systemd-coredump
```

And once the crash happens again, execute:
```
$ sudo coredumpctl debug /usr/bin/touchegg
```
(type "quit" to exit)

-----------------

It is normal that if you kill the process gestures doesn't work, just run Touchégg like this and close the terminal without killing the process:

```
(touchegg --debug &) &
```

Your config file wasn't uploaded, but it seems to be fine, the problem should be something else.

**Comment by chgardener** [comment]
Hey! Sorry for the delay, work kept me busy. After a restart, '$ ps -aux | grep touchegg' yields the following:

`root        1142  0.1  0.1 334688 15164 ?        Ssl  11:25   0:07 /usr/bin/touchegg --daemon
richard     2494  0.0  0.1 194640 14620 ?        Sl   11:25   0:00 touchegg
richard    12103  0.0  0.0   9380  2796 pts/0    S+   12:55   0:00 grep --color=auto touchegg
`

So I guess it is running, but gestures do not work. After typing this command I connected the debug client and everything works fine again. 
I'm skipping the coredump because touchegg has not crashed.

**Comment by iamjackg** [comment]
Interesting, I'm actually seeing the same behaviour. Things only work when I have the debug client connected.

**Comment by JoseExposito** [comment]
But... Do you need to set the `--debug` flag to make it work? Or just running `touchegg` works?

Honestly, I don't know what's going on. The process is running, I'm not sure why it is not working...

**Comment by chgardener** [comment]
Ok, my touchegg is run as a service, so I edited the touchegg.service. the command used to be `touchegg --daemon`. I tried it without any arguments and with the debug argument. None work. Interestingly, when I run touchegg using anything but the --daemon argument, not even connecting the debug client makes it work.

**Comment by iamjackg** [comment]
I'll double check tonight that the client is actually running. I strongly suspect that's the issue, but it might be my fault. I'll report back soon!

**Comment by iamjackg** [comment]
You were absolutely right -- for some reason the `touchegg.desktop` service was not running. I started it and everything works now. 

I definitely did not notice the line in the README that says:
> Run Touchégg manually by running the command `touchegg` or reboot to get started.

**Comment by chgardener** [comment]
Oh cool, thanks for the explanation. I tried adding the --debug argument in /etc/xdg/autostart/touchegg.desktop. Indeed didn't change the behaviour, except even connecting the debug client doesn't make touchegg work anymore.

**Comment by chgardener** [comment]
Hey, by the way I changed from Ubuntu to Manjaro (Arch base) and the error still ocurred. On a vanilla system, touchegg works fine, but when I install onboard (on screen keyboard) and use it maybe two times, touchegg stops working and is only fixed by connecting the debug client. 

Hope this helps.
