### ISSUE TITLE
Doesn't work on Fedora 34

### ISSUE THREAD

**Issue by nagayev** [JoseExposito/touchegg#485]
### Describe the bug

I ran touchegg by typing `ttouchegg`.
Then I swiped right with three fingers (GNOME 's default gesture) and touchegg crashed.
So what I need to do? Should I disable some GNOME components?

### Logs

<details>
<summary>Log</summary>
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = long unsigned int; _Alloc = std::allocator<long unsigned int>; std::vector<_Tp, _Alloc>::reference = long unsigned int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
</details>

### Your environment

 * Version of Touchégg: 2.0.9
 * Operating System: Fedora 34
 * Desktop Environment: Gnome 40

**Comment by JoseExposito** [comment]
Hi,

Make sure you are not using the Wayland session:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

If your hardware allows you to run Wayland, GNOME 40 already comes with multi-touch gestures out of the box, so you probably will not need Touchégg. If you are on X11, have a look to https://github.com/JoseExposito/gnome-shell-extension-x11gestures as well :wink:

**Comment by nagayev** [comment]
@JoseExposito Yes, I'm using Wayland, but have possibility to use X11 session.
Thanks.
