### ISSUE TITLE
renaming arm64 to set apart from amd64

### ISSUE THREAD

**Issue by cuvtixo** [JoseExposito/touchegg#486]
This might be low-priority, but I think its worth noting:
as is, touchegg_2.0.9_amd64.deb and touchegg_2.0.9_arm64.deb look too much alike and may cause some confusion. Ideally, downloaders would look carefully at each file. But, experience tells me this is often not the case.

### Describe the solution you'd like
I personally feel that simple capitalization of the name is a good solution. Maybe (for the next release) touchegg_2.0.10_ ARM64.deb and touchegg_2.0.10_ARMhf.deb  I'm assuming the ARM packages are much less often downloaded, as of now ARM is mainly for smartphones and tablets which don't have touchpads. Maybe this will change and laptops manufacturers will follow Apple in the future, but for now, re-labeling the ARM offerings seems least disruptive.

### Describe alternatives you've considered

The "arm" releases could also be left alone and amd64 changed to AMD64. I don't really understand why the RPM is x86_64 when the DEB is amd64, maybe that was also for readability and differentiation?  There are quite a few different ways to handle the amd64/arm64 situation. It could also be arranged so that armhf is put between amd64 and arm64. I think JoseExposito may be the only one in position to determine what solution, if any, is best.

Of course, there's no emergency here, perhaps mistaking the two is rare, and/or can be considered the downloaders' responsibility, anyways. I just came close to trying to install the wrong package, and I thought a solution would be easy enough to implement. Thank you for your time.

**Comment by JoseExposito** [comment]
Hi, and thank for creating a feature request.

Saying no to this one, not because the name is not confusing (it is) but rather because the naming used follows the standard. On Debian/Ubuntu, architectures are amd64/arm64/armhf and on Fedora/RHEL it is x86_64, so I prefer to follow the platform standard.
