### ISSUE TITLE
Error connecting to daemon

### ISSUE THREAD

**Issue by J0hnnyb0y86** [JoseExposito/touchegg#488]
### Describe the bug

cant use touchegg

### Expected behaviour

when i run touchegg the terminal get  conenction to demon but touchegg isnt a service

### Actual behaviour

Tell us what happens instead.

### Logs

If required, include logs of the bug:

Touchégg v2.8.9.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/johnnyboy/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...

### Your environment

 * Version of Touchégg: 2.8.9on
 * Operating System: MX Linux
 * Desktop Environment: KDE

**Comment by JoseExposito** [comment]
Hi,

It looks like the daemon is not running. Could you attach the output of this commands please?

```
$ sudo systemctl status touchegg
```

```
$ journalctl -u touchegg -b -f
```

How did you installed Touchégg? Make sure to use one of the officially supported installers please, otherwise, the daemon/service might not be installed.
