### ISSUE TITLE
[Help/Feature Request] Opposite Keys & Modifiers on Repeat Commands

### ISSUE THREAD

**Issue by Brin-o** [JoseExposito/touchegg#495]
Not sure if this is somehow available yet so marking this as Help & Feature request.

I am trying to use three-finger-swiping to the left/right as a way to switch between windows with alt-tab ala Windows 10.

I am able to enable this on both left/right swipes and it works fine, however if I am mid gesture and pivot the gesture to go in the other direction that gesture will not trigger. I'm assuming I could achieve this by using "Opposite keys". While this cancels the alt tab behavior it does not trigger it in the opposite way.

I'm unsure if this is possible to set using the config file but I'm trying to set it up like this and it does not work for me:
![image](https://user-images.githubusercontent.com/49071768/119257102-18439b00-bbc4-11eb-8fd2-33217cf57ff4.png)

**Comment by JoseExposito** [comment]
Hi!

There is an example available here:
https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys

This is how it looks in Touché:
![image](https://user-images.githubusercontent.com/1335948/119269377-b0a74300-bbf7-11eb-8491-9454c7a5450a.png)

**Comment by Brin-o** [comment]
Fantastic, this works perfectly. Thank you!

**Comment by richarddribeiro** [comment]
Hi,

Just a quick update. Now the configuration needs to be slightly different to have that working. Notice that in my case I use 4 fingers and UP/DOWN, rather than 3 fingers and LEFT/RIGHT, but the logic is the same.

In the touchegg.conf needs to be like that:
```
<gesture type="SWIPE" fingers="4" direction="UP">
      <action type="SEND_KEYS">
        <modifiers>Alt_L</modifiers>
        <keys>Shift_L+Tab</keys>
        <repeat>true</repeat>
        <animate>true</animate>
        <decreaseKeys>Tab</decreaseKeys>
      </action>
    </gesture>
```
    
```
<gesture type="SWIPE" fingers="4" direction="DOWN">
      <action type="SEND_KEYS">
        <modifiers>Alt_L</modifiers>
        <keys>Tab</keys>
        <repeat>true</repeat>
        <animate>true</animate>
        <decreaseKeys>Shift_L+Tab</decreaseKeys>
      </action>
    </gesture>
```

And in Touché appears like that:

<img width="898" height="646" alt="Image" src="https://github.com/user-attachments/assets/c7b83c7e-2a43-4918-9fd5-95572d50f264" />
