### ISSUE TITLE
Daemon touchegg-nosystemd

### ISSUE THREAD

**Issue by Ant136445** [JoseExposito/touchegg#497]
Please tell me how to run daemon touchegg-nosystemd in Artix. With /etc/xdg/autostart/touchegg.desktop the client runs, but without daemon it doesn't work?

**Comment by JoseExposito** [comment]
Hi,

I'm not an Artix user, but you can try to ask in the package comment section, hopefully @jzbor can help you:
https://aur.archlinux.org/packages/touchegg-nosystemd/
