### ISSUE TITLE
Switching to previous tabs not working in google chrome and other chromium based browsers

### ISSUE THREAD

**Issue by gandalf0151** [JoseExposito/touchegg#500]
### Describe the bug

Touchegg v2 works great. 

I mapped Ctrl+Tab to switch to next tab in google-chrome and Ctrl+Shift+Tab to switch to previous tab. 
I have added Control_L as modifier; Tab and Shift_L+Tab as Keys
But, both the gestures switches to next tab.
I also tried changing modifier to Shift_L and keys as Control_L+Tab, but that too didn't work

### Expected behaviour

In google-chrome and other browsers in general, Ctrl+Shift+Tab is keyboard shortcut for switching to previous tab. I was hoping to achieve same outcome from touchegg

### Actual behaviour

Both the keyboard shortcuts switched to next tab

### Logs

If required, include logs of the bug:

```
$ touchegg --debug

```

### Your environment

 * Version of Touchégg: v2.0.9
 * Operating System: Ubuntu 20.04
 * Window Manager: i3wm

**Comment by gandalf0151** [comment]
Alright, I should have checked for alternatives
Sorry for the trouble
I mapped those to Ctrl+PgUp/PgDown
It's working perfectly for everything else

Thanks for such an awesome product :D

**Comment by JoseExposito** [comment]
No problem at all, glad you found a solution :+1:
