### ISSUE TITLE
four finger swipe issue on Pop 21.04

### ISSUE THREAD

**Issue by tuncbkose** [JoseExposito/touchegg#507]
### Describe the bug

Four finger swiping suddenly stopped working. Looking at Touche, four finger up/down swiping is listed as "Used by GNOME".

### Expected behaviour

Four finger swiping up/down should change workspaces.

### Actual behaviour

Nothing happens.

### Logs

Running `touchegg --debug` terminates because of another instance running. I can provide logs if someone tells me an alternative way.

### Your environment

 * Version of Touchégg: 2.0.9
 * Operating System: Pop_OS 21.04
 * Desktop Environment: Gnome (with COSMIC)

I'd appreciate any guidence on trying to debug this.

**Comment by JoseExposito** [comment]
It looks like you installed the [X11 Gestures](https://github.com/JoseExposito/gnome-shell-extension-x11gestures) GNOME extension.

I guess the extension doesn't work on the modified GNOME version Pop!_OS packages. You should see a smooth one to one animation when switching desktops.

In case it doesn't work, you can uninstall the extension, open your Touchégg configuration file (placed at `~/.config/touchegg/touchegg.conf`) and delete the gestures a that have `GNOME_SHELL` as action.

Let me know if you have problems editing you config, feel free to post it here and I'll fix it for you :)

**Comment by tuncbkose** [comment]
Thank you so much. After a couple of reboots, it started working properly again. Sadly, I have no idea what happened.
