### ISSUE TITLE
Run command and send keys execute twice

### ISSUE THREAD

**Issue by MarioJim** [JoseExposito/touchegg#508]
### Describe the bug

When declaring a gesture like
```xml
    <gesture type="SWIPE" fingers="4" direction="RIGHT">
      <action type="RUN_COMMAND">
        <command>notify-send 'notif' ''</command>
        <on>begin</on>
      </action>
    </gesture>
```
the command is ran twice, once with the correct call stack:
```
RunCommand::executeAction
RepeatedAction::onGestureBegin
RunCommand::onGestureBegin
GestureController::onGestureBegin
```
and the second time with a call stack from `AnimatedAction::onGestureEnd`:
```
RunCommand::executeAction
AnimatedAction::onGestureEnd
RepeatedAction::onGestureEnd
GestureController::onGestureEnd
```
because the percentage of the gesture is greater than the threshold.

### Expected behaviour

The command should run only once.

### Actual behaviour

The command is executed twice.

### Your environment

 * Version of Touchégg: I've ran into this issue since commit 7d743c5d8e1edd5256de3d690022a6b6577681c4
 * Operating System: Arch Linux
 * Desktop Environment: i3

**Comment by JoseExposito** [comment]
Thanks for the detailed bug report.

As you pointed out, this was a bug introduced by [custom animations](https://github.com/JoseExposito/touchegg#custom-animations), and should be solved in master now. Hopefully it wasn't released, so no need to tag a stable build.

**Comment by MarioJim** [comment]
Thank you for the help! And thanks for the amazing software!
