### ISSUE TITLE
Error while compiling source code in 32bit machine ( please make new release for 32 bit )

### ISSUE THREAD

**Issue by oreosec** [JoseExposito/touchegg#511]
i try compiling source code with my 32bit machine and that's happen:

```
$ sudo make install

[  2%] Linking CXX executable touchegg
/usr/bin/ld: CMakeFiles/touchegg.dir/src/daemon/daemon-client.cpp.o: undefined reference to symbol 'g_signal_connect_data'
/usr/bin/ld: /lib/i386-linux-gnu/libgobject-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/touchegg.dir/build.make:733: touchegg] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/touchegg.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by JoseExposito** [comment]
Make sure you installed GLib. Depending on your distro the package could be similar to `libglib2.0-dev` or `glib2-devel`. For more details:
https://github.com/JoseExposito/touchegg/blob/master/HACKING.md#compilation

Let me know if that solved the issue :D

**Comment by oreosec** [comment]
yes sure.. i has been install it ... i was follow step by step from your instruction on HACKING.md but it's still error

**Comment by JoseExposito** [comment]
Do you mind to test with this branch? https://github.com/JoseExposito/touchegg/pull/513

In your `touchegg` directory:

```
$ git pull
$ git checkout add-gio
```

And follow the compilation steps, please.

If that doesn't work, please add more information about your system so I can test in a virtual machine.

**Comment by oreosec** [comment]
SOLVED!!! appreciate it
