### ISSUE TITLE
Ubuntu 21.04 gestures not detected

### ISSUE THREAD

**Issue by jordan-huitema** [JoseExposito/touchegg#514]
### Describe the bug

I updated to 21.04 today and found my touchegg gestures wouldnt work, i rebooted and they worked fine but my tile gestures would run but wouldnt effect windows.

I shutdown and my gestures wouldnt work at all, only native gestures worked, after rebooting i got the same as before.

I reinstalled using flatpack and now they dont work at all.

I tired running touchegg --debug and found that my commands are being registered but the built in commands are crashing touchegg and by custom command:
```bash
dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.show();'
```
I just dosnt run or dosnt have any effect.

I suspect this has to do with the new native touch and gesture support on 21.04
[21.04 touch gestures](https://help.ubuntu.com/stable/ubuntu-help/touchscreen-gestures.html.en)

Hope its an easy fix, i love this app.

### Expected behaviour

Gesture input detected.
Selected or moused over window effected by tile command.

### Actual behaviour

Input is not detected

### Logs

```bash
jordan@jordan-laptop:~$ sudo touchegg --debug

Touchégg v2.0.11.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/usr/share/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: LEFT
	Gesture performed on app: 
	Action configured for this gesture
	Starting action
Segmentation fault

jordan@jordan-laptop:~$ 

```

### Your environment

 * Version of Touchégg: 2.0.11
 * Operating System: Ubuntu 21.04
 * Desktop Environment: Gnome

**Comment by JoseExposito** [comment]
Are you running the Wayland session? Touchégg is a X11 only tool:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

You can check it in System Settings.

**Comment by jordan-huitema** [comment]
Yeah turns out i am on wayland, weird it was working for a bit before. Ill look into switching, thanks for the help.
