### ISSUE TITLE
touchegg crashing

### ISSUE THREAD

**Issue by csetera** [JoseExposito/touchegg#516]
### Describe the bug

Recently, touchegg has stopped functioning.  It appears to be crashing according to logs

### Logs

```
./apport.log:ERROR: apport (pid 17766) Sun Aug 22 13:28:01 2021: executable: /usr/bin/touchegg (command line "touchegg")
./apport.log:ERROR: apport (pid 17766) Sun Aug 22 13:28:01 2021: wrote report /var/crash/_usr_bin_touchegg.1000.crash
```
```
./syslog:Aug 22 13:27:57 XPS-15-9500 touchegg.desktop[8201]: Connection with Touchégg daemon lost Underlying GIOStream returned 0 bytes on an async read
./syslog:Aug 22 13:27:57 XPS-15-9500 touchegg.desktop[8201]: Connecting to Touchégg daemon...
./syslog:Aug 22 13:27:57 XPS-15-9500 touchegg.desktop[8201]: Error connecting to Touchégg daemon: Error receiving data: Connection reset by peer
./syslog:Aug 22 13:27:57 XPS-15-9500 touchegg.desktop[8201]: Reconnecting in 5 seconds...
./syslog:Aug 22 13:28:02 XPS-15-9500 touchegg.desktop[8201]: Error connecting to Touchégg daemon: Could not connect: Connection refused
./syslog:Aug 22 13:28:02 XPS-15-9500 touchegg.desktop[8201]: Reconnecting in 5 seconds...
./syslog:Aug 22 13:28:07 XPS-15-9500 touchegg.desktop[8201]: Error connecting to Touchégg daemon: Could not connect: Connection refused
./syslog:Aug 22 13:28:07 XPS-15-9500 touchegg.desktop[8201]: Reconnecting in 5 seconds...
./syslog:Aug 22 13:28:12 XPS-15-9500 touchegg.desktop[8201]: Error connecting to Touchégg daemon: Could not connect: Connection refused
./syslog:Aug 22 13:28:12 XPS-15-9500 touchegg.desktop[8201]: Reconnecting in 5 seconds...
./syslog:Aug 22 13:28:17 XPS-15-9500 touchegg.desktop[8201]: Error connecting to Touchégg daemon: Could not connect: Connection refused
./syslog:Aug 22 13:28:17 XPS-15-9500 touchegg.desktop[8201]: Reconnecting in 5 seconds...
./syslog:Aug 22 13:28:22 XPS-15-9500 touchegg.desktop[8201]: Error connecting to Touchégg daemon: Could not connect: Connection refused
./syslog:Aug 22 13:28:22 XPS-15-9500 touchegg.desktop[8201]: Reconnecting in 5 seconds...
```

### Your environment

 * Version of Touchégg: Touchégg v2.0.9
 * Operating System: Ubuntu 21.04
 * Desktop Environment: Gnome 3.38.5; Wayland display

**Comment by JoseExposito** [comment]
Touchégg is a X11 only tool:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

Unfortunately it is not possible to make it work on Wayland.

**Comment by csetera** [comment]
I know this is closed, but hoping you will still read and respond.  I'm confused about this.  Touchegg has been working on this machine with this installation for months. (since April)   While I understand that it isn't supposed to work with Wayland, I never (explicitly) changed my windowing system.  Do you have any thoughts of what might have happened?

Finally - Is there any tool like touchegg that works for Wayland?  It seems this is the future direction for Ubuntu, so wonder where I can turn?

**Comment by JoseExposito** [comment]
Did you updated to Ubuntu 21.04 recently? Maybe they switched the session to Wayland.

Unfortunately, the stuff Touchégg does (managing windows) is the compositor's job in the Wayland world, i.e., Mutter/GNOME Shell. It is not possible for an app to manage another apps.
So no, it's not possible to create a tool like Touchégg on Wayland. I think keyboard shortcuts should work, but it is more difficult to configure your actions using only shortcuts.

**Comment by csetera** [comment]
This was not a recent update.  If it makes any difference, the only thing I was trying to do was replicate the function of the "Super" key in Ubuntu to work with 3 finger swipe to replicate (to an extent) the behavior of MacOS (which is my work environment).  My usage of Touchegg has been very light.

**Comment by JoseExposito** [comment]
On GNOME 3.38, swiping with 3 fingers up and down should smoothly switch between desktops. To open the activities view, you can pinch with 3 fingers.

On X11, in addition to Touchégg, you can use:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures

**Comment by csetera** [comment]
Thanks for the pointers.  I was able to get things working with a different Gnome extension.
