### ISSUE TITLE
Alt_L + Left/Right arrows

### ISSUE THREAD

**Issue by heqro** [JoseExposito/touchegg#517]
From the documentation, I'm trying to make Touché use 3-finger swipe left as Alt_L + Left. So far I managed to settle Alt_L as modifier, but I don't know how to tell I want to use "Left arrow key" in the Keys label.

**Comment by bruno-berchielli** [comment]
Try simply Left and Right

**Comment by heqro** [comment]
Thanks. When I tried it earlier it didn't work. (Perhaps it would be a cool gesture to have predefined, as it's substitute for going back in so many applications?)

Thank you so much again.

**Comment by JoseExposito** [comment]
Thanks for the advice @bruno-berchielli, I'm glad it's working now.
