### ISSUE TITLE
Pinch improvement 

### ISSUE THREAD

**Issue by Nikita-Presnov** [JoseExposito/touchegg#518]
### Problem

I'm always frustrated when pinch to zoom does not work for some apps(LibreOffice).
This is due to the fact that pinch uses the hotkey, and not ctrl + scroll as in these programs. And in principle, ctrl + scroll works more smoothly.

### Solution

Add the ability to routinely rewind in key-holding gestures.

**Comment by JoseExposito** [comment]
I don't know if I understood the problem properly. You want to pinch to zoom in LibreOffice, don't you? Why not doing something similar to this?
https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys

**Comment by Nikita-Presnov** [comment]
1 LibreOffice is not the only program where ctrl + = (+) and ctrl + - do not work for me (I will not name them all for sure, but I have come across more than once).
2 ctrl + scroll works smoother than this gesture, which simply "push" the buttons.
I think it would be more logical to emulate something similar, and not just keystrokes.

**Comment by JoseExposito** [comment]
Ok, that's not possible at the moment, adding it to the wishlist.

**Comment by Nikita-Presnov** [comment]
When i need to update this prorgamm to get this function?

**Comment by JoseExposito** [comment]
I'll close the issue when I manage to implement this feature and notify you, but I have to say that it's a low priority feature.

Of course, pull request are welcome in case you want to implement it yourself.

**Comment by Nikita-Presnov** [comment]
Thanks. I was thinking about doing it myself, but I'm afraid I won't have enough experience.

**Comment by Nikita-Presnov** [comment]
But why?
I though it is very interesting and useful function.

**Comment by JoseExposito** [comment]
I was thinking about this feature, and I think you can achieve control + zoom by using `xdotool`. First, install it (this command is for Ubuntu/Debian, use your distro command):

```
$ sudo apt install xdotool
```

And now add a couple of run command actions like:

![image](https://user-images.githubusercontent.com/1335948/134768457-7491d03f-eecb-4f0c-8481-869c110c4e82.png)

Or if you prefer to add it in your `~/.config/touchegg/touchegg.conf` file:

```xml
  <application name="libreoffice-writer">
    <gesture type="PINCH" fingers="2" direction="IN">
      <action type="RUN_COMMAND">
        <command>xdotool keydown ctrl click 5 keyup ctrl</command>
        <repeat>true</repeat>
        <animation>NONE</animation>
        <decreaseCommand>xdotool keydown ctrl click 4 keyup ctrl</decreaseCommand>
      </action>
    </gesture>
    <gesture type="PINCH" fingers="2" direction="OUT">
      <action type="RUN_COMMAND">
        <command>xdotool keydown ctrl click 4 keyup ctrl</command>
        <repeat>true</repeat>
        <animation>NONE</animation>
        <decreaseCommand>xdotool keydown ctrl click 5 keyup ctrl</decreaseCommand>
      </action>
    </gesture>
  </application>
```

That'll do the trick.

**Comment by Nikita-Presnov** [comment]
ЗдравствуйтеА какие новости по курсу?Просто я на карантине по ковиду, выхожу 12 октября.24.09.2021, 20:23, "José Expósito" ***@***.***>:
I'll close the issue when I manage to implement this feature and notify you, but I have to say that it's a low priority feature.
Of course, pull request are welcome in case you want to implement it yourself.
