### ISSUE TITLE
Ubuntu Mate 20.04 install with Synaptic distro package fails

### ISSUE THREAD

**Issue by hubyhuby** [JoseExposito/touchegg#519]
### Describe the bug

When installing from synaptic (the package is available in ubuntu mate aparentely ) I get the following error :
After rebooting it doesn t seem to work.
When I install Touché I don t have a way to test it (would be nice to have a play ground there) and when I switsh the  buttons to ON they come back to OFF when I return to the window (log in term says "undefined").

![ScrShot-30-août_3](https://user-images.githubusercontent.com/26340942/131351199-8fca0469-753d-480d-8400-5cd81a9f46d2.png)

### Expected behaviour

Working Touchegg on ubuntu mate

### Actual behaviour

Install process seems to fail.
### Logs

![image](https://user-images.githubusercontent.com/26340942/131350868-6e911192-2b7f-4f23-89a5-3d0670c8e1c8.png)

```
"/home/yann/.config/touchegg/touchegg.conf"  not found, copying config from  /usr/share/touchegg/touchegg.conf
Reading config from  "/home/yann/.config/touchegg/touchegg.conf"
Try to make a multitouch gesture. If everything goes well the information about the gesture must appear
[+] Avaliable gesture:
	 Name ->  Flick
[+] Avaliable gesture:
	 Name ->  Drag
[+] Avaliable gesture:
	 Name ->  Pinch
[+] Avaliable gesture:
	 Name ->  Rotate
[+] Avaliable gesture:
	 Name ->  Tap
[+] Avaliable gesture:
	 Name ->  Touch



```

### Your environment

Ubuntu mate 20.04 up to date
Thinkpad E590 bios update 2020 ish

Touché says "undefined"
![image](https://user-images.githubusercontent.com/26340942/131351729-13fdba79-6978-47bf-832a-505fcd38e5cc.png)

**Comment by hubyhuby** [comment]
Just install the .deb directely from github and it works.
The version included in Ubuntu mate 20.04 doesn t work.
Touché doesn t seems to work with this version either

**Comment by JoseExposito** [comment]
Yes, the version available in the official Ubuntu repo is too old (like 6 or 7 years old).

Unfortunately, I have not been able to get it updated.

If you experiment problems with the configuration file, delete it. It could contain keys from the old version that might not work on the new one.

By the way, if you want to receive automatic updates, you can use the PPA:
https://github.com/JoseExposito/touchegg#ubuntu-debian-and-derivatives

**Comment by hubyhuby** [comment]
Thks Jose,
I have seen the ppa...but I take it easy with ppas since it messed up my ubuntu last time...
Would be nice if you d manage one day to have it in Ubuntu.
Thks for this geeat work.
