### ISSUE TITLE
Init script is missing from .deb package

### ISSUE THREAD

**Issue by sgon00** [JoseExposito/touchegg#520]
Hi, I am running MX Linux which runs init instead of systemd and the system is based on debian 10.

After installing the .deb file, I don't find the init script to start the daemon.

Do anyone know how to write a touchegg init script in debian 10?

Thanks a lot.

**Comment by JoseExposito** [comment]
A while ago, I added a compilation flag to disable systemd: https://github.com/JoseExposito/touchegg/issues/481

You can check the [AUR package](https://aur.archlinux.org/packages/touchegg-nosystemd/) to see how it works on Arch.

Leaving the issue open so hopefully someone can help you with the init file. Said that, I have no plans to support non-systemd distros upstream.

**Comment by sgon00** [comment]
@JoseExposito 

Thanks a lot for your reply.
I have made a init script for touchpad and it's working. 
This is my first time creating a init script so I am not sure if it's good.

```
#!/bin/sh

### BEGIN INIT INFO
# Provides:          touchegg
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     5
# Default-Stop:
# Short-Description:
# Description:
### END INIT INFO

case "$1" in
    start)
	/usr/bin/touchegg --daemon
	;;

     *)
        echo "Usage: $0 start" 1>&2
        exit 3
        ;;
esac

exit 0
```

Closing this issue.
