### ISSUE TITLE
touchegg --daemon does not work

### ISSUE THREAD

**Issue by VanillaBase1lb** [JoseExposito/touchegg#521]
I am on KDE Plasma Arch. Touchegg was working fine all this time until I decided to change my global theme, for some reason after changing theme, touchegg stopped working in daemon mode. It still works if I run `touchegg` on terminal but `touchegg --daemon` does not and neither does systemd service. I have tried reinstalling from AUR multiple times. This is the output of `systemctl status touchegg`:

● touchegg.service - Touchégg Daemon
     Loaded: loaded (/usr/lib/systemd/system/touchegg.service; disabled; vendor preset: disabled)
     Active: active (running) since Tue 2021-09-07 13:44:48 IST; 16s ago
       Docs: https://github.com/JoseExposito/touchegg/tree/master/installation#readme
   Main PID: 40861 (touchegg)
      Tasks: 3 (limit: 16692)
     Memory: 2.3M
        CPU: 43ms
     CGroup: /system.slice/touchegg.service
             └─40861 /usr/bin/touchegg --daemon

Sep 07 13:44:48 nitroan51543 touchegg[40861]: Creating D-Bus server
Sep 07 13:44:48 nitroan51543 touchegg[40861]: Server started at address unix:abstract=touchegg
Sep 07 13:44:48 nitroan51543 touchegg[40861]: A list of detected compatible devices will be displayed below:
Sep 07 13:44:48 nitroan51543 touchegg[40861]: Compatible device detected:
Sep 07 13:44:48 nitroan51543 touchegg[40861]:         Name: ELAN0504:01 04F3:312A Touchpad
Sep 07 13:44:48 nitroan51543 touchegg[40861]:         Size: 101.094mm x 73.3125mm
Sep 07 13:44:48 nitroan51543 touchegg[40861]:         Calculating start_threshold and finish_threshold. You can tune this values in your service file
Sep 07 13:44:48 nitroan51543 touchegg[40861]:         start_threshold: 28.8632
Sep 07 13:44:48 nitroan51543 touchegg[40861]:         finish_threshold_horizontal: 358.206
Sep 07 13:44:48 nitroan51543 touchegg[40861]:         finish_threshold_vertical: 259.769

**Comment by JoseExposito** [comment]
The systemd service is the bit that runs the daemon (`touchegg --daemon`) and it looks like it's running: `Active: active (running)`.

The client is started by a desktop file:
https://github.com/JoseExposito/touchegg/blob/master/installation/touchegg.desktop

Both processes should be running after restarting. Could you copy and paste the output of this command, please?

```bash
$ ps -fC touchegg  
UID          PID    PPID  C STIME TTY          TIME CMD
jose        1697    1336  0 07:27 ?        00:00:00 touchegg
root        2063       1  0 07:28 ?        00:00:01 /usr/bin/touchegg --daemon
```

**Comment by VanillaBase1lb** [comment]
Oh, I did not realise that a desktop file was required, I thought just running the daemon was enough. I did actually make a desktop file and set it to autostart, I thought this was a workaround and not the correct method.
