### ISSUE TITLE
enable horizontal switch desktop animation on gnome 3.38 

### ISSUE THREAD

**Issue by rcsm17** [JoseExposito/touchegg#526]
Hello, first of all, thanks for your work... it is awesome having 1:1 gestures on X11. Anyway, I'm using Ubuntu 20.04LTS on my laptop. On the PC I run Arch Linux with Gnome40 and I really like the horizontal workspace, and, since I got used to using the horizontal workspace I add to my laptop with Ubuntu 20.04 (and Gnome 3.38) an extension that make the workspace horizontal instead of vertical. Now with that settings, the gestures didn't work properly even if I set the right configuration (swipe right and swipe left to change desktop). Indeed if I execute the horizontal gesture it switches the desktop without the animation (like if I tap the combination keys) but if I execute the vertical gesture it switches the desktop horizontally but with the correct 1:1 animation.
Please, can you add this feature or fix the behavior ?

PS. The extension to set the horizontal workspace is this: https://extensions.gnome.org/extension/2141/horizontal-workspaces/  

EDIT:
I noticed that with the horizontal workspace, if I have the mouse plugged in, in the overview, I neither can navigate through the workspace with the mouse wheel and see the workspace bar as well. Maybe it's correlated ?

**Comment by JoseExposito** [comment]
Hi,

In addition to Touchégg, are you also using the [X11 Gestures](https://github.com/JoseExposito/gnome-shell-extension-x11gestures) extension?

It looks like the horizontal workspaces extension makes some changes to the way gestures and mouse scroll is handled. If you are using [X11 Gestures](https://github.com/JoseExposito/gnome-shell-extension-x11gestures), it's out of the scope of the project to be compatible with other extensions. There are hundreds of them and it's virtually impossible to ensure compatibility.

But probably it's worth to report the mouse wheel error you are experimenting so developers are aware of the issue.

If you are just using the [change desktop action](https://github.com/JoseExposito/touchegg#switch-desktopsworkspaces-change_desktop) (an arrow is being displayed on screen), you can use the [keyboard shortcut](https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys) action instead to send Control+Alt+Left/Right to change between workspaces.
