### ISSUE TITLE
Two finger gestures

### ISSUE THREAD

**Issue by 6e622dafdae9** [JoseExposito/touchegg#528]
Hi, is it possible for touchegg to have two finger gestures so that it can be more similar to other operating systems? In MacOS, Windows and ChromeOS, two finger swipe left and right in web browsers go back and forth in the page history.

IMO it's fine to give up horizontal scrolling to get this gesture.

**Comment by JoseExposito** [comment]
Unfortunately, for technical reasons, it is not possible to do this in Touchégg, it needs to be implemented at the app level. For example, [GNOME Web](https://wiki.gnome.org/Apps/Web) implements it really well.
