### ISSUE TITLE
Changing desktop animation doesn't work

### ISSUE THREAD

**Issue by Jckpt** [JoseExposito/touchegg#531]
### Describe the bug

Changing direction and animationPosition tags doesn't change the animation when changing desktops

### Expected behaviour

Changing desktop animation should go from right to left.

### Actual behaviour

Changing desktop animation doesn't do anything for me and the animation is still from bottom to top.
I'm using [this](https://reposhub.com/javascript/misc/NayamAmarshe-ToucheggKDE.html) config file

https://user-images.githubusercontent.com/64931967/135449163-c972f7c6-06c9-4c31-a4e7-3270af55561c.mp4

### Your environment
Touchégg v2.0.11
Operating System: Manjaro Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.19-2-MANJARO (64-bit)

**Comment by JoseExposito** [comment]
For what I can see, [this is the configuration](https://github.com/NayamAmarshe/ToucheggKDE/blob/main/touchegg.conf#L57):

```xml
    <gesture type="SWIPE" fingers="3" direction="RIGHT">
      <action type="CHANGE_DESKTOP">
        <direction>previous</direction>
        <animate>true</animate>
        <animationPosition>left</animationPosition>
        <color>000000</color>
        <borderColor>000000</borderColor>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="3" direction="LEFT">
        <action type="CHANGE_DESKTOP">
            <direction>next</direction>
            <animate>true</animate>
            <animationPosition>right</animationPosition>
            <color>000000</color>
            <borderColor>000000</borderColor>
        </action>
    </gesture>
```

Changing `animationPosition` to `up` and `down` works fine here.

Could you attach your configuration file? Let's see if there is something missing in it...

**Comment by Jckpt** [comment]
[touchegg.conf.txt](https://github.com/JoseExposito/touchegg/files/7261131/touchegg.conf.txt)

**Comment by JoseExposito** [comment]
Notice that in your config `animationPosition` is set to left and right:

```xml
<gesture type="SWIPE" fingers="3" direction="RIGHT">
      <action type="CHANGE_DESKTOP">
        <direction>previous</direction>
        <animate>true</animate>
        <animationPosition>left</animationPosition>
        <color>000000</color>
        <borderColor>000000</borderColor>
      </action>
    </gesture>
```

Replace it with top and bottom and it'll work.

**Comment by Jckpt** [comment]
I'm sorry, English isn't my native language, I meant that I don't want the animation to look like this:

![example1](https://user-images.githubusercontent.com/64931967/135499927-fef1fb32-0d3e-4843-974e-773c679f1c87.png)

instead, I want it to look like this:

![animation2](https://user-images.githubusercontent.com/64931967/135500068-0f96124f-645e-43f8-ad14-f5d4fb82f1fd.png)

![animation3](https://camo.githubusercontent.com/3b32d4ac2214dad86c51199c63ba47c67b6742236b8b7302c7e947b5767b3b72/68747470733a2f2f73322e67696679752e636f6d2f696d616765732f5377697463682d4465736b746f702e676966)

**Comment by Jckpt** [comment]
okay sorry for wasting your time, all I needed to do is to edit some settings in virtual desktops. I thought that this sliding animation is integrated into touchegg, this is my second day using linux..

**Comment by JoseExposito** [comment]
Don't worry, it can be difficult to find the right settings, there are a lot of them in KDE. Welcome to Linux ;)
