### ISSUE TITLE
Crash when showing animations on manjaro-sway

### ISSUE THREAD

**Issue by jfecher** [JoseExposito/touchegg#532]
### Describe the bug

touchegg crashes possibly whenever attempting to show an animation while running on Sway wm. I've given the steps to reproduce below but have not tested on any other WM or distro.

Steps to reproduce:
1. Install touchegg and touche
2. Start+enable the touchegg service, and run `touchegg` in a terminal
3. Use touche to create an action for "global gestures: tap with 2 fingers"
    - This appears to still crash for other gestures as well, though I've only tested 2, 3 finger type, and 3 finger swipes, all global
    - "Minimize a window," "Close a window," "execute a command," and "mouse click" are the only actions that _do not_ result in a crash
    - If "Keyboard shortcut" is chosen, touchegg will only crash if an animation is chosen
4. Tap anywhere on screen with 2 fingers

### Expected behaviour

Touchegg should execute the bound action without crashing

### Actual behaviour

Touchegg crashes with a C++ bounds check while indexing a vector.

### Logs

If required, include logs of the bug:
```
$ touchegg
Touchégg v2.0.11.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/username/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Your configuration file changed, reloading your settings
Using configuration file "/home/username/.config/touchegg/touchegg.conf"
Your configuration file changed, reloading your settings
Using configuration file "/home/username/.config/touchegg/touchegg.conf"
Your configuration file changed, reloading your settings
Using configuration file "/home/username/.config/touchegg/touchegg.conf"
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = long unsigned int; _Alloc = std::allocator<long unsigned int>; std::vector<_Tp, _Alloc>::reference = long unsigned int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    128638 abort (core dumped)  touchegg
exit 134
```

Three finger touch:
```
$ touchegg --debug
Touchégg v2.0.11.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/rndmprsn/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: TAP
		Direction: UNKNOWN
	Gesture performed on app: krita
	Action configured for this gesture
	Starting action
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = long unsigned int; _Alloc = std::allocator<long unsigned int>; std::vector<_Tp, _Alloc>::reference = long unsigned int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    133683 abort (core dumped)  touchegg --debug
exit 134
```

### Your environment

- Touchegg v2.0.11
- Manjaro
- Sway

**Comment by JoseExposito** [comment]
Touchégg is a X11 only tool:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

Some actions, like running a command or shortcuts might work, but everything UI related won't.

Unfortunately, it is not possible for technical reasons to support Wayland.
