### ISSUE TITLE
Add support for more complex gestures

### ISSUE THREAD

**Issue by MiguelGuthridge** [JoseExposito/touchegg#534]
### Is your feature request related to a problem? Please describe

I'd love to be able to make more complex gestures be usable. I'm coming from Windows, where I used [GestureSign](https://gesturesign.win/#/), which allowed me to record complex gestures. Although I can set up the simpler ones (left/right change tabs, up/down open and close tabs), there aren't any options for more complex ones such as up then right (reopen closed tab) or diagonally up and left (detach tab into new window). 

### Describe the solution you'd like

It'd be great to be able to define actions for gestures that are comprised of combinations of other gestures, as well as other complex ones such as diagonal swipes. I think that this would add an entirely new dimension of fine-grained control for the software.

### Describe alternatives you've considered
I can't think of any alternatives other than not adding the gestures.

**Comment by JoseExposito** [comment]
One similar alternative on Linux is Easystroke:
https://lifehacker.com/easystroke-makes-mouse-gestures-easy-in-linux-5049268

It allows to record mouse gestures and replay them. I haven't tested it, but I think it should allow you to do something similar.

This feature is a bit out of the scope of this project, saying no to this one, sorry.
