### ISSUE TITLE
Does finger limitation exists?

### ISSUE THREAD

**Issue by oleksii-danchuk** [JoseExposito/touchegg#536]
Hi,

I cannot find any information about upper limit of fingers.
It works good with 2,3,4. 
Does it support 5 fingers?

**Comment by JoseExposito** [comment]
Hi,

You can find the docs here:
https://github.com/JoseExposito/touchegg#available-gestures

Answering your question, no, 5 fingers are not supported (on touchpads).

The easiest way to see what's available is to use Touché for configuration: https://github.com/JoseExposito/touche#readme
