### ISSUE TITLE
Add back two-finger swipes for browser navigation

### ISSUE THREAD

**Issue by coldspark29** [JoseExposito/touchegg#547]
### Is your feature request related to a problem? Please describe

I would like to use two fingers for going forward/back in browsers. I think this was possible and was removed. Why?

### Describe the solution you'd like

I would like the feature back and maybe an animation in the middle of the screen. Firefox doesn't support this out-of-the-box unfortunately.

### Describe alternatives you've considered

I considered using Chromium, but it isn't able to open the virtual keyboard. So no browser is really fully touch capcable on Linux. This feature would bring it back. Using three fingers is not intuitive and is also used for window tiling.

**Comment by JoseExposito** [comment]
Are you using a touchpad? Or a touchscreen?

With a touchpad, this is not possible:
https://github.com/JoseExposito/touchegg/blob/master/README.md#can-i-use-2-finger-swipes-for-web-browser-navigation

If you are using a touchscreen, Chrome allows to do this by swiping with one finger.

**Comment by coldspark29** [comment]
A touchpad and you could easily enable this

**Comment by JoseExposito** [comment]
How? As far as I know, this is not possible.

**Comment by coldspark29** [comment]
Why is it not possible? Can't you just change the limitation to two fingers? Is it a libinput limitation? I would be happy to file an issue there in that case

**Comment by JoseExposito** [comment]
The first issue is that 2 finger swipes are not exposed by libinput as gestures:
https://github.com/JoseExposito/touchegg#swipe

And it's fine, 2 finger swipes are used to scroll system wide.

But even if I could receive 2 finger swipes in Touchégg, I wouldn't have enough context to know if you are trying to scroll horizontally in a web page or navigating back/forward.

The browser is the one that has that context and should implement this feature. There are not technical limitations for them not to implement it.

GNOME Web for example has this feature and works really well.

**Comment by coldspark29** [comment]
Okay, thank you for making that clear. It is really a pity that there is no browser on Linux that supports all touch inputs. Chrome does the swiping but doesn't recognize if you click in a text field. Firefox does recognize that and has lately gotten basic touchscreen gestures without visual feedback, but none for the trackpad. I will not use GNOME Web or Konqueror because they are not good for other reasons.
