### ISSUE TITLE
touchegg (202110210918-stable-2.0.12~ubuntu20.04.1) cannot maximize or minimize windows

### ISSUE THREAD

**Issue by compilebunny** [JoseExposito/touchegg#548]
It appears that touchegg (202110210918-stable-2.0.12~ubuntu20.04.1) cannot maximize or minimize windows.

The system is ubuntu Mate 20.04.1.

An appropriate touchegg configuration file has been created. 

touchegg --debug shows that touchegg is detecting the gestures and attempting the action. However, maximization or minimization do not occur.

Changing touchegg.conf to reference the keyboard shortcuts for maximization or minimization is an effective workaround.

**Comment by JoseExposito** [comment]
It could be a problem with your window manager. Under the hood, Touchégg does something similar to this command:

```bash
$ sudo apt install wmctrl # In case it is not already installed
$ wmctrl -r :ACTIVE: -b toggle,maximized_vert,maximized_horz
```

Does the second command maximize or restore the active window?

**Comment by compilebunny** [comment]
wmctrl -r :ACTIVE: -b toggle,maximized_vert,maximized_horz

The command above does maximize the active window

**Comment by JoseExposito** [comment]
The problem should be somewhere else then. Could you verify that it is not a duplicate of https://github.com/JoseExposito/touchegg/issues/542, please?

Also, could you attach the output of `touchegg --debug` and `libinput --version`, please?

**Comment by compilebunny** [comment]
Given the timing and that both of us are using the same OS, I would be surprised if it were not related. However, I am not sure of how to verify whether this bug has the same root cause.

$ libinput --version
1.15.5

touchegg --debug with action set to keyboard shortcut (successful minimize)

Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: DOWN
	Gesture performed on app: Firefox
	Action configured for this gesture
	Starting action
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture end detected


touchegg --debug with action set to minimize (minimize does not occur)

Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: DOWN
	Gesture performed on app: Mate-terminal
	Action configured for this gesture
	Starting action
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture end detected

**Comment by JoseExposito** [comment]
Ok, the problem is that 0%. Probably meaning that the size of your touchpad is unknown and Touchégg is falling back to the default size. You can find more information here:
https://github.com/JoseExposito/touchegg#daemon-configuration

Let me know if you see this log:

```
$ journalctl -u touchegg -b
[...]
It wasn't possible to get your device physical size, falling back to default start_threshold and finish_threshold. You can tune this values in your service file:
https://github.com/JoseExposito/touchegg#daemon-configuration
```

If so, you can configure the thresholds as explained in the readme.
