### ISSUE TITLE
Unable to change 4 finger gestures up and down (Used by GNOME error)

### ISSUE THREAD

**Issue by naheedroomy** [JoseExposito/touchegg#550]
### Describe the bug

i am unable to change 4 finger gestures up and down. Option is greyed out and says used by GNOME.

### Expected behaviour

I should be able to change all these options. AFAIK it used to work before and then it suddenly didnt.

### Actual behaviour

Option to change gestures for 4 finger up and down is grayed out.

### Your environment

 * Version of Touchégg: 2.0.9
 * Operating System: PopOS - 21.04
 * Desktop Environment: Gnome 3.38.5

**Comment by JoseExposito** [comment]
You are using this GNOME Shell extension in order to be able to use multitouch gestures on X11:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures

If you don't want to use the default GNOME gestures, you can remove the extension and edit your config file manually.
