### ISSUE TITLE
Allow overriding threshold on a per-action basis

### ISSUE THREAD

**Issue by iamkroot** [JoseExposito/touchegg#553]
### Is your feature request related to a problem? Please describe

The `action_execute_threshold` is currently a global setting that applies to all actions. However, some actions would benefit from a custom amount that is more appropriate. 

For example, I've configured 3-finger horizontal swipes for switching between windows on KDE using `send_keys` with `repeat=true`. My global threshold is `20%`, but I've found that this is causing jank, since the repeat steps are `10%`, meaning the action execution always starts by skipping the neighbouring window.

### Describe the solution you'd like

We should be able to specify the `action_execute_threshold` for each action, overriding the global value.

Considering that each `Action` already [contains](https://github.com/JoseExposito/touchegg/blob/5166e312e5be2dd463a3688cfee6fb7c999bb5c5/src/actions/action.h#L70) the `threshold` member, it seems like the only change will have to be in passing the proper value in the constructor.

### Describe alternatives you've considered

I _could_ reduce the global setting to `10%`, but this would impact other actions such as maximize or show desktop which I would like to have a high threshold for.

**Comment by JoseExposito** [comment]
> meaning the action execution always starts by skipping the neighbouring window

It shouldn't behave like that. I have the same action configured (elementary OS) with the same 20% threshold and no window is skipped. Here is my config:

![image](https://user-images.githubusercontent.com/1335948/147495118-e2ae3110-ce54-4abe-b6be-f742a5565527.png)

Do you mind to share your `touchegg.conf` file? Let's see if there is something wrong there...

**Comment by TomiOhl** [comment]
While I don't have the issue the op pointed out, I would appreciate being able to configure thresholds on a per-gesture level: I'm using three finger swipe for the very same purpose as you on Elementary 6.1. Since the new window switcher I constantly find myself swiping too much initially and a setting like this could solve my problem.

Also, the quick window switcher sometimes gets stuck on the screen after using this gesture and only clicking an icon on it makes it go away. Not sure if I should open a new issue here or in elementary/gala. I think I only get it when using the gesture, not with alt+tab.

**Comment by JoseExposito** [comment]
@TomiOhl I think the issue with elementary's window switcher could be related to https://github.com/elementary/gala/issues/1307

See my comment for a workaround.

**Comment by TomiOhl** [comment]
Thanks, but that does not seem to solve my problem. Still getting it randomly.
I had a different shortcut set for layout switching. An hour ago I switched it to disabled but the issue remained.
Note that alt + shift + tab works for me, that's another detail that's different.

**Comment by iamkroot** [comment]
> It shouldn't behave like that. I have the same action configured (elementary OS) with the same 20% threshold and no window is skipped

Huh, you're right. I just retried it in debug mode, and saw that the action does get started at 10% even if the threshold is set to 20%.

I guess my main issue is that the touchpad is too sensitive, so I'm hitting 20% with the normal swipes, making me think it skipped over one window. Is it possible to tweak this via the config?

**Comment by JoseExposito** [comment]
> I guess my main issue is that the touchpad is too sensitive, so I'm hitting 20% with the normal swipes, making me think it skipped over one window. Is it possible to tweak this via the config?

No, but we can add a config option :)

**Comment by JoseExposito** [comment]
Hi, I just added a new option to configure this behavior: `times`.

As an example, the Alt+Tab action would look like this:

```xml
<gesture type="SWIPE" fingers="3" direction="LEFT">
  <action type="SEND_KEYS">
    <repeat>true</repeat>
    <modifiers>Alt_L</modifiers>
    <keys>Shift_L+Tab</keys>
    <decreaseKeys>Tab</decreaseKeys>
    <times>8</times>
  </action>
</gesture>

<gesture type="SWIPE" fingers="3" direction="RIGHT">
  <action type="SEND_KEYS">
    <repeat>true</repeat>
    <modifiers>Alt_L</modifiers>
    <keys>Tab</keys>
    <decreaseKeys>Shift_L+Tab</decreaseKeys>
    <times>8</times>
  </action>
</gesture>
```

You can compile and test the latest code, hopefully it'll fix your issue :)

**Comment by iamkroot** [comment]
Awesome! Just tested it out - fixed the sensitivity issue perfectly. Thanks a lot for the quick resolution!

I do have a slight suggestion; the `times` name might probably confuse people. I had to look at the commit to understand what exactly that value means. Maybe better to rename it to something like `repeat_sensitivity_inverse`?

**Comment by JoseExposito** [comment]
Cool, thanks for testing it!

> I do have a minor suggestion; the times name will probably confuse people. I had to look at the commit to understand what exactly that value means. Maybe better to rename it to something like repeat_sensitivity_inverse?

How I read it is: repeat - true, times - X. But it's true that it can be confusing.
Since the config name wasn't published yet, we can change it, but repeat_sensitivity_inverse is a bit confusing, because the config affect both directions, not only inverse one.

**Comment by iamkroot** [comment]
By `inverse`, I mean that the value goes in the denominator when calculating the step. Increasing this value will decrease the sensitivity, and hence the inverse relation.
But I guess we can just call it `repeat_sensitivity_factor`, and mention this inverse relation in the docs.
