### ISSUE TITLE
Add animation for volume control

### ISSUE THREAD

**Issue by FrixBOX** [JoseExposito/touchegg#556]
### Is your feature request related to a problem? Please describe

when i use three finger swipe for controlling my volume. sometimes i can't really tell whether it really works or not

### Describe the solution you'd like

trigger animation for increasing/decreasing volume like when you use FN+F2/F3 to control volume

**Comment by JoseExposito** [comment]
Hi!

Your desktop environment should be the one performing the animation when the volume changes. For example, elementary OS shows a nice animation:

![Screenshot from 2022-01-08 12 33 28](https://user-images.githubusercontent.com/1335948/148642589-e6701270-92ae-49db-8930-c75d0022f3b6.png)


This feature is out of the scope of the project, try to request the feature to your DE developers, maybe they are wiling to implement it.
