### ISSUE TITLE
[action] Used by GNOME 

### ISSUE THREAD

**Issue by spantheslayer** [JoseExposito/touchegg#557]
Installed the touchegg and it was working fine on the first boot but after trying to tweak here and here and doing a reboot, it is showing some like the below picture. can anyone help on this?

$ touchegg --debug
 ```

Touchégg v2.0.12.
Starting Touchégg in client mode
terminate called after throwing an instance of 'std::runtime_error'
  what():  Another instance of Touchégg is already running. If you are sure that Touchégg is not already running, delete the lock file with the following command and try again:
$ rm /home/spantheslayer/.config/touchegg/.touchegg.lock
[1]    3239 abort (core dumped)  touchegg --debug
```
![Screenshot from 2022-01-13 22-24-13](https://user-images.githubusercontent.com/61844611/149374917-0b148898-6570-456a-8096-17a49a82e970.png)

**Comment by JoseExposito** [comment]
This is a know bug in the GNOME Shell [X11 Gestures](https://github.com/JoseExposito/gnome-shell-extension-x11gestures) extension.

In order to fix it, open your config file (`~/.config/touchegg/touchegg.conf`) and remove all the "used by GNOME" actions.

**Comment by geekfish69** [comment]
Thanks, this solved the issue.
