### ISSUE TITLE
Please support debian in PPA

### ISSUE THREAD

**Issue by szekelyisz** [JoseExposito/touchegg#559]
### Is your feature request related to a problem? Please describe

The PPA doesn't work with debian, only ubuntu.

### Describe the solution you'd like

The PPA to provide a repository for debian.

### Describe alternatives you've considered

Installing the package directly with dpkg works, but it won't give you updates.

**Comment by JoseExposito** [comment]
I might be wrong, but as far as I know, PPAs are Ubuntu only. Unfortunately, I can't select Debian on launchpad, this is not possible.
