### ISSUE TITLE
Endevour OS - Touchegg working just when running touchegg in console.

### ISSUE THREAD

**Issue by Raduc4** [JoseExposito/touchegg#560]
### Describe the bug
Hello, 
I'm using endevour os (arch) with Gnome, i had installed gnome extension and also touchegg from AUR. Unfortunately It doesn't work. It works just when i run touchegg in console. I'd like to make it working at boot. Also, when i swipe down with 3 fingers inside an app the app disapears for  a second from the top-left menu but it appears again after.
![image](https://user-images.githubusercontent.com/55291600/151127124-e9e01c34-c96a-4d8e-bf88-acc93469df1d.png)

### Logs

If required, include logs of the bug:

```
$ touchegg --debug

r@rnbook ~]$ touchegg --debug
Touchégg v2.0.13.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/usr/share/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: DOWN
	Gesture performed on app: jetbrains-webstorm
	Action configured for this gesture
	Starting action
Gesture update detected (13.2238%)
Gesture update detected (20.276%)
Gesture update detected (27.3283%)


```
```
systemctl status touchegg

[r@rnbook ~]$ systemctl status touchegg
● touchegg.service - Touchégg Daemon
     Loaded: loaded (/usr/lib/systemd/system/touchegg.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2022-01-26 10:05:21 EET; 9min ago
       Docs: https://github.com/JoseExposito/touchegg/tree/master/installation#readme
   Main PID: 399 (touchegg)
      Tasks: 4 (limit: 9369)
     Memory: 18.1M
        CPU: 3.100s
     CGroup: /system.slice/touchegg.service
             └─399 /usr/bin/touchegg --daemon
```

### My environment

 * Version of Touchégg: Touchégg v2.0.13.
 * Operating System: Arch Linux...
 * Desktop Environment: Gnome

**Comment by Raduc4** [comment]
```
[r@rnbook ~]$ touchegg --debug --daemon
Touchégg v2.0.13.
Starting Touchégg in daemon mode
Starting daemon server...
Generating D-Bus introspection data
Creating D-Bus server
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error creating D-Bus server: Error binding to address (GUnixSocketAddress): Address already in use
Aborted (core dumped)
[r@rnbook ~]$ 
```

**Comment by JoseExposito** [comment]
The Arch package is suppose to create a `desktop` file in `/etc/xdg/autostart` that should run the client (just `touchegg`, without the daemon flag) on session start.

Make sure that the file was properly installed and if it is not there, reinstall or add `touchegg` to your start up program. If I remember correctly you can do it from GNOME settings.

Let me know if that worked :)

**Comment by Raduc4** [comment]
Hello, thank you for the replay.

I discovered that Touchegg doesn't work on my machine that uses Wayland.

**Comment by JoseExposito** [comment]
Ok, yes, it was probably crashing on the background. The good news is that GNOME has gestures out of the box on Wayland.
