### ISSUE TITLE
Doesn't work anymore since nvidia-drv 510.47 update

### ISSUE THREAD

**Issue by neonicoo** [JoseExposito/touchegg#563]
touchegg doesn't work since I updated the nvidia driver to 510, same issue on several distros.

 * Version of Touchegg: v2.0.13.
 * Operating System: Ubuntu 20.04, Fedora, 35  & Arch Linux
 * Desktop Environment: Gnome 41 & Gnome 3.36

**Comment by JoseExposito** [comment]
Could you expand a bit more, please? Attach logs and the other information requested in the bug report template, otherwise I won't be able to help you.
