### ISSUE TITLE
Problems using it in openSUSE Leap 15.3

### ISSUE THREAD

**Issue by Freemason-12** [JoseExposito/touchegg#568]
I'm on openSUSE leap 15.3 and as an official package there is only 1.1.1 version available which I can't get to work. Is there a way to install recent version of touchegg on Leap or get the old one to work?

**Comment by JoseExposito** [comment]
Hi! I'm afraid the version available in leap is too old. You can use the official COPR repo instead:
https://github.com/JoseExposito/touchegg#fedora-centos-rhel-and-derivatives
