### ISSUE TITLE
Consider releasing a flatpak package

### ISSUE THREAD

**Issue by axtux** [JoseExposito/touchegg#574]
Hello,

I am using an OS that does not offer the touchegg package. Right now, I download source code, compile it and install manually. To make things easier for me but also for any potential user, you could consider releasing a flatpack package. As there is already a Touché package in flatpak, I guess you already know how to make and release such packages. Already discussed in #363 but the issue has been closed by the requestor while it was not resolved.

Some links:
- https://docs.flatpak.org/en/latest/first-build.html
- https://github.com/flathub/flathub/wiki/App-Submission

**Comment by JoseExposito** [comment]
Hi! 

Unfortunately, it is not possible to distribute Touchégg as a Flatpak because it runs as a systemd daemon and Flatpak doesn't support it.

I don't know which distro you are using, but you can try to request packaging support to them.
