### ISSUE TITLE
GDK error updating touchegg from AUR

### ISSUE THREAD

**Issue by haug1** [JoseExposito/touchegg#575]
Trying to update from the AUR I keep getting this error and I'm not sure what to do:

```
/home/main/Downloads/touchegg/src/touchegg-2.0.14/src/utils/color.cpp:25:10: fatal error: gdk/gdk.h: No such file or directory
   25 | #include <gdk/gdk.h>
```

The touch screen also stopped working at some point, I'm not sure when, maybe when I uninstalled `xf86-video-intel`, I'm not sure. Anyway it could be that I uninstalled some dependency I don't know about, but every other GUI program installs and runs fine.

Is it possibly an issue with touchegg? I don't know, please help

**Comment by parkerlreed** [comment]
gdk.h is part of gtk2/gtk3. Make sure you have that installed.

**Comment by JoseExposito** [comment]
As mentioned, you'd need to install GTK 3
