### ISSUE TITLE
Volume config not working

### ISSUE THREAD

**Issue by paoloros97** [JoseExposito/touchegg#576]
Hi!

This is already possible, try this config:

```xml
    <gesture type="SWIPE" fingers="3" direction="UP">
      <action type="RUN_COMMAND">
        <repeat>true</repeat>
        <command>pactl set-sink-volume 0 +10%</command>
        <decreaseCommand>pactl set-sink-volume 0 -10%</decreaseCommand>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="3" direction="DOWN">
      <action type="RUN_COMMAND">
        <repeat>true</repeat>
        <command>pactl set-sink-volume 0 -10%</command>
        <decreaseCommand>pactl set-sink-volume 0 +10%</decreaseCommand>
      </action>
    </gesture>
```

_Originally posted by @JoseExposito in https://github.com/JoseExposito/touchegg/issues/470#issuecomment-797334794_

Hello Jose,
I've tried to use this configuration, but it doesn't work for me :(
I got the following error: 
`Failed to get sink information: No such entity`

Can you help me please?
Thank you :)

**Comment by JoseExposito** [comment]
Have you tried the other workaround suggested? https://github.com/JoseExposito/touchegg/issues/470#issuecomment-797633992

**Comment by paoloros97** [comment]
It works!
Thank you

**Comment by paoloros97** [comment]
This work!
without using `xdotool`


```
<gesture type="SWIPE" fingers="4" direction="UP">
      <action type="RUN_COMMAND">
        <repeat>true</repeat>
        <command>pactl set-sink-volume @DEFAULT_SINK@ +10%</command>
        <decreaseCommand>pactl set-sink-volume @DEFAULT_SINK@ -10%</decreaseCommand>
      </action>
    </gesture>
```

    <gesture type="SWIPE" fingers="4" direction="DOWN">
      <action type="RUN_COMMAND">
        <repeat>true</repeat>
        <command>pactl set-sink-volume @DEFAULT_SINK@ -10%</command>
        <decreaseCommand>pactl set-sink-volume @DEFAULT_SINK@ +10%</decreaseCommand>
      </action>
    </gesture>
