### ISSUE TITLE
Three fingers drag&drop support

### ISSUE THREAD

**Issue by iFederx** [JoseExposito/touchegg#577]
[Feature request]
I know that this feature was requested yet in the past (https://github.com/JoseExposito/touchegg/issues/468)...
Touchegg is wonderfull, but I'd like more if the Mac OS three fingers drag&drop would be natively supported by touchegg.

Is it possible or is there any structural limitation?

**Comment by JoseExposito** [comment]
A buggy implementation of 3 fingers drag&drop could be implemented, but Touchégg doesn't have enough context to do it properly, so I'd prefer to avoid shipping a bad user experience.

The main problem would be pointer acceleration. I'd have to implement a acceleration profile as similar as possible to the one in libinput, but there'd differences and it'd feel weird.

Another problem is HiDPI. Touchégg doesn't know if your screen is "normal" DPI or 4k. In a 4k screen the pointer would move  really slow, leading to a bad user experience or multiple configuration options.

For those reason, I think that libinput or the Wayland compositors are the right place to implement this feature.

**Comment by iFederx** [comment]
Thanks fo your response.
Yes... I agree with you: "the best or nothing" :)

**Comment by daviewales** [comment]
For completeness, `libinput` have [just merged](https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/1042) native functionality for three finger drag!

So, you can get this by cloning the latest `libinput` source and installing as described here:
https://wayland.freedesktop.org/libinput/doc/latest/building.html#building

Then patch it to enable three finger drag by default:

``` diff
diff --git a/src/evdev-mt-touchpad-gestures.c b/src/evdev-mt-touchpad-gestures.c
index be475a69..6681d3e7 100644
--- a/src/evdev-mt-touchpad-gestures.c
+++ b/src/evdev-mt-touchpad-gestures.c
@@ -2328,7 +2328,7 @@ tp_3fg_drag_get_enabled(struct libinput_device *device)
 static enum libinput_config_3fg_drag_state
 tp_3fg_drag_default(struct tp_dispatch *tp)
 {
-       return LIBINPUT_CONFIG_3FG_DRAG_DISABLED;
+       return LIBINPUT_CONFIG_3FG_DRAG_ENABLED_3FG;
 }

 static enum libinput_config_3fg_drag_state
```

You have to log out, then log back in for your system to recognise the fresh `libinput` installation.

I'm not sure what the next steps are to get this properly integrated into distributions.
@JoseExposito, is this something that could be surfaced in the Touchegg settings?
Or does it need to be enabled somewhere else?

**Comment by JoseExposito** [comment]
> I'm not sure what the next steps are to get this properly integrated into distributions.
@JoseExposito, is this something that could be surfaced in the Touchegg settings?
Or does it need to be enabled somewhere else?

It needs to be added to the compositor and to the DE settings.

Touchégg uses its own libinput context (different from the compositor context) and can not affect how the compositor works.

**Comment by luyanfeng** [comment]
You can use Touchégg together with fusuma. I do
