### ISSUE TITLE
Add PPA for jammy errors on key fetch

### ISSUE THREAD

**Issue by mtkraai** [JoseExposito/touchegg#578]
### Describe the bug

Running `sudo add-apt-repository ppa:touchegg/stable` returns errors.  `sudo apt update` reports no GPG key for touchegg PPA repo.

### Expected behaviour

PPA add succeeds, update succeeds, without error.

### Actual behaviour

``` shell
$ sudo add-apt-repository ppa:touchegg/stable
Repository: 'deb https://ppa.launchpadcontent.net/touchegg/stable/ubuntu/ jammy main'
Description:
Latest stable version of Touchégg for all Ubuntu flavours.

Touchégg is an app that runs in the background and transform the gestures you make on your touchpad or touchscreen into visible actions in your desktop. Learn more at https://github.com/JoseExposito/touchegg
More info: https://launchpad.net/~touchegg/+archive/ubuntu/stable
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/touchegg-ubuntu-stable-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/touchegg-ubuntu-stable-jammy.list
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 357, in main
    shortcut.add()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 222, in add
    self.add_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 398, in add_key
    if not all((self.trustedparts_file, self.trustedparts_content)):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 141, in trustedparts_content
    key = self.lpppa.getSigningKeyData()
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 592, in __call__
    response, content = self.root._browser._request(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 429, in _request
    raise error
lazr.restfulclient.errors.ServerError: HTTP Error 500: Internal Server Error
Response headers:
---
connection: close
content-length: 30
content-type: text/plain;charset=utf-8
date: Mon, 25 Apr 2022 22:40:52 GMT
server: gunicorn/19.8.1
status: 500
x-lazr-oopsid: OOPS-466eb28197c8c240d99efcf31c8c3d5e
x-powered-by: Zope (www.zope.org), Python (www.python.org)
x-request-id: 63eaf434-7618-4ab6-9bbd-806f0eac28ec
x-vcs-revision: 1445a2883c2be41f8e3d484e7c1c2b98b0a1caf9
---
Response body:
---
b'GPGKeyTemporarilyNotFoundError'
---

$ sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]             
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [99.4 kB]                                      
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease                                                         
Get:5 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 DEP-11 Metadata [6,628 B]
Get:6 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [19.2 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [6,624 B]
Get:8 https://ppa.launchpadcontent.net/touchegg/stable/ubuntu jammy InRelease [18.1 kB]           
Err:8 https://ppa.launchpadcontent.net/touchegg/stable/ubuntu jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0FCE32AF6B96252
Reading package lists... Done
W: GPG error: https://ppa.launchpadcontent.net/touchegg/stable/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0FCE32AF6B96252
E: The repository 'https://ppa.launchpadcontent.net/touchegg/stable/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

### Your environment

Kubuntu 22.04

**Comment by Zay-Ta** [comment]
"sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C0FCE32AF6B96252"

adding the key manually worked for me, im using Ubuntu 22.04 lts

**Comment by JoseExposito** [comment]
Yes, I think it is similar to:
https://github.com/JoseExposito/touchegg/issues/462

Just trying later worked on the past, it is a internal server error (error 500)

**Comment by mtkraai** [comment]
Thanks for the answers.  I can see that it's not your issue.

The `apt-key` command didn't help for me.  Eventually, it worked, I just kept trying.  Once one command worked, so did the other.

**Comment by niksingh710** [comment]
I got a error saying `gpg: keyserver receive failed: Server indicated a failure`  when I tried to add key manually

**Comment by niksingh710** [comment]
> I got a error saying `gpg: keyserver receive failed: Server indicated a failure` when I tried to add key manually

ignore it just worked after spamming same command thrice

It was giving warning so used [This](https://askubuntu.com/questions/1398344/apt-key-deprecation-warning-when-updating-system)

**Comment by Freemason-12** [comment]
> "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C0FCE32AF6B96252"
> 
> adding the key manually worked for me, im using Ubuntu 22.04 lts

How did you find the key? It's usually on the launchpad website, but not in this case.

**Comment by elvisisvan** [comment]
> <img alt="@vpolimenov" width="20" height="20" src="https://avatars.githubusercontent.com/u/9103498?s=40&amp;v=4">

a guy in that post you linked suggested ```gpg --refresh-keys
``` and it worked for me 
![image](https://user-images.githubusercontent.com/69122770/224910252-b3c16a54-9edc-4b19-b19a-095c29ffdfae.png)

**Comment by elvisisvan** [comment]
> > I got a error saying `gpg: keyserver receive failed: Server indicated a failure` when I tried to add key manually
> 
> ignore it just worked after spamming same command thrice
> 
> It was giving warning so used [This](https://askubuntu.com/questions/1398344/apt-key-deprecation-warning-when-updating-system)


a guy in that post you linked suggested (https://askubuntu.com/a/1410768)
```
gpg --refresh-keys
``` 
and it worked for me 
![image](https://user-images.githubusercontent.com/69122770/224910252-b3c16a54-9edc-4b19-b19a-095c29ffdfae.png)

**Comment by elvisisvan** [comment]
> > I got a error saying `gpg: keyserver receive failed: Server indicated a failure` when I tried to add key manually
> 
> ignore it just worked after spamming same command thrice
> 
> It was giving warning so used [This](https://askubuntu.com/questions/1398344/apt-key-deprecation-warning-when-updating-system)


a guy in that post you linked suggested (https://askubuntu.com/a/1410768)
```
gpg --refresh-keys
``` 
and it worked for me 
![image](https://user-images.githubusercontent.com/69122770/224910252-b3c16a54-9edc-4b19-b19a-095c29ffdfae.png)
