### ISSUE TITLE
Documentation issue: Touché README does not contain the advertised insitlation instructions. 

### ISSUE THREAD

**Issue by mrdunk** [JoseExposito/touchegg#581]
### Describe the bug

Documentation issue:

Readme says:
`Follow the instructions on [the project page](https://github.com/JoseExposito/touche) to install it.`
about Touché however no instillation instructions exist on that page.

### Expected behaviour

Should find instillation instructions.

### Actual behaviour

Do not find instillation instructions.

### Logs

NA

### Your environment

NA

**Comment by mrdunk** [comment]
> there is a button reading "Download on FLATHUB"

Apologies, So there is.
My brain automatically filters images like that; I was looking for the text instructions.

If you want to cater to idiot's like me, a heading `Installation:` or similar before the icon would probably have done it.
On the other hand, i'm probably a dinosaur/edge case that isn't worth worrying about.

Thanks for the fun project!

**Comment by JoseExposito** [comment]
No problem, I'm glad you managed to install it. It also happens to me sometimes, our brain has been trained to ignore ads and other banners, so some times it's easy to miss information.
