### ISSUE TITLE
Using gestures combined with a key stroke

### ISSUE THREAD

**Issue by ClementPinard** [JoseExposito/touchegg#582]
### Is your feature request related to a problem? Please describe

Trying to figure out how to use navigation shortcut with my browser. For example I would love to use three finger swipe to do previous page / next page. However, this is already (rightfully !)taken by window tiling.

One idea that came to mind was to combine a key stroke with a gesture to create a new one. The same way Ctrl + mouse scroll changes the zoom level on many application, having Shift + three finger swipe would be perfect for my navigation problem.

Maybe there's already a way to do that ?

### Describe the solution you'd like

So the ideal solution would have to ignore regular three finger swipe when e.g. shift is pressed, and to look for the implementation for shift+swipe . Optionally, fall back to regular swipe if no implementation of shift+swipe is available.

I have no idea if this is technically possible, but the corresponding touché interface could have a few more entries, like regular swipe or modifier+swipe, with modifiers = ctrl,alt,shift,super

Thanks for your help !

**Comment by JoseExposito** [comment]
This is not possible at the moment, but you can follow 2 different approaches:

- Make 3 fingers swipes on Firefox perform a  different action. In the UI, this is possible by clicking the "+" button, select Firefox and adding Firefox only gestures
- Change the shortcuts to emulate this behaviour, for example, change Firefox back shortcut to Ctrl+Shift+<- and the tiling shortcut Ctrl+<- (with the corresponding animation). Now, shift acts as a gesture modifier.

Option 2 is a bit of a hack... But it works. I don't think the effort of implementing this is worth it.

I hope one of these solutions work for you.

**Comment by ClementPinard** [comment]
thanks for your answer !

First solution would mean losing the window tiling function, which I need for firefox :)

Second solution is interesting ! Indeed with shortkeys extension, it works, thanks !
