### ISSUE TITLE
Show Desktop gesture doesn't restore all windows

### ISSUE THREAD

**Issue by charizard-knows** [JoseExposito/touchegg#583]
Using Gnome on Zorin 16.1
Configured 3 finger swipe down to show desktop which works perfectly, but while desktop is being shown, it doesn't restore all windows as mentioned in the [readme.md](https://github.com/JoseExposito/touchegg#show-desktop-show_desktop)

**Comment by JoseExposito** [comment]
Touchégg tells GNOME to show or hide the desktop. Unfortunately, GNOME doesn't support this action (I don't think it is available on the Shell), so there is not much I can do to fix it.

You can try to open a bug report/feature request on the Mutter project on GitLab and see if they are open to implement it.
