### ISSUE TITLE
touchegg is available as an official Fedora package

### ISSUE THREAD

**Issue by decathorpe** [JoseExposito/touchegg#584]
touchegg has been available from official Fedora package repositories for a few months, and can be installed just with "dnf install touchegg":
https://src.fedoraproject.org/rpms/touchegg

It would be great if the installation instructions here
https://github.com/JoseExposito/touchegg#fedora-centos-rhel-and-derivatives
could be updated to mention that for Fedora 35+, it is no longer necessary to enable third-party repositories.

I also see that the COPR builds for the latest version (2.0.14) have failed, but the official repos already have 2.0.14, so users that enabled your COPR will already have been "switched" to the package from the official Fedora package repositories by now, since they provide a newer version than the COPR.

**Comment by JoseExposito** [comment]
Thanks a lot for the heads up! I didn't know it was available on the official repo. Added to the README file :)
