### ISSUE TITLE
Title: Emacs does  not receive touchegg events

### ISSUE THREAD

**Issue by tvraman** [JoseExposito/touchegg#588]
Description: Emacs, StumpWM, touchegg
I built touchegg  from source on Debian Rodette 
Linux raman9 5.17.11-1rodete2-amd64 #1 SMP PREEMPT Debian
5.17.11-1rodete2 (2022-06-09) x86_64 GNU/Linux
and  started it via systemctl -- it looks healthy and detects the
trackpad on my Linovo X1 Carbon 9.

I'm primarily an Emacs user and use stumpwm as my manager in case the
WM is relevant.

touchegg is running, and loading my config; to test, I created a
minimal config that defines gestures --- three-finger swipe up/down
for  Emacs.

When I perform the gesture Emacs does not receive any events.

I ran touchegg --debug in a shell and it does appear to be detecting
my gestures; the gestures are just not going to emacs.

Separately I also tried the same gestures in an XTerm, and touchegg
correctly reports that they are not mapped for any application which
is correct.

Attaching the touchegg  run log and my touchegg.conf.

Here is the touchegg console log:

touchegg --debug
Touchégg v2.0.14.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/raman/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: Emacs
	Action configured for this gesture
	Starting action
Gesture end detected
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: DOWN
	Gesture performed on app: Emacs
	Action configured for this gesture
	Starting action
Gesture update detected (8.36149%)
Gesture update detected (12.7384%)
Gesture update detected (17.222%)
Gesture update detected (24.0008%)
Gesture update detected (31.4735%)
Gesture update detected (36.9713%)
Gesture update detected (42.896%)
Gesture update detected (52.1302%)
Gesture update detected (63.3392%)
Gesture update detected (74.4949%)
Gesture update detected (88.7464%)
Gesture end detected
  C-c C-c
19:15:33 ~ $ 

<touchégg>
  <settings>
    <property name="composed_gestures_time">0</property>
  </settings>
  
  <application name="Emacs">
    
    <gesture type="SWIPE" fingers="3" direction="UP">
      <action type="SEND_KEYS">Control+v</action>
    </gesture>
    
    <gesture type="SWIPE" fingers="3" direction="DOWN">
      <action type="SEND_KEYS">Alt+v</action>
    </gesture>
  </application>
</touchégg>

**Comment by JoseExposito** [comment]
Closing as duplicated of https://github.com/JoseExposito/touchegg/issues/589
