### ISSUE TITLE
Title: Emacs Cannot See Touchegg Events

### ISSUE THREAD

**Issue by tvraman** [JoseExposito/touchegg#589]
Description: Emacs cannot see touchegg events

OS: Debian Linux 
Laptop Model: Linovo X1 Carbon 9 With Touchpad --- no touch screen

Built touchegg from source and started via systemd.
Minimal configuration to bind 2 gestures to emacs.
Use StumpWM as WM if it matters.

Observation: With three-finger swipe up/down mapped for Emacs,
touchegg detects the hardware on startup and the console touchegg app
reports the gestures; emacs doesn't receive anything.

Console Log:

touchegg --debug
Touchégg v2.0.14.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/raman/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: Emacs
	Action configured for this gesture
	Starting action
Gesture end detected
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: DOWN
	Gesture performed on app: Emacs
	Action configured for this gesture
	Starting action
Gesture update detected (8.36149%)
Gesture update detected (12.7384%)
Gesture update detected (17.222%)
Gesture update detected (24.0008%)
Gesture update detected (31.4735%)
Gesture update detected (36.9713%)
Gesture update detected (42.896%)
Gesture update detected (52.1302%)
Gesture update detected (63.3392%)
Gesture update detected (74.4949%)
Gesture update detected (88.7464%)
Gesture end detected
  C-c C-c
19:15:33 ~ $ 

touchegg.conf in my ~/.config/touchegg directory:

<touchégg>
  <settings>
    <property name="composed_gestures_time">0</property>
  </settings>
  
  <application name="Emacs">
    
    <gesture type="SWIPE" fingers="3" direction="UP">
      <action type="SEND_KEYS">Control+v</action>
    </gesture>
    
    <gesture type="SWIPE" fingers="3" direction="DOWN">
      <action type="SEND_KEYS">Alt+v</action>
    </gesture>
  </application>
</touchégg>

**Comment by JoseExposito** [comment]
`Control_L` should be used instead of `Control`. Try with `Alt_L` as well:
https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys

You can use Touché to avoid configuration issues:
https://github.com/JoseExposito/touche

**Comment by tvraman** [comment]
will try -- though I think the root of the problem is the fact that I am
running emacs-29 (unreleased) and that version apparently wont work with
xinput 
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
