### ISSUE TITLE
name: Bug report

### ISSUE THREAD

**Issue by tvraman** [JoseExposito/touchegg#590]
about: Create a report to help us improve
title:Touchegg And Emacs 29
labels: Emacs-29
Description: TouchEgg Works With Emacs-29 But:

I discovered that if I run touchegg  in the background as a client,
then touchegg events get to Emacs. Is this a bug or feature -- the
touchegg  docs dont  say one needs to run a second touchegg client
process once the daemon is started via systemctl.

---

### Describe the bug

A clear and concise description of what the bug is and how to reproduce it.

### Expected behaviour

Tell us what should happen.

### Actual behaviour

Tell us what happens instead.

### Logs

If required, include logs of the bug:

```
$ touchegg --debug

```

### Your environment

 * Version of Touchégg: Run `touchegg --version` in the terminal to check the version
 * Operating System: Ubuntu, Fedora, Arch Linux...
 * Desktop Environment: Gnome, KDE, Xfce...

**Comment by JoseExposito** [comment]
Hi! A fter installation, a [desktop file](https://github.com/JoseExposito/touchegg/blob/master/installation/touchegg.desktop) should be created and Touchégg will autostart on next boot.

As the usual process of installing software on Linux is install an app and then run it, I don't think special instructions are required.

By the way, closing https://github.com/JoseExposito/touchegg/issues/589 as it looks like you managed to fix it.

**Comment by tvraman** [comment]
José Expósito ***@***.***> writes:

I may not have communicated clearly.

I did install and enable the daemon via systemctl and the daemon is
running. However emacs does not get events from touchegg unless I start
a  client instance of touchegg which is where I was confused. If that is
obvious, then I guess  there is nothing to do here -- but it was not
obvious to me that one needed both 

A: an instance of the touchegg --daemon running as root and 
B: An instance of touchegg the client running as <me>

> Hi! A fter installation, a desktop file should be created and Touchégg
> will autostart on next boot.
>
> As the usual process of installing software on Linux is install an app
> and then run it, I don't think special instructions are required.
>
> By the way, closing #589 as it looks like you managed to fix it.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
