### ISSUE TITLE
Refreshing the old QT4 UI for configuring Touchégg

### ISSUE THREAD

**Issue by mateMathieu** [JoseExposito/touchegg#591]
Hi José,

Would it be possible to refresh the KDE/QT4 configuration interface?
It was way ahead of its time, so I think it would be very nice to dust it and complete it for the current project.
Do you have the time and resources to do this?

I imagine you thought about it, so you might want to share your status about it.

Reference to the original project: https://store.kde.org/p/1132323/
Best

**Comment by JoseExposito** [comment]
There is a new UI available on Flathub:
https://github.com/JoseExposito/touche#readme

I hope it helps :)
