### ISSUE TITLE
Crash when using swipe gesture

### ISSUE THREAD

**Issue by gokeeper** [JoseExposito/touchegg#593]
### Describe the bug
Crash when using swipe gesture

### Expected behaviour

Tell us what should happen.

### Actual behaviour

Tell us what happens instead.

### Logs

If required, include logs of the bug:

```
$ touchegg --debug

gkp@nano-ubuntu:~$ touchegg --debug
Touchégg v2.0.14.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/gkp/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
##start a PINCH gesture
Gesture begin detected
        Gesture information:
                Fingers: 3
                Type: PINCH
                Direction: IN
        Gesture performed on app: Hyper
        Action configured for this gesture
        Starting action
Gesture update detected (2.69802%)
Gesture update detected (3.98594%)
.
.
Gesture update detected (28.5394%)
Gesture update detected (28.6635%)
Gesture end detected
##start a SWIPE gesture
Gesture begin detected
        Gesture information:
                Fingers: 3
                Type: SWIPE
                Direction: LEFT
        Gesture performed on app: Hyper
        Action configured for this gesture
        Starting action
Segmentation fault (core dumped)

### Your environment

 * Version of Touchégg: Run `touchegg --version` in the terminal to check the version
2.0.14
 * Operating System: Ubuntu, Fedora, Arch Linux...
Ubuntu 22.04
 * Desktop Environment: Gnome, KDE, Xfce...
Gnome

<!--
Please, make sure to search for similar bug reports before creating one and to read the FAQ:
https://github.com/JoseExposito/touchegg#faq
-->

**Comment by JoseExposito** [comment]
Hi!

Does it also happen if no action is associated with the gesture? Does it also crash using other swipe gestures, like 4 finger swipes?

If you could share your config it'd help to understand the problem.

**Comment by gokeeper** [comment]
Hi Jose,
Thanks for the prompt reply. I removed the gestures associated with 3 fingers swipe and touchegg no longer crash. Looks like the it have conflict with buildin 3 fingers swipe action? 


	Gesture performed on app: Google-chrome
	No action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: RIGHT

**Comment by JoseExposito** [comment]
>  Looks like the it have conflict with buildin 3 fingers swipe action?

If there is a build-in gesture, you are most likely using Wayland. Most Touchégg actions won't work for you:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

Actions like SEND_KEYS or RUN_COMMAND might work, but otherwise you'll see a lot of crashes.
