### ISSUE TITLE
Program doesnt work on linux mint

### ISSUE THREAD

**Issue by Schweiger-Jacob** [JoseExposito/touchegg#594]
### Describe the bug

I tried installing it (along with touche) both via the app store and with the terminal. The program launched but none of the gestures I set did anything. 
### Expected behaviour

The gestures doing what they were set to 
### Actual behaviour

they don't do anything 
### Logs

If required, include logs of the bug:

```
$ touchegg --debug

```

### Your environment

 * Version of Touchégg: Run `touchegg --version` in the terminal to check the version
 * Operating System: Ubuntu, Fedora, Arch Linux...
 * Desktop Environment: Gnome, KDE, Xfce...
 * Are you using Wayland? If the anwser is yes, please have in mind that [Touchégg is a X11 only tool](https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland)

**Comment by ngiololollo** [comment]
I had the same problem, I found that the libinput-tools package is not installed by default on linux mint. installing it solved it

**Comment by Schweiger-Jacob** [comment]
> I had the same problem, I found that the libinput-tools package is not installed by default on linux mint. installing it solved it

thanks for the tip I will have to try that later

**Comment by alvindera97** [comment]
Just like @ngiololollo said, I had this problem on Ubuntu 22.04 after I switched back to X11. All I had to do was install `libinput-tools` via the command: `sudo apt install libinput-tools --y` on the terminal and shortly after the installation was complete everything started working.

Thanks again @ngiololollo :slightly_smiling_face:

**Comment by JoseExposito** [comment]
Thanks @ngiololollo, closing the issue.

**Comment by XilinJia** [comment]
> I had the same problem, I found that the libinput-tools package is not installed by default on linux mint. installing it solved it

Thank you.  On Xubuntu 22.04, I also need to install libinput-tools saparately.

**Comment by Schweiger-Jacob** [comment]
it turned out that it was already installed. The gestures still do not work
