### ISSUE TITLE
Three fingers dragging

### ISSUE THREAD

**Issue by mvaranda** [JoseExposito/touchegg#595]
### Three Fingers dragging configuration

Thanks so much for maintaining this project. Before I dig in the code I would like to know if there is out of the box 3 fingers dragging feature (click/hold/move/release emulation). If so then what would its configuration look like. Thanks in advance.

**Comment by JoseExposito** [comment]
Hi,

Touchégg is not the right place to implement this. The Wayland compositor or libinput should implement it for the reasons explained here:
https://github.com/JoseExposito/touchegg/issues/577

**Comment by mvaranda** [comment]
Thanks Jose. I just realized that GNOME 's double-touch and holding (on the second touch) emulates left-click/hold. Thanks for the reply and the good work.
