### ISSUE TITLE
No action on 3 fingers SWIPE

### ISSUE THREAD

**Issue by sebastienmorand-loreal** [JoseExposito/touchegg#596]
### Describe the bug

The 3 fingers SWIPE is detected in the debug mode but no action is happening.

### Expected behaviour

Switch desktop, here is my configuration:
<touchégg>
  <settings>
    <property name="animation_delay">150</property>
    <property name="action_execute_threshold">20</property>
    <property name="color">auto</property>
    <property name="borderColor">auto</property>
  </settings>
  <application name="All">
    <gesture type="SWIPE" fingers="3" direction="DOWN">
      <action type="MINIMIZE_WINDOW">
        <animate>true</animate>
      </action>
    </gesture>
    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="CHANGE_DESKTOP">NEXT</action>
    </gesture>
    <gesture type="SWIPE" fingers="3" direction="RIGHT">
      <action type="CHANGE_DESKTOP">PREVIOUS</action>
    </gesture>
  </application>
</touchégg>

### Actual behaviour

Nothing
### Logs

If required, include logs of the bug:

```
$ touchegg --debug

```
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: LEFT
	Gesture performed on app: Terminator
	Action configured for this gesture
	Starting action
Gesture update detected (0.942124%)
Gesture update detected (1.43053%)
Gesture update detected (1.78573%)
Gesture update detected (2.27413%)
Gesture update detected (2.40734%)
Gesture end detected

### Your environment

 * Version of Touchégg: 2.0.14
 * Operating System: Debian Testing
 * Desktop Environment: XFMW4
 * Are you using Wayland? Nop

**Comment by JoseExposito** [comment]
Hi!

The problem is that the DEB package you are using is compiled against a different version of libinput, see https://github.com/JoseExposito/touchegg/issues/542#issuecomment-948767422 or https://github.com/JoseExposito/touche/issues/63.

Compiling Touchégg locally should fix the issue. Until libinput >= 1.18 hits Debian stable, I'm kind of forced to distribute this package :S
