### ISSUE TITLE
Support: touchegg not working with kinto?

### ISSUE THREAD

**Issue by github-germ** [JoseExposito/touchegg#600]
### Describe the bug

On  Ubuntu 22.04 with kinto using x11 when I run touchegg none of the trackpad gestures are active. Should this work, and if so, what do you suggest to find root cause and fix?

Thanks!!

### Expected behaviour

Trackpad gestures working.

### Actual behaviour

No gestures are working.

### Logs

If required, include logs of the bug:

```
$ touchegg --debug
Reading config from  "/home/XXX/.config/touchegg/touchegg.conf"
Try to make a multitouch gesture. If everything goes well the information about the gesture must appear
[+] Avaliable gesture:
	 Name ->  Flick
[+] Avaliable gesture:
	 Name ->  Drag
[+] Avaliable gesture:
	 Name ->  Pinch
[+] Avaliable gesture:
	 Name ->  Rotate
[+] Avaliable gesture:
	 Name ->  Tap
[+] Avaliable gesture:
	 Name ->  Touch

```

### Your environment
* touchegg 1.1.1-0ubuntu4 (btw, `touchegg --version` does not display the version with my installation?)
* Ubuntu 22.04
* Gnome
* X11
* kinto

**Comment by JoseExposito** [comment]
Hi!

The version of Touchégg you are running is too old. Please uninstall it (`apt remove touchegg`) and install from PPA as described here: https://github.com/JoseExposito/touchegg#ubuntu-debian-and-derivatives
