### ISSUE TITLE
Launchpad PPA does not have a signing key

### ISSUE THREAD

**Issue by Freemason-12** [JoseExposito/touchegg#602]
I wanted to add PPA for touchegg on Debian, but I could not find a signing key:

![image](https://user-images.githubusercontent.com/97738675/196025183-54637bcb-88b1-465b-81f7-a765f52e80cc.png)

**Comment by JoseExposito** [comment]
Hi,

I'd need some help here, as I have no idea how to add a PPA in Debian or if it is even possible.

Some user reported issues with the key:
 - https://github.com/JoseExposito/touchegg/issues/578#issuecomment-1109867038
 - https://github.com/JoseExposito/touchegg/issues/462#issuecomment-786066365

I hope some of those commands help you. A log of the error message could be useful as well.

**Comment by Freemason-12** [comment]
On Debian it works the same as in Ubuntu, the only difference being that the key has to be imported manually like in reports you sent.
It should be displayed in the screenshot part of the site, but it's not there and I have no idea on how some of your reporters found  the key

**Comment by JoseExposito** [comment]
Honestly, I have no idea... Let's see if they tell us how they did it. Closing this issue as I imagine you managed to install it? Otherwise feel free to reopen it.
