### ISSUE TITLE
touchegg not creating systemd service on linux mint 21 and not working when started

### ISSUE THREAD

**Issue by wat9rz** [JoseExposito/touchegg#604]
### Describe the bug
Touchegg doing nothing. No systemD service created

### Expected behaviour
touchegg should start as normal and let me use gestures

Tell us what should happen.
it should have started as normal

### Actual behaviour

nothing happened

### Logs

If required, include logs of the bug:

```
$ touchegg --debug

```

### Your environment

 * Version of Touchégg: Run `touchegg --version` in the terminal to check the version
 * Operating System: Ubuntu, Fedora, Arch Linux...
 * Desktop Environment: Gnome, KDE, Xfce...
 * Are you using Wayland? If the anwser is yes, please have in mind that [Touchégg is a X11 only tool](https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland)

**Comment by JoseExposito** [comment]
You probably need to enable the service:

```
$ sudo systemctl start touchegg
$ sudo systemctl enable touchegg
```

What distro are you using? Did you follow the install intructions?

**Comment by macdeluck** [comment]
Hey, same problem here. Touchegg installed using:
`sudo apt install touchegg`

No sign of touchegg.service created:
![image](https://user-images.githubusercontent.com/5777649/200687448-4440dce9-833e-4db1-9d7a-0f052596a377.png)

``` bash
macdeluck@DELLIONL:~$ sudo systemctl enable touchegg
[sudo] hasło użytkownika macdeluck:           
Failed to enable unit: Unit file touchegg.service does not exist.
```
``` bash
macdeluck@DELLIONL:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa
```

App itself seems to be available:
``` bash
macdeluck@DELLIONL:~$ touchegg
Reading config from  "/home/macdeluck/.config/touchegg/touchegg.conf"
Try to make a multitouch gesture. If everything goes well the information about the gesture must appear
[+] Avaliable gesture:
	 Name ->  Flick
[+] Avaliable gesture:
	 Name ->  Drag
[+] Avaliable gesture:
	 Name ->  Pinch
[+] Avaliable gesture:
	 Name ->  Rotate
[+] Avaliable gesture:
	 Name ->  Tap
[+] Avaliable gesture:
	 Name ->  Touch
```

I hope this helps :)

**Comment by macdeluck** [comment]
Please note that installing ppa as suggested in the guide doesn't work anymore. It says that receiving key failed: no data

``` bash
macdeluck@DELLIONL:~$ sudo add-apt-repository ppa:touchegg/stable
[sudo] hasło użytkownika macdeluck:           
Masz zamiar dodać następujące PPA:
 Latest stable version of Touchégg for all Ubuntu flavours.

Touchégg is an app that runs in the background and transform the gestures you make on your touchpad or touchscreen into visible actions in your desktop. Learn more at https://github.com/JoseExposito/touchegg
 Więcej informacji: https://launchpad.net/~touchegg/+archive/ubuntu/stable
Wciśnij Enter, aby kontynuować lub Crtl+C, aby anulować

Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.EoiFVtjtFb/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys ********************************
gpg: odbiór z serwera kluczy nie powiódł się: Brak danych
```

**Comment by JoseExposito** [comment]
@macdeluck you installed the version available in the official Ubuntu repo, which is very outdated, and won't work with the current input stack. You'd need to `sudo apt remove touchegg` and install from PPA as explained in the [readme](https://github.com/JoseExposito/touchegg#ubuntu-debian-and-derivatives).

If you experiment issues with the key using the PPA, some users reported this as a fix:
https://github.com/JoseExposito/touchegg/issues/578#issuecomment-1109867038

**Comment by macdeluck** [comment]
Hey @JoseExposito,
thanks, this + `systemctl` commands you've sent before indeed helped.
![image](https://user-images.githubusercontent.com/5777649/200943868-39697fbe-437e-44c1-b4d9-4e297eec2070.png)

Then - there is only still this warning after applying solution mentioned in #578.

``` bash
macdeluck@DELLIONL:/etc/systemd$ sudo apt update
Stary:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Stary:2 http://archive.ubuntu.com/ubuntu jammy InRelease                       
Ign.:3 https://ftp.icm.edu.pl/pub/Linux/dist/linuxmint/packages vanessa InRelease
Stary:4 http://ppa.launchpad.net/touchegg/stable/ubuntu jammy InRelease        
Stary:5 https://ftp.icm.edu.pl/pub/Linux/dist/linuxmint/packages vanessa Release
Stary:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease               
Stary:7 https://packages.microsoft.com/repos/edge stable InRelease             
Stary:8 https://dl.winehq.org/wine-builds/ubuntu jammy InRelease               
Stary:9 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease       
Stary:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Stary:11 https://packages.microsoft.com/repos/code stable InRelease
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności... Gotowe
Odczyt informacji o stanie... Gotowe   
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: http://ppa.launchpad.net/touchegg/stable/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```
Is there any workaround for that one too?

**Comment by JoseExposito** [comment]
It looks like the key location changed in Ubuntu 22.04, I didn't test it, but this looks like the solution:
https://askubuntu.com/questions/1403556/key-is-stored-in-legacy-trusted-gpg-keyring-after-ubuntu-22-04-update
