### ISSUE TITLE
OpenRC support

### ISSUE THREAD

**Issue by psammarco** [JoseExposito/touchegg#605]
Hello,

is the program systemd dependent? If not, I could try and port it to Gentoo.

Thanks

**Comment by sodface** [comment]
Hi @psammarco you could take a look at:
https://git.alpinelinux.org/aports/tree/community/touchegg

Which uses openrc and `-DUSE_SYSTEMD=off` in the APKBUILD.

**Comment by JoseExposito** [comment]
Hi! Like @sodface mentioned, there is a build option to avoid installing systemd related files.

In addition, it looks like some progress were made here:
https://bugs.gentoo.org/541448

Touchégg has a client/server architecture:
- The server (`touchegg --daemon`) is run as part of the "input" group so it has access to raw data from input devices. This is the reason why systemd is used: https://github.com/JoseExposito/touchegg/blob/master/installation/touchegg.service.in#L7
- The client (`touchegg`) can run without privileges

You'd need to figure out how to give permissions to the server process in Gentoo. Let me know if you manage to do it, I'll add the install instructions to the readme file.

**Comment by psammarco** [comment]
I will give it a try and report back. Thanks

**Comment by psammarco** [comment]
Initial ebuild now available on my [overlay](https://github.com/psammarco/latrina/tree/master/x11-misc/touchegg).

So far I have just been working on getting the ebuild to compile, and so I have yet to see if the program actually works. I know portage show emerge it now. Will do some testings tomorrow.

**Comment by psammarco** [comment]
Also, systemd USE needs to be implemented in order to add compatibility with systemd.

**Comment by psammarco** [comment]
Right, I am going to ask a couple of questions as I am not quite sure what to expect from the program behavior itself.

I am able to install the the program, start it as daemon using OpenRC, and the touchegg binary seems to start in client mode, but no UI is shown. 

```
pietro@toilet ~ $ sudo rc-service touchegg status
 * status: started
pietro@toilet ~ $ touchegg 
Touchégg v2.0.14.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/usr/share/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
^C
pietro@toilet ~ $ 
```
How would you execute the program in UI mode? Should the touchegg binary itself bring up the gtk based UI?

Regards

**Comment by JoseExposito** [comment]
> I am able to install the the program, start it as daemon using OpenRC, and the touchegg binary seems to start in client mode

Those logs look really good, I think you managed to get it working :tada: 

> How would you execute the program in UI mode? Should the touchegg binary itself bring up the gtk based UI?

No, Touché (the UI) is an standalone app and it can be installed from Flathub:
https://github.com/JoseExposito/touche#readme

It looks like Flatpak is [supported on Gentoo](https://flatpak.org/setup/Gentoo), so no extra work is required on that front.

**Comment by psammarco** [comment]
> > How would you execute the program in UI mode? Should the touchegg binary itself bring up the gtk based UI?
> 
> No, Touché (the UI) is an standalone app and it can be installed from Flathub: https://github.com/JoseExposito/touche#readme
> 
Oh I see, fair enough. And does the touchegg required the Touché app for it to work? 

Also, can you confirm all of these deps are needed to build touchegg? I want to make sure I am not adding unneeded stuff to the final ebuild.

```
        dev-util/cmake
	dev-libs/libinput
	dev-libs/pugixml
	x11-libs/cairo
	x11-libs/libX11
	x11-libs/libXtst
	x11-libs/libXrandr
	x11-libs/libXi
	dev-libs/glib:2
	x11-libs/gtk+:3
	virtual/libudev
```
Lastly, would it work on x11-libs/gtk+:2?

Thanks

**Comment by JoseExposito** [comment]
> does touchegg require the Touché app for it to work?

No, it is not required. Touchégg can be configured by editing a plain text file. The GUI just helps with the configuration making it easier.

> Also, can you confirm all of these deps are needed to build touchegg?

You can check the Debian/Ubuntu dependencies [here](https://github.com/JoseExposito/touchegg/blob/master/debian/control#L5) and the Fedora ones [here](https://github.com/JoseExposito/touchegg/blob/master/rpm/touchegg.spec#L11). I think that your list is accurate.

> One more thing, would it work on x11-libs/gtk+:2?

I don't think so. GTK 3 is used only to choose a color depending on the theme used by the system. Here is a little demo:
https://twitter.com/Jose__Exposito/status/1328760948732071940

However, if for some reason GTK 3 is not available, you can set the [AUTO_COLORS build option](https://github.com/JoseExposito/touchegg/blob/master/CMakeLists.txt#L68) to false and GTK won't be used.

**Comment by psammarco** [comment]
Right, it is mostly all sorted. I think it is decent enough to bring it up to the Gentoo devs for upstream support.

I am just not sure what to do with the Touche' app. I am not a big fan of Flatpak as it completely defeats the purpose of using  a source based distribution. I am wondering if I should package it as well.

**Comment by JoseExposito** [comment]
Cool! Thanks for working on it. Let me know if it get included upstream to add the install instructions, please.

**Comment by haarp** [comment]
Hey, fwiw, I made another ebuild with some changes. It's on my overlay, Zugaina should update with the -r1 soon: https://gpo.zugaina.org/x11-misc/touchegg

The upstream effort doesn't seem to be going ahead as well. It's overlays only for now.
