### ISSUE TITLE
swiping from a side when swiping started from another side is not recognised

### ISSUE THREAD

**Issue by DIDIK3V1** [JoseExposito/touchegg#606]
When I swipe with 4 fingers from the left on my touch pad I trigger the "alt tab menu" (display activity windows in a circle rotating from left to right)
The "shift alt tab menu" is activated when i swipe from the right. (display activity windows in a circle rotating from right to left).

But when I use it, if i've gone too far I can't go back to the previous windows on the menu without stopping the swipe.

The Expected behaviour would be that the swipe on the same axis should be recognized even if the other side was triggered be

Tell us what should happen.

$ touchegg --debug

Gesture begin detected
        Gesture information:
                Fingers: 4
                Type: SWIPE
                Direction: RIGHT
        Gesture performed on app: konsole
        Action configured for this gesture
        Starting action 
//SWIPING FROM THE RIGHT
Gesture update detected (1.74647%)
Gesture update detected (2.50087%)
Gesture update detected (4.28988%)
Gesture update detected (6.4453%)
Gesture update detected (7.11349%)
Gesture update detected (9.41979%)
Gesture update detected (9.78622%)
Gesture update detected (12.3512%)
Gesture update detected (14.5928%)
Gesture update detected (15.7999%)
Gesture update detected (18.3002%)
Gesture update detected (19.9167%)
Gesture update detected (20.628%)
Gesture update detected (23.0852%)
Gesture update detected (23.4732%)
Gesture update detected (25.995%)
Gesture update detected (28.1505%)
Gesture update detected (29.2928%)
Gesture update detected (31.6207%)
Gesture update detected (33.5175%)
Gesture update detected (34.6599%)
Gesture update detected (36.1686%)
Gesture update detected (36.6213%)
Gesture update detected (39.0138%)
Gesture update detected (41.0615%)
Gesture update detected (42.2254%)
Gesture update detected (44.1868%)
Gesture update detected (44.6395%)
Gesture update detected (46.9458%)
Gesture update detected (48.5624%)
Gesture update detected (49.3168%)
Gesture update detected (51.0411%)
Gesture update detected (52.4206%)
Gesture update detected (53.2612%)
Gesture update detected (54.5544%)
Gesture update detected (54.9855%)
Gesture update detected (56.365%)
Gesture update detected (57.3781%)
Gesture update detected (57.7876%)
Gesture update detected (58.7144%)
Gesture update detected (59.3395%)
Gesture update detected (59.6197%)
Gesture update detected (60.1586%)
Gesture update detected (60.2663%)
Gesture update detected (60.5681%)
Gesture update detected (60.8483%)
Gesture update detected (60.8914%)
Gesture update detected (60.9776%)
Gesture update detected (61.0423%)
Gesture update detected (61.0423%)
Gesture update detected (61.1285%)
Gesture update detected (61.2147%)
Gesture update detected (61.2578%)
Gesture update detected (61.3009%)
Gesture update detected (61.3872%)
Gesture update detected (61.4734%)
Gesture update detected (61.538%)
Gesture update detected (61.5596%)
Gesture update detected (61.6027%)
Gesture update detected (61.6458%)
Gesture update detected (61.6889%)
Gesture update detected (61.7967%)
Gesture update detected (61.926%)
Gesture update detected (62.0122%)
Gesture update detected (62.1631%)
Gesture update detected (62.1847%)
Gesture update detected (62.2062%)
Gesture update detected (62.2493%)
Gesture update detected (62.2709%)
Gesture update detected (62.2493%)
Gesture update detected (62.2062%)
Gesture update detected (62.0769%)
Gesture update detected (61.8398%)
Gesture update detected (61.4734%)
Gesture update detected (60.9345%)
Gesture update detected (60.5465%)
Gesture update detected (59.8137%)
Gesture update detected (59.2102%)
Gesture update detected (58.1756%)
Gesture update detected (57.2056%)
Gesture update detected (56.6021%)
Gesture update detected (55.1364%)
Gesture update detected (53.7138%)
Gesture update detected (52.6146%)
Gesture update detected (50.6962%)
Gesture update detected (50.028%)
Gesture update detected (47.6571%)
Gesture update detected (45.5879%)
Gesture update detected (44.6395%)
Gesture update detected (42.2901%)
Gesture update detected (40.0915%)
Gesture update detected (38.906%)
Gesture update detected (36.8584%)
Gesture update detected (36.2333%)
Gesture update detected (33.6468%)
Gesture update detected (31.6423%)
Gesture update detected (31.4483%)
Gesture update detected (29.0988%)
Gesture update detected (27.0296%)
Gesture update detected (26.3615%)
Gesture update detected (24.1845%)
Gesture update detected (23.7965%)
Gesture update detected (21.3178%)
Gesture update detected (18.6881%)
Gesture update detected (17.8906%)
Gesture update detected (15.9292%)
Gesture update detected (13.7738%)
Gesture update detected (13.1487%)
//SWIPING LEFT
Gesture update detected (11.1872%)
Gesture update detected (9.44135%)
Gesture update detected (8.88094%)
Gesture update detected (7.1997%)
Gesture update detected (6.89794%)
Gesture update detected (5.13049%)
Gesture update detected (3.60014%)
Gesture update detected (3.21216%)
Gesture update detected (1.46627%)
Gesture update detected (1.27228%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
Gesture update detected (0%)
//RELEASING
Gesture end detected

### Your environment

 * Version of Touchégg: Touchégg v2.0.14
 * Operating System: Manjaro
 * Desktop Environment: KDE
 * Are you using Wayland? no

**Comment by JoseExposito** [comment]
This is weird, it looks like you are swiping left here:

```
Gesture update detected (60.5465%)
Gesture update detected (59.8137%)
Gesture update detected (59.2102%)
Gesture update detected (58.1756%)
Gesture update detected (57.2056%)
Gesture update detected (56.6021%)
```

Rather than here:

```
Gesture update detected (13.7738%)
Gesture update detected (13.1487%)
//SWIPING LEFT
Gesture update detected (11.1872%)
```

Could you double check that the percentage decreases only when you , please?

Also, I noticed that your trace didn't reach the 100% of the gesture. Could you run the following command and check if [this happens](https://github.com/JoseExposito/touchegg#daemon-configuration), please?

```
$ sudo journalctl -u touchegg -b
```
