### ISSUE TITLE
No response to gestures when using the example configuration

### ISSUE THREAD

**Issue by xiaoshihou514** [JoseExposito/touchegg#607]
### Describe the bug

No response to gestures when using the example configuration

### Expected behaviour

Workspace changes when swiped

### Actual behaviour

No response 

### Logs
Launching touchegg from terminal(kitty):

```
$ touchegg --debug
Touchégg v2.0.13.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/xiaoshihou/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 4
		Type: SWIPE
		Direction: LEFT
	Gesture performed on app: kitty
	No action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 4
		Type: SWIPE
		Direction: RIGHT
	Gesture performed on app: kitty
	No action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)

```
Configuration File:
```xml
❯ cat .config/touchegg/touchegg.conf 
<gesture type="SWIPE" fingers="4" direction="LEFT">
  <action type="CHANGE_DESKTOP">
    <direction>next</direction>
    <animate>true</animate>
    <animationPosition>right</animationPosition>
    <color>3E9FED</color>
    <borderColor>3E9FED</borderColor>
  </action>
</gesture>

<gesture type="SWIPE" fingers="4" direction="RIGHT">
  <action type="CHANGE_DESKTOP">
    <direction>previous</direction>
    <animate>true</animate>
    <animationPosition>left</animationPosition>
    <color>3E9FED</color>
    <borderColor>3E9FED</borderColor>
  </action>
</gesture>

<gesture type="SWIPE" fingers="4" direction="DOWN">
  <action type="SHOW_DESKTOP">
    <animate>true</animate>
    <color>909090</color>
    <borderColor>FFFFFF</borderColor>
  </action>
</gesture>
```
libinput version:
`❯ libinput --version`
`1.21.0`

### Your environment

 * Version of Touchégg: Run `touchegg --version` in the terminal to check the version
 `Touchégg v2.0.13.`
 * Operating System: Ubuntu, Fedora, Arch Linux...
 `void linux`
 * Desktop Environment: Gnome, KDE, Xfce...
 `xfce (xfce4-session-4.16.0_2,xfwm4-4.16.1_1)`
 * Are you using Wayland? If the anwser is yes, please have in mind that [Touchégg is a X11 only tool](https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland)
`No`

**Comment by JoseExposito** [comment]
Have a look to the defaul config:
https://github.com/JoseExposito/touchegg/blob/master/installation/touchegg.conf

Your configuration is missing a bunch of tags. I'd suggest to copy that config and use Touché to edit it:
https://github.com/JoseExposito/touche

It is easier than manually editting the config.

**Comment by xiaoshihou514** [comment]
Thank you for your quick answer!
