### ISSUE TITLE
Pinch to zoom on Microsoft edge

### ISSUE THREAD

**Issue by giulioturrisi** [JoseExposito/touchegg#609]
Hi, i would like to ask if the compatibility with Microsoft edge could be added! For now i'm not able to zoom in/out with the touchpad on that browser, but with Google Chrome there is no problem

**Comment by JoseExposito** [comment]
You can add it yourself easily installing Touché:
https://github.com/JoseExposito/touchegg#using-touch%C3%A9

And using the same configuration that is already available for Chrome.

Feel free to share your config (~/.config/touchegg/touchegg.conf) and I'll include Edge by default.

**Comment by JoseExposito** [comment]
Oh! And feel free to add any comments here, even if the issue is closed, if you have problems with the installation or configuration.
