### ISSUE TITLE
SHOW_DESKTOP 显示桌面后就无法再让桌面回来了

### ISSUE THREAD

**Issue by luyanfeng** [JoseExposito/touchegg#610]
SHOW_DESKTOP  显示桌面后就无法再让桌面回来了？

 我用的touche 
![图片](https://user-images.githubusercontent.com/5779510/210496563-d1011a09-99cb-4715-9858-bad0806a03c0.png)

**Comment by luyanfeng** [comment]
我想让应用和桌面可以来回切换

**Comment by JoseExposito** [comment]
Hi,

I'm afraid I don't speak Chinese, so I'm doing my best with Google translate. If possible, reply in English, please.

The show desktop action hides all windows. Restoring them back is up to your desktop environment. The last time I checked, KDE worked really nice, but GNOME was not able to restore the windows.

> 我想让应用和桌面可以来回切换

If the translation is correct, I think that you want to use this action to switch between desktops, check the animated GIF to have a quick idea:
https://github.com/JoseExposito/touchegg#switch-desktopsworkspaces-change_desktop
