### ISSUE TITLE
Every time logging in, it notifies that "Touchegg is not installed" even when it has been uninstalled

### ISSUE THREAD

**Issue by NeumoNeumo** [JoseExposito/touchegg#617]
### Describe the bug

I have already uninstalled Touchegg. However, every time I log in, there is a notification titled "Touchegg is not install " reminding me that "Please install touchegg to enable multi-touch gesture". It seems that I did not uninstall Touchegg totally.
![image](https://user-images.githubusercontent.com/107997665/218275867-33a54a2b-9d35-4e01-8972-2ff927642cd1.png)
![image](https://user-images.githubusercontent.com/107997665/218275898-f2ec6cd6-6441-4617-9df6-28885c74e9aa.png)

How to reproduce: 
```bash
sudo apt install touchegg
```
and then unintall it by
```bash
sudo apt purge touchegg
```
Then use `super+L` to log out and then log in. ( Or reboot and log in)

### Expected behaviour

There is not such a notification when I log in.

### Actual behaviour

There is such a notification every time I log in.

### Logs

The tail of "syslog" is as follows:
```
Feb 12 02:38:47 yuan-Inspiron-5409 gnome-shell[1782]: [x11gestures@joseexposito.github.io] Reconnecting to Touchégg daemon in 5 seconds
Feb 12 02:38:48 yuan-Inspiron-5409 gnome-shell[1782]: [x11gestures@joseexposito.github.io] Connecting to Touchégg daemon
Feb 12 02:38:48 yuan-Inspiron-5409 gnome-shell[1782]: [x11gestures@joseexposito.github.io] Error connecting to Touchégg daemon: Could not connect: Connection refused
Feb 12 02:38:48 yuan-Inspiron-5409 gnome-shell[1782]: [x11gestures@joseexposito.github.io] Reconnecting to Touchégg daemon in 5 seconds
Feb 12 02:38:48 yuan-Inspiron-5409 gnome-shell[1782]: [x11gestures@joseexposito.github.io] Connecting to Touchégg daemon
Feb 12 02:38:48 yuan-Inspiron-5409 gnome-shell[1782]: [x11gestures@joseexposito.github.io] Error connecting to Touchégg daemon: Could not connect: Connection refused
Feb 12 02:38:48 yuan-Inspiron-5409 gnome-shell[1782]: [x11gestures@joseexposito.github.io] Reconnecting to Touchégg daemon in 5 seconds
Feb 12 02:38:52 yuan-Inspiron-5409 gnome-shell[1782]: [x11gestures@joseexposito.github.io] Connecting to Touchégg daemon
Feb 12 02:38:52 yuan-Inspiron-5409 gnome-shell[1782]: [x11gestures@joseexposito.github.io] Error connecting to Touchégg daemon: Could not connect: Connection refused
Feb 12 02:38:52 yuan-Inspiron-5409 gnome-shell[1782]: [x11gestures@joseexposito.github.io] Reconnecting to Touchégg daemon in 5 seconds
```

I have already uninstalled Touchegg. So I cannot run the following command.
```
$ touchegg --debug
```
Additional information
```
$ sudo apt list --installed | grep touchegg 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```
which means I have actually uninstalled touchegg by apt.

### Your environment

 * Version of Touchégg: Run `touchegg --version` in the terminal to check the version
 * Operating System: Ubuntu 22.04.1 LTS x86_64
 * Desktop Environment: GNOME 42.5 
 * Are you using Wayland? No, I am using x11

### What I tried
According to [this post](https://forum.manjaro.org/t/error-connecting-to-touchegg-daemon-could-not-connect-connection-refused/79926), I 
a) removed my Touchegg config file "~/.config/touchegg", 
b) and I ran "systemctl disable --now touchegg" (however got "Failed to disable unit: Unit file touchegg.service does not exist."), 
c) and finally checked my x11 related files in the home directory, which are ".xinitrc"(empty file) and ".xinputrc"(only one line "run_im fcitx5") 
However, these efforts did not fix the problem.

**Comment by JoseExposito** [comment]
Hi!

That notification is displayed by this GNOME Shell extension:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures

Make sure to remove it to get rid of the notification.
