### ISSUE TITLE
Suggestion :) of Wacom touch disable/enable based on the pen near/far 

### ISSUE THREAD

**Issue by BSalem** [JoseExposito/touchegg#619]
Sorry it's not related to this project, however, I can tell that the libinput daemon you wrote for the gesture can be modified for a nice job with Wacom tablets since you look interested in this area...

One of the major real annoying to all wacom users, that the touch screen is made by the manufacturer to be enabled and disabled by a button on the tablet itself, while the idea from gestures and pen, is accuracy and efficiency!

So, I was always thinking of libinput daemon that runs in the background, watches the pen, if the pen is moving, the touch is disabled so the hand doesn't mess with the pen drawing and actions while the palm is resting on the tabled while painting, if the pen is not detected to be moving, then the touch immediately gets enabled.

This way, when the mouse is being used, the hand touch on the board doesn't interfere with the pen works, and when the pen is up, the tablet works nicely as a touch pad with gestures

**Comment by JoseExposito** [comment]
Hi!

I don't own one of those devices, but from reading issue reports in libinput's bug tracker, I believe that touch arbitration is in place and the touchscreen should be disabled once the pen is in proximity.

If you run `sudo libinput debug-events --verbose`  you should see `touch-arbitration: activated for X <-> Y` where X and Y are the names of your devices.

There might be an issue with your tablet. Feel free to attach the output of `sudo libinput debug-events --verbose` or even better create a new issue in libinput.
