### ISSUE TITLE
Can't use swipe 3 finger or 4 finger after upgrade to Gnome 44

### ISSUE THREAD

**Issue by 1stGuardian** [JoseExposito/touchegg#622]
### Describe the bug

As long as i still on gnome 43, 3-finger swipe left and right can be used to switch workspaces. However after upgrading to gnome 44 it doesn't work anymore (all swipe with 3-finger and 4-finger can't be used).

### Expected behaviour

It should work again like it was still on gnome 43

### Logs

```
$ touchegg --debug
Touchégg v2.0.16.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/firstguardian/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: LEFT
	Gesture performed on app:
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: RIGHT
	Gesture performed on app:
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app:
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: PINCH
		Direction: IN
	Gesture performed on app: org.gnome.Nautilus
	Action configured for this gesture
	Starting action
Gesture update detected (8.73489%)
Gesture update detected (12.9049%)
Gesture update detected (16.5431%)
Gesture update detected (19.7881%)
Gesture update detected (23.4302%)
Gesture update detected (26.1503%)
Gesture update detected (28.9516%)
Gesture update detected (31.02%)
Gesture update detected (31.9581%)
Gesture update detected (32.767%)
Gesture update detected (33.3051%)
Gesture update detected (33.7744%)
Gesture update detected (34.5762%)
Gesture update detected (35.5117%)
Gesture update detected (36.5763%)
Gesture update detected (38.1718%)
Gesture update detected (40.0949%)
Gesture update detected (44.1234%)
Gesture update detected (43.9261%)
Gesture end detected
```

### Your environment

 * Version of Touchégg: Touchégg v2.0.16.
 * Operating System: Fedora 38
 * Desktop Environment: Gnome 44
 * Are you using Wayland? Ofc no

**Comment by jawadalkassim** [comment]
+1

**Comment by DaniSeeh** [comment]
Same. I had to rollback to Gnome 43.

Touchegg is still working as custom gestures configured with Touche still worked, but the connection to Gnome via x11 gestures extension seems to be busted.

**Comment by carlossantos74** [comment]
> Same. I had to rollback to Gnome 43.
> 
> Touchegg is still working as custom gestures configured with Touche still worked, but the connection to Gnome via x11 gestures extension seems to be busted.

this seems to be an issue we can track as well.

https://github.com/JoseExposito/gnome-shell-extension-x11gestures/issues/48

**Comment by Fenimoure** [comment]
I've tested that. With 4 fingers I found out gestures are working, but they are working in a very strange way: swipe up/down changes workspaces, swipe left opens overview

**Comment by carlossantos74** [comment]
I've tested another solution that works fine for me.

https://extensions.gnome.org/extension/4245/gesture-improvements/

**Comment by Fenimoure** [comment]
I've also changed settings via Touché and it works fine now. (I've used key combinations to replicate the behaviour of the X11 gestures extension)

**Comment by JoseExposito** [comment]
Sorry for the delay fixing this issue. A new version is available at https://extensions.gnome.org/extension/4033/x11-gestures/ fixing the GNOME Shell extension.
