### ISSUE TITLE
App closing after swipe up

### ISSUE THREAD

**Issue by thalesmaoa** [JoseExposito/touchegg#623]
I've just installed the new elementary OS Horus. Multigesture works natively. However, I'm getting an annoying bug.
Three fingers up enables multitask view. If I make the "up movement"  really slow, no problem arise. If I make it quick, my windows close.

```
$ touchegg --debug
Touchégg v2.0.14.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/thales/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: firefox
	No action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: 
	No action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: Io.elementary.terminal
	No action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: firefox
	No action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)

```
The swipe up is being performed in the up. Despite of stating `No action configured for this gesture`, the app is closing.

```bash
$ touchegg --version
Touchégg v2.0.14.
thales@ThinkPad-P15v-Gen-3-95107790:~$ cat /etc/os-release 
PRETTY_NAME="elementary OS 7 Horus"
NAME="elementary OS"
CPE_NAME="cpe:/o:elementary:elementary_os:7"
VERSION_ID="7"
VERSION="7 Horus"
VERSION_CODENAME=horus
ID=elementary
ID_LIKE="ubuntu debian"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://docs.elementary.io/contributor-guide/feedback/reporting-issues"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
UBUNTU_CODENAME=jammy
UBUNTU_PRETTY_NAME="Ubuntu 22.04.2 LTS"
UBUNTU_NAME="Ubuntu"
UBUNTU_VERSION_ID="22.04"
UBUNTU_VERSION="22.04.2 LTS (Jammy Jellyfish)"
UBUNTU_VERSION_CODENAME=jammy
thales@ThinkPad-P15v-Gen-3-95107790:~$ una
unalias  uname    
thales@ThinkPad-P15v-Gen-3-95107790:~$ uname -a
Linux ThinkPad-P15v-Gen-3-95107790 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by JoseExposito** [comment]
Checking your logs, it doesn't look like Touchégg is closing the app.

The close app action shows an animation like this one: https://github.com/JoseExposito/touchegg#close-a-window-close_window
And I imagine you are not showing it.

Have in mind that 3 fingers tap closes apps in elementary OS multitasking view. Make sure you are not tapping after swiping.

Closing the issue as this is not a Touchégg problem, but feel free to add any comments.

**Comment by thalesmaoa** [comment]
Hi @JoseExposito , appreciate your help. 

> And I imagine you are not showing it.

I presented the full log. Nothing omitted. Besides, I can't see the animation of windows closing.


> Have in mind that 3 fingers tap closes apps in elementary OS multitasking view. Make sure you are not tapping after swiping.

Not at all. Probably some but from Thinkpad, but this doesn't happen in my MacOS or my previous build of elementary in a Inspiron.

I apologize to insist, but let me suppose something:

What if there there is a bug in the Thinkpad touch (I will look in the bios). The way I see to fix it is adding a delay and avoid overlap gestures. Is there a way to perform it?

**Comment by JoseExposito** [comment]
> I presented the full log. Nothing omitted. Besides, I can't see the animation of windows closing.

It doesn't look like a Touchégg bug. There might be an issue with your touchpad sensitivity.

I suspect that, somehow, your touchpad is tapping and closing the app accidentally.

A good way to test it is disabling tap to click in mouse and touchpad settings and checking if you can reproduce the bug. If you can't, it means that an extra tap is sent by your touchpad.

Also, you can run `sudo libinput debug-events --verbose` and see if the tap is happening. I don't have access to a Linux box right now, but, from the top of my head, that command should print a log when you tap.

**Comment by thalesmaoa** [comment]
Hi @JoseExposito , I confirm that three fingers tap doesn't close my windows.
Also, 

```bash
$ sudo libinput debug-events --verbose
[sudo] senha para thales:        
sudo: libinput: comando não encontrado
```

How can I use elementary without libinput?

**Comment by JoseExposito** [comment]
> How can I use elementary without libinput?

You'd need to install the `libinput-tools` package.

> EDIT: In fact, in multitask view, three fingers close the app. In regular view, three fingers doesn't close the app.

Yes, that's what I ment here, sorry if it wasn't clear:

> Have in mind that 3 fingers tap closes apps in elementary OS multitasking view. Make sure you are not tapping after swiping.

That's why I'd give this a try:

> A good way to test it is disabling tap to click in mouse and touchpad settings and checking if you can reproduce the bug. If you can't, it means that an extra tap is sent by your touchpad.

If you disable tap to click and you are not able to close the apps accidentally it means that your touchpad is sending an extra tap.

**Comment by JoseExposito** [comment]
This is not related to Touchégg, you will need to request this feature in Gala: https://github.com/elementary/gala
