### ISSUE TITLE
zooming does not work on brave browser

### ISSUE THREAD

**Issue by dsoum** [JoseExposito/touchegg#624]
### Describe the bug

Zoom in and out with two finger in touch-pad does not work in brave browser. 

### Expected behaviour

it should zoom in and out.

### Actual behaviour

Zooming is not working.

### Logs

If required, include logs of the bug:

```
$ touchegg --debug

```

### Your environment

 * Version of Touchégg: Touchégg v2.0.16.        
 * Operating System: Ubuntu 22.04
 * Desktop Environment: Gnome
 * Are you using Wayland? No 
 * 
Please, make sure to search for similar bug reports before creating one and to read the FAQ:
https://github.com/JoseExposito/touchegg#faq
-->

**Comment by JoseExposito** [comment]
Does you configuration include an entry for Brave? If I remember correctly, the default configuration includes support for Chrome out of the box, but not for Brave. If zoom is working on Chrome, you probably need to configure it.

**Comment by dsoum** [comment]
Yeah I forgot that. Now I added and it is working now. Thanks :)
