### ISSUE TITLE
Sensibility on Ubuntu 23.04

### ISSUE THREAD

**Issue by MichaelToniolo** [JoseExposito/touchegg#627]
### Describe the bug
When I had installed on my Ubuntu 23.04. When swipe up three finger I need to swipe hard to show my Activities.

### Expected behaviour
In Fedora 38 I don't have this "two" hard three finger swipe.

### Actual behaviour
two or three swipe to show Activities T.T

### Logs

If required, include logs of the bug:

```
$ touchegg --debug

```

### Your environment

Touchégg v2.0.16.
Ubuntu 23.04
GNOME 44

**Comment by Nikita-Presnov** [comment]
Support for kde neon and debian 12 with KDE

**Comment by Nikita-Presnov** [comment]
Try to change property value

**Comment by Nikita-Presnov** [comment]
I think it is libinput problem

**Comment by MichaelToniolo** [comment]
Ok I'm using openSUSE right now and touchegg working rightly. I change some values in properties days ago, restart the services and reboot too, that's not work =\ so. When I can I'll see about libinput.
So, how to check libinput?

**Comment by MichaelToniolo** [comment]
I have been tried on Ubuntu 22.04 LTS and the touchegg gesture works ok. Maybe something doesn't works on the non-LTS Ubuntu Versions.

**Comment by Anifyuli** [comment]
I get this problem too. How should I do to solve this problem?

**Comment by JoseExposito** [comment]
Hi, 

Sorry for the long delay looking into this.

> When I had installed on my Ubuntu 23.04. When swipe up three finger I need to swipe hard to show my Activities.

I guess you are using this GNOME Shell extension as well:
https://extensions.gnome.org/extension/4033/x11-gestures/

On Ubuntu, make sure to install from PPA. The deb package is for Debian users and it is compiled against a different version of libinput, which might cause problems.
See  
https://github.com/JoseExposito/touchegg/issues/542#issuecomment-948767422 for more details.


> Ok I'm using openSUSE right now and touchegg working rightly. I change some values in properties days ago, restart the services and reboot too, that's not work =\ 

This looks like a different issue. Is it possible that there is something wrong in your configuration file? Feel free to share it and I'll have a look.

**Comment by Anifyuli** [comment]
> On Ubuntu, make sure to install from PPA. The deb package is for Debian users and it is compiled against a different version of libinput, which might cause problems. See [#542 (comment)](https://github.com/JoseExposito/touchegg/issues/542#issuecomment-948767422) for more details.

I change from '.deb' instalation to from PPA it make my issue solved. Thanks for you explanation, Mister

**Comment by JoseExposito** [comment]
Cool, I'm glad it worked.

**Comment by Nikita-Presnov** [comment]
However it does not solve this problem on debian 12 with kde, please check

**Comment by JoseExposito** [comment]
@Nikita-Presnov try the latest version please:
https://github.com/JoseExposito/touchegg/releases/tag/2.0.17

I have built the Debian package targeting Bookworm, which should solve the issues. I think that in Debian it's possible to install PPAs, but I'm not sure... I'm not a Debian user.

**Comment by Nikita-Presnov** [comment]
Yes, problem solved for Debian also
