### ISSUE TITLE
Chromium and browsers question

### ISSUE THREAD

**Issue by ramita-0** [JoseExposito/touchegg#632]
I installed touchegg because i thought i would be able to go back and forth in the browser (if i swipe 2 fingers to the left, i go one page forward in history, if i swipe 2 fingers to the right, i go 1 page back in history) As it works in windows with touchpads.

Am i missing this feature or is it not supported? If not, are there plans for it? (This issue is not a formal feature request, just asking if this feature exists)

**Comment by JoseExposito** [comment]
It is not possible. Quoting the FAQs: https://github.com/JoseExposito/touchegg#can-i-use-2-finger-swipes-for-web-browser-navigation

Can I use 2 finger swipes for web browser navigation?

No, at least not with Touchégg. It is up to the web browser to implement that feature. You can request this feature in your favourite's web browser bug tracker.
