### ISSUE TITLE
Diagonal swipes

### ISSUE THREAD

**Issue by haarp** [JoseExposito/touchegg#638]
### Is your feature request related to a problem? Please describe

Gestures on other OS can involve diagonal swipes. This opens up open up a lot more flexibility and number of possible gestures.

### Describe the solution you'd like

Diagonal swipe support in Touchegg

### Describe alternatives you've considered

Well, I could live without them, but were's the fun in that? :)

### Additional context

This was previously requested in #138, but that was before the change to libinput, so I think it might be worthwhile to re-explore these now. Other tools like [Gebaar](https://github.com/Coffee2CodeNL/gebaar-libinput) support diagonal swipes with libinput.

Thanks a lot! Touchegg is great :3

**Comment by JoseExposito** [comment]
I experimented with this option, and it is relatively easy to implement, however, while in a big touchpad (like for example the Apple Magic Trackpad) diagonal swipes are reliable, on a normal-sized touchpad  I found myself hitting the wrong gesture frequently.

I think that for most touchpads adding this feature would cause a frustrating experience.

**Comment by haarp** [comment]
I  get your point and you're right. Speaking from experience with Gebaar, it can be hard to hit the right gestures when there's 8 directions.

But shouldn't that choice be up to the user? Maybe they're good at getting gestures right, maybe they have a large touchpad.

Or maybe that don't want to use all directions, but those they do want to use include diagonals. I for one have an application where it would be sensible to have up-left, up-right and downwards defined as swipes.

Of course this is a question as to whether direction thresholds adjust to which directions are defined. If no diagonal swipes are defined, then an up-left swipe should be detected as either an up or left swipe, not ignored as an undefined diagonal swipe.

Anyway, thanks for reading!

**Comment by JoseExposito** [comment]
> I get your point and you're right. Speaking from experience with Gebaar, it can be hard to hit the right gestures when there's 8 directions.
> 
> But shouldn't that choice be up to the user?

Maybe, but I prefer to offer well tested options that I (think that) work rather than dealing with bug reports or causing a "this doesn't work" feeling on users.

While, from the code perspective, this is easy to implement, I don't think it is a good idea to add it.
