### ISSUE TITLE
Touchegg config file reverts back to default after suspend/restart

### ISSUE THREAD

**Issue by ssidd96** [JoseExposito/touchegg#641]
When trying to launch or check touchegg through terminal it throws the following error:

~$ touchegg

Touchégg v2.0.15.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/xxx/.config/touchegg/touchegg.conf"
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error parsing configuration file
Aborted (core dumped)

Running the command "touchegg --debug" gives the same message.

When trying to install the X11 gestures extention it says error and the following message is displayed in the extensions manager app:

"Type name Gjs_utils_Logger_Logger is already registered"

Installing the touchegg appand launching it dosen't open the app and crashes after a minute.

Touchegg was fully functional for a short while. I was able to launch the app and customize the gestures as per my liking and used them. Restarted my system for something else and touchegg stopped working completely. 

 * Version of Touchégg: v2.0.15
 * Operating System: Pop!_OS 22.04 LTS
 * Desktop Environment: Gnome
 * Are you using Wayland? No, using X11 (double checked in terminal)

**Comment by ssidd96** [comment]
The above issue resolved itself automatically after another restart of the system but now I am unable to keep my changes. 

The GUI shows all of the 3 fingers gestures as greyed out and not intractable with the message "Used by GNOME". I edited the .config file found in the "home/.config/touchegg" directory. I removed the gestures used by gnome, after which I could set the gestures I wanted using the touche GUI app. But, after coming back from suspend or restart the config file reverts back to its default setting with all of my customizations removed.

Is there anyway that I can stop this behavior and keep the customizations I want? I am new to linux and any help would be much appreciated.

**Comment by JoseExposito** [comment]
It looks like you are using the X11 extension:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures

This extension reserves to itself 3 finger swipes and writes in the configuration every time you login into your desktop.

It is possible to configure it to use 4 fingers instead of 3, check the "Extensions" app for configuration. Or, if you don't want to use GNOME gestures, you can always uninstall it and manually clean your configuration.

**Comment by ssidd96** [comment]
Thank you for the reply. I did have the extension enabled, maybe that is what was causing the problem. I disabled the extension and enabled the native popOS X11 gestures and also turned off the pop shell. I am not sure which was causing the issue but after disabling the both of them it is working as intended. Thank you once again for your help.

**Comment by JoseExposito** [comment]
I think that Pop_OS! ships Touchégg and the extension by default, so that's probably why it was causing some issues 

I'm glad it is working now, closing the issue.
