### ISSUE TITLE
Touchpad 2-finger swipe left/right not working

### ISSUE THREAD

**Issue by nicon89** [JoseExposito/touchegg#642]
### Describe the bug
Without touchegg when I swipe left/right with 2-fingers on the touchpad I can go through long lines in the browser (and not only browser).
With touchegg installed this feature doesn't work.
As far as I know 2-finger swipes are not supported on the touchpad. Is there a way to get it running?
It works well on touchscreen, but not on the touchpad.

### Expected behaviour
Swipe left <
Swipe right >

### Actual behaviour
Nothing happens.

### Logs
N/A

### Your environment

 * Version of Touchégg: v2.0.16.
 * Operating System: Ubuntu
 * Desktop Environment: KDE
 * Are you using Wayland? No.

**Comment by gnuhead-chieb** [comment]
Have you tried libinput-gestures, a tool with similar functionality?
https://github.com/bulletmark/libinput-gestures

**Comment by JoseExposito** [comment]
> Without touchegg when I swipe left/right with 2-fingers on the touchpad I can go through long lines in the browser (and not only browser).
With touchegg installed this feature doesn't work.
As far as I know 2-finger swipes are not supported

Are you sure installing of uninstall Touchégg changes the way 2 finger scroll works?

Touchégg completely ignores 2 finger scroll and should not change this behaviour at all

**Comment by nicon89** [comment]
That's actually weird - I found this setting to be disabled in KDE... Even though I had it enabled for months.
After re-enabling it works fine... Thank you.
