### ISSUE TITLE
[Suggestion] Back and forward mouse click support

### ISSUE THREAD

**Issue by CheeseFort** [JoseExposito/touchegg#643]
Currently, touchegg supports emulating left, right, and middle mouse clicks as actions. I suggest expanding this to include back and forward mouse button emulation. Back and forward mouse buttons are featured on most middle and high-end mice, and it would be nice to have this functionally on a touchpad. Thanks.

[Mouse with forward and back buttons](https://user-images.githubusercontent.com/24459435/81587407-48543d80-93b7-11ea-9c11-bcfbfa72ecca.png)

**Comment by JoseExposito** [comment]
It is possible to manually edit the XML configuration file and use values 8 and 9 to emulate back and forward. 

Is this a request to add it to the configuration GUI?

**Comment by JoseExposito** [comment]
Documented here: https://github.com/JoseExposito/touchegg#mouse-click-mouse_click

Thanks!!
