### ISSUE TITLE
Failed to add touchegg PPA.

### ISSUE THREAD

**Issue by akki01133** [JoseExposito/touchegg#647]
command `sudo add-apt-repository ppa:touchegg/stable` fails with the following log:

```
Repository: 'Types: deb
URIs: https://ppa.launchpadcontent.net/touchegg/stable/ubuntu/
Suites: mantic
Components: main

Description:
Latest stable version of Touchégg for all Ubuntu flavours.

Touchégg is an app that runs in the background and transform the gestures you make on your touchpad or touchscreen into visible actions in your desktop. Learn more at https://github.com/JoseExposito/touchegg
More info: https://launchpad.net/~touchegg/+archive/ubuntu/stable
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Hit:1 https://repo.extreme-ix.org/ubuntu mantic InRelease
Hit:2 https://repo.extreme-ix.org/ubuntu mantic-updates InRelease          
Hit:3 https://repo.extreme-ix.org/ubuntu mantic-backports InRelease        
Hit:4 https://repo.extreme-ix.org/ubuntu mantic-security InRelease         
Ign:6 https://ppa.launchpadcontent.net/touchegg/stable/ubuntu mantic InRelease 
Err:7 https://ppa.launchpadcontent.net/touchegg/stable/ubuntu mantic Release   
  404  Not Found [IP: 2620:2d:4000:1::3e 443]
Hit:5 https://packagecloud.io/filips/FirefoxPWA/any any InRelease              
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/touchegg/stable/ubuntu mantic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### My Desktop Specifications:
```
OS: Ubuntu 23.10 x86_64 
Host: VivoBook_ASUSLaptop X421EAY_X4
Kernel: 6.5.0-9-generic
DE: GNOME 45.0 
and For sure I am using X11 Windowing System 
```

**Comment by JoseExposito** [comment]
It should be fixed now, could you try again, please?

Closing the issue but if you find any problems feel free to comment or open it again.

**Comment by N-Mi** [comment]
Hi, just added the PPA on Debian stable, got the issue.

`Err :4 https://ppa.launchpadcontent.net/touchegg/stable/ubuntu trixie Release
  404  Not Found [IP : 185.125.190.80 443]
`

`Error: The repository 'https://ppa.launchpadcontent.net/touchegg/stable/ubuntu trixie Release' does not have a Release file.
Notice: Updating from such a repository can't be done securely, and is therefore disabled by default.
Notice: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by JoseExposito** [comment]
Hi @N-Mi 

I'm not a Debian user and I don't know how to add PPAs there, but "trixie" is a Debian release, not an Ubuntu release, so it is expected to be not found.

You'd need to check online how to add PPAs to Debian, it looks like you missed a step.
