### ISSUE TITLE
Can't get it working Pop!_OS

### ISSUE THREAD

**Issue by alextrastero** [JoseExposito/touchegg#650]
### Describe the bug

I can't seem to be able to override 4 finger swipes on Pop OS

I've got X11 gestures (or at least popos's version)
![image](https://github.com/JoseExposito/touchegg/assets/4152819/2a405027-62eb-4b5a-86c2-09f4ae657527)

My touchegg service is running but 4 finger swipe is grayed out
![image](https://github.com/JoseExposito/touchegg/assets/4152819/afc095b8-3a35-4634-af13-4005ef3c451f)

I've also tried editing my custom copy of touchegg.conf, every time I edit and save it overrides it with GNOME_SHELL

```
    <gesture type="SWIPE" fingers="4" direction="UP">
      <action type="SHOW_DESKTOP"></action>
    </gesture>
    <gesture type="SWIPE" fingers="4" direction="DOWN">
      <action type="SHOW_DESKTOP"></action>
    </gesture>
  
<gesture type="SWIPE" fingers="4" direction="UP"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="4" direction="DOWN"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="4" direction="UP"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="4" direction="DOWN"><action type="GNOME_SHELL"></action></gesture>
```

**Comment by JoseExposito** [comment]
Hi!

It looks like COSMIC/System76 ship a fork of my extension to enable gestures on X11:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures

If you disable the extension, you won't be able to use 4 finger swipes to enter the activities view. But if that is what you want, disable the extension, remove the `GNOME_SHELL` action from the configuration file and you'll be able to set your favorite gestures using Touché:
https://github.com/JoseExposito/touche

I don't know if System76 make any change to my software for their OS, so if you keep having issues you can always ask them.

**Comment by alextrastero** [comment]
👍🏼 thanks for the pointer
