### ISSUE TITLE
touchegg crash

### ISSUE THREAD

**Issue by RazoBeckett** [JoseExposito/touchegg#651]
### Describe the bug

When i try 3 or especially 4 finger out it crashes and errors out.

### Expected behaviour
The assigned gesture should happen.

### Actual behaviour
4 finger out it crashes and errors out.

### Logs

Touchégg v2.0.17.
Starting Touchégg in daemon mode
Starting daemon server...
Generating D-Bus introspection data
Creating D-Bus server
Server started at address unix:abstract=touchegg
A list of detected compatible devices will be displayed below:
Compatible device detected:
	Name: ELAN1203:00 04F3:307A Touchpad
	Size: 101.062mm x 51.9062mm
	Calculating start_threshold and finish_threshold. You can tune this values in your service file
	start_threshold: 20.4355
	finish_threshold_horizontal: 358.095
	finish_threshold_vertical: 183.92
New client connection request
New client connected
Client disconnected
Touchégg v2.0.17.
Starting Touchégg in daemon mode
Starting daemon server...
Generating D-Bus introspection data
Creating D-Bus server
Server started at address unix:abstract=touchegg
A list of detected compatible devices will be displayed below:
Compatible device detected:
	Name: ELAN1203:00 04F3:307A Touchpad
	Size: 101.062mm x 51.9062mm
	Calculating start_threshold and finish_threshold. You can tune this values in your service file
	start_threshold: 20.4355
	finish_threshold_horizontal: 358.095
	finish_threshold_vertical: 183.92
New client connection request
New client connected
Client disconnected
libinput error: event26 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
libinput error: event26 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
New client connection request
New client connected
libinput error: event26 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
Client disconnected
New client connection request
New client connected
libinput error: event26 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
Client disconnected
New client connection request
New client connected
Client disconnected
New client connection request
New client connected
Client disconnected
New client connection request
New client connected
Client disconnected
New client connection request
New client connected
Client disconnected
New client connection request
New client connected
Client disconnected
Touchégg v2.0.17.
Starting Touchégg in daemon mode
Starting daemon server...
Generating D-Bus introspection data
Creating D-Bus server
Server started at address unix:abstract=touchegg
A list of detected compatible devices will be displayed below:
Compatible device detected:
	Name: ELAN1203:00 04F3:307A Touchpad
	Size: 101.062mm x 51.9062mm
	Calculating start_threshold and finish_threshold. You can tune this values in your service file
	start_threshold: 20.4355
	finish_threshold_horizontal: 358.095
	finish_threshold_vertical: 183.92
New client connection request
New client connected
libinput error: event21 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
libinput error: event21 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
Client disconnected
libinput error: event21 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
New client connection request
New client connected
libinput error: event21 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
libinput error: event21 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
libinput error: event21 - ELAN1203:00 04F3:307A Touchpad: WARNING: log rate limit exceeded (5 msgs per 24h). Discarding future messages.
Client disconnected
New client connection request
New client connected
Client disconnected
Touchégg v2.0.17.
Starting Touchégg in daemon mode
Starting daemon server...
Generating D-Bus introspection data
Creating D-Bus server
Server started at address unix:abstract=touchegg
A list of detected compatible devices will be displayed below:
Compatible device detected:
	Name: ELAN1203:00 04F3:307A Touchpad
	Size: 101.062mm x 51.9062mm
	Calculating start_threshold and finish_threshold. You can tune this values in your service file
	start_threshold: 20.4355
	finish_threshold_horizontal: 358.095
	finish_threshold_vertical: 183.92
libinput error: event21 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
libinput error: event21 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
libinput error: event21 - ELAN1203:00 04F3:307A Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
Touchégg v2.0.17.
Starting Touchégg in daemon mode
Starting daemon server...
Generating D-Bus introspection data
Creating D-Bus server
Server started at address unix:abstract=touchegg
A list of detected compatible devices will be displayed below:
Compatible device detected:
	Name: ELAN1203:00 04F3:307A Touchpad
	Size: 101.062mm x 51.9062mm
	Calculating start_threshold and finish_threshold. You can tune this values in your service file
	start_threshold: 20.4355
	finish_threshold_horizontal: 358.095
	finish_threshold_vertical: 183.92
New client connection request
New client connected
Client disconnected
Touchégg v2.0.17.
Starting Touchégg in daemon mode
Starting daemon server...
Generating D-Bus introspection data
Creating D-Bus server
Server started at address unix:abstract=touchegg
A list of detected compatible devices will be displayed below:
Compatible device detected:
	Name: ELAN1203:00 04F3:307A Touchpad
	Size: 101.062mm x 51.9062mm
	Calculating start_threshold and finish_threshold. You can tune this values in your service file
	start_threshold: 20.4355
	finish_threshold_horizontal: 358.095
	finish_threshold_vertical: 183.92
New client connection request
New client connected
Client disconnected
New client connection request
New client connected
Client disconnected

```
$ touchegg --debug
Touchégg v2.0.17.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/razobeckett/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 4
		Type: PINCH
		Direction: OUT
	Gesture performed on app: kitty
	Action configured for this gesture
	Starting action
/usr/include/c++/13.2.1/bits/stl_vector.h:1125: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = long unsigned int; _Alloc = std::allocator<long unsigned int>; reference = long unsigned int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

### Your environment

 * Version of Touchégg: Touchégg v2.0.17.
 * Operating System: Artix Linux (OpenRC initsystem)
 * Desktop Environment: DWM
 * Are you using Wayland? : No

**Comment by RazoBeckett** [comment]
I installed it from AUR: touchegg-openrc(as daemon), which downloaded touchegg-nosystemd (actaully touchegg i guess).

**Comment by JoseExposito** [comment]
Hi!

Thanks for the bug report. Could you check if your window manager (DWM) sets the `_NET_WORKAREA` and/or `_NET_CURRENT_DESKTOP` properties, please? I suspect Touchégg is crashing trying to figure out the size of your screen to display an animation.

To check it, please copy and paste the output of `xprop -root`.

**Comment by RazoBeckett** [comment]
$ xprop -root
output:- 
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x240000e
_NET_CLIENT_LIST(WINDOW): window id # 0x60002c, 0x240000e
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x1e00004
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x1e00004
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_WM_NAME, _NET_WM_ICON, _NET_WM_STATE, _NET_SUPPORTING_WM_CHECK, _NET_SYSTEM_TRAY_S0, _NET_SYSTEM_TRAY_OPCODE, _NET_SYSTEM_TRAY_ORIENTATION, _NET_SYSTEM_TRAY_ORIENTATION_HORZ, _NET_WM_STATE_FULLSCREEN, _NET_ACTIVE_WINDOW, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DIALOG, _NET_CLIENT_LIST, _NET_CLIENT_INFO
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0xa0001d
WM_NAME(STRING) = "^c#fcec07^ ^c#ad402a^[ ï\302\207«  Terrain_2.4G ] ^c#a0bf21^[ ó°\302\201¹? 81% ]  ^c#89dceb^[ îª°  Sun, 10.12. | î\302\216\302\204  11:47 AM ] "
AT_SPI_BUS(STRING) = "unix:path=/run/user/1000/at-spi/bus_0,guid=b8716b4f5ef84009741ae249657556e5"
XFree86_DDC_EDID1_RAWDATA(INTEGER) = 0, -1, -1, -1, -1, -1, -1, 0, 6, -81, -108, -126, 0, 0, 0, 0, 3, 30, 1, 4, -91, 38, 22, 120, 3, 112, 117, -109, 88, 90, -108, 41, 32, 80, 84, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -50, -113, -128, -74, 112, 56, -120, 64, 48, 32, -91, 0, 126, -41, 16, 0, 0, 24, -20, 59, -128, -74, 112, 56, -120, 64, 48, 32, -91, 0, 126, -41, 16, 0, 0, 24, 0, 0, 0, -3, 0, 48, -112, -80, -80, 37, 1, 10, 32, 32, 32, 32, 32, 32, 0, 0, 0, -2, 0, 66, 49, 55, 51, 72, 65, 78, 48, 52, 46, 57, 32, 10, 0, -106
_GNOME_BACKGROUND_REPRESENTATIVE_COLORS(STRING) = "rgb(26,25,25)"
XKLAVIER_ALLOW_SECONDARY(INTEGER) = 0
GDK_VISUALS(INTEGER) = 970, 1283
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", "caps:escape"
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 7
Xorg_Seat(STRING) = "seat0"


you are right, how can i fix this ?

**Comment by RazoBeckett** [comment]
Okay I fixed it using dwm-ewmhtags patch: https://dwm.suckless.org/patches/ewmhtags/
