### ISSUE TITLE
Cant edit Touchegg settings because it wont open

### ISSUE THREAD

**Issue by iLlCugino** [JoseExposito/touchegg#653]
Hi,

So I recently reinstalled Pop OS 22.04 LTS with a fresh new install.

Previously I had ToucheGG and I had a gesture modified. Four finger right showed all open windows instead of apps. I remember when I changed this before it was through the ToucheGG app. There is no way for me to open the ToucheGG app to modify this. I've tried through terminal or searching it on the super menu but nothing. I just want to have four finger right show all windows instead of all apps.

According to terminal the app is launched and it works but I just want to modify these settings on it but can seem to open it. Any help would be appreciated. 

Thanks in advance

deskopt@pop-os:~$ touchegg

Touchégg v2.0.15.

Starting Touchégg in client mode

Parsing your configuration file...

Using configuration file "/usr/share/touchegg/touchegg.conf"

Configuration parsed successfully

Connecting to Touchégg daemon...

Connection with Touchégg established

deskopt@pop-os:~$ sudo systemctl restart touchegg && journalctl -u touchegg -b -f

Feb 02 12:11:16 pop-os touchegg[740]: New client connected

Feb 02 12:13:08 pop-os touchegg[740]: Client disconnected

Feb 02 12:39:19 pop-os touchegg[740]: New client connection request

Feb 02 12:39:19 pop-os touchegg[740]: New client connected

Feb 02 12:40:40 pop-os touchegg[740]: Client disconnected

Feb 02 12:41:45 pop-os systemd[1]: Stopping Touchégg Daemon...

Feb 02 12:41:45 pop-os systemd[1]: touchegg.service: Deactivated successfully.

Feb 02 12:41:45 pop-os systemd[1]: Stopped Touchégg Daemon.

Feb 02 12:41:45 pop-os systemd[1]: touchegg.service: Consumed 2.416s CPU time.

Feb 02 12:41:45 pop-os systemd[1]: Started Touchégg Daemon.

Feb 02 12:41:45 pop-os touchegg[51101]: Touchégg v2.0.15.

Feb 02 12:41:45 pop-os touchegg[51101]: Starting Touchégg in daemon mode

Feb 02 12:41:45 pop-os touchegg[51101]: Starting daemon server...

Feb 02 12:41:45 pop-os touchegg[51101]: Generating D-Bus introspection data

Feb 02 12:41:45 pop-os touchegg[51101]: Creating D-Bus server

Feb 02 12:41:45 pop-os touchegg[51101]: Server started at address unix:abstract=touchegg

Feb 02 12:41:45 pop-os touchegg[51101]: A list of detected compatible devices will be displayed below:

Feb 02 12:41:50 pop-os touchegg[51101]: New client connection request

Feb 02 12:41:50 pop-os touchegg[51101]: New client connected

Feb 02 12:41:50 pop-os touchegg[51101]: New client connection request

Feb 02 12:41:50 pop-os touchegg[51101]: New client connected

Feb 02 12:41:54 pop-os touchegg[51101]: Compatible device detected:

Feb 02 12:41:54 pop-os touchegg[51101]: Name: SYNA32A4:00 06CB:CE17 Touchpad

Feb 02 12:41:54 pop-os touchegg[51101]: Size: 111mm x 69mm

Feb 02 12:41:54 pop-os touchegg[51101]: Calculating start_threshold and finish_threshold. You can tune this values in your service file

Feb 02 12:41:54 pop-os touchegg[51101]: start_threshold: 27.1654

Feb 02 12:41:54 pop-os touchegg[51101]: finish_threshold_horizontal: 393.307

Feb 02 12:41:54 pop-os touchegg[51101]: finish_threshold_vertical: 244.488

Feb 02 12:42:28 pop-os touchegg[51101]: New client connection request

Feb 02 12:42:28 pop-os touchegg[51101]: New client connected

**Comment by JoseExposito** [comment]
Are you looking for this app?

https://github.com/JoseExposito/touche

**Comment by iLlCugino** [comment]
I was able to install through flatpak, x11 gnome was giving errors.

Finally fixed thank you so much
