### ISSUE TITLE
Two Finger Tap, Swipe, etc. and Tap controls on touchpad?

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [JoseExposito/touchegg#658]
For my windows, I used to be able to set triple tap on touchpad to pause and play media. Is it possible for you to implement tap controls for the touchpad? If it exists, can it be added to the Touche flatpak GUI? Also, it would be nice to be able to do 2-finger swipes so I can set 2-finger swipes for browser back and front.

**Comment by JoseExposito** [comment]
Unfortunately, it is not possible to implement tap gestures on touchpads.
libinput, the library used by Touchégg under the hood, doesn't support it.

About 2 finger swipe in the browser:
https://github.com/JoseExposito/touchegg?tab=readme-ov-file#can-i-use-2-finger-swipes-for-web-browser-navigation

**Comment by ENTPRESTIGIOUS** [comment]
> Unfortunately, it is not possible to implement tap gestures on touchpads.
libinput, the library used by Touchégg under the hood, doesn't support it.

Damn that sucks.

> About 2 finger swipe in the browser:
https://github.com/JoseExposito/touchegg?tab=readme-ov-file#can-i-use-2-finger-swipes-for-web-browser-navigation

What about for Opera? I don't think it has any right? I mean even for Windows 10, it doesn't have two finger swipe so that's a shame.
