### ISSUE TITLE
Installing touchegg in a proot-distro alias of Debian in Termux

### ISSUE THREAD

**Issue by b9Joker108** [JoseExposito/touchegg#659]
Hi

In Termux , I am endeavouring to launch a XFCE4 GUI, in my proot-distro alias of Debian, with Termux-x11. I have done so, but on my tablet, it isn't very touch friendly. Can I install touchegg in Debian somehow?

Any assistance greatly appreciated.

Thanking you in anticipation
Beauford

**Comment by JoseExposito** [comment]
Hi!

I'm not familiar with Termux, and I'm not sure if Touchégg will work on Android (I have never test it), but the error is:

```
CMake Error at /data/data/com.termux/files/usr/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:35 (file):
  file failed to open for reading (No such file or directory):
```

On my Fedora install, I the file can be found at `/usr/share/cmake/Modules/CMakeDetermineSystem.cmake` (and inside some Flatpak SDKs).

You can try to check if the file is present in a different path:

```
$ find / -name "CMakeDetermineSystem.cmake" 2> /dev/null
```

And create a symlink or try to copy it from a regular Linux distro and see if you are lucky enough to make it work.

I'm afraid I won't be able to help you with this issue as I don't have a way to run Termux.

**Comment by b9Joker108** [comment]
Thank you so much for your response. As it turns out, I don't require Touchégg, as Termux-X11 has built-in functionality to enable touchscreen functionality for the GUI. This works for both launching the GUI of the Termux host environment, and the GUI of chroots. I didn't know this when I began prospecting the Touchégg solution. I learnt much from trying to get Touchégg working in my Debian chroot, so the time and endeavour wasn't a waste. Thank you so much for your code.
