### ISSUE TITLE
How to delete Touchegg properly on Fedora?

### ISSUE THREAD

**Issue by Ph15** [JoseExposito/touchegg#661]
### Describe the bug

I have installed Touchegg on Fedora × Gnome, but have figured out only afterwards that it doesn't work on Wayland.
At every boot, I get an error message telling me that Touchegg doesn't work, which is a bit annoying.

### Expected behaviour

I would expect a clear CLI to delete Touchegg properly or cancel this boot message, but cannot find it.
Is there any instruction I could use?

### Your environment

 * Version of Touchégg: v2.0.16
 * Operating System: Fedora
 * Desktop Environment: Gnome
 * Are you using Wayland? Yes

**Comment by JoseExposito** [comment]
To uninstall the GNOME Shell extension, you can visit the page of the extension and press uninstall:
https://extensions.gnome.org/extension/4033/x11-gestures/

Or use the "Extensions" app (available in GNOME Sotfware) to manage your extensions.

To uninstall Touchégg, open a terminal and run:

```
$ sudo dnf remove touchegg
```

**Comment by Ph15** [comment]
Alright, looks like it worked! Thank you! 🙏
