### ISSUE TITLE
Rotating Compiz desktop cube using drag

### ISSUE THREAD

**Issue by Secret-chest** [JoseExposito/touchegg#665]
### Is your feature request related to a problem? Please describe

I have a tablet, and I want to rotate the Compiz desktop cube without a keyboard.

### Describe the solution you'd like

I want dragging with a certan number of fingers to actually drag with a button and some modifiers (Control+Super+Button1) so it can be used to rotate the desktop cube.

### Describe alternatives you've considered

None.

### Additional context

None

**Comment by JoseExposito** [comment]
You can emulate the keyboard shortcut:
https://github.com/JoseExposito/touchegg?tab=readme-ov-file#keyboard-shortcut-send_keys

But, if you want a better experience (the cube following your fingers rather than a one immediate action) you'd have to request it to the compiz cube developers.

**Comment by Secret-chest** [comment]
> But, if you want a better experience (the cube following your fingers rather than a one immediate action) you'd have to request it to the compiz cube developers.

No, because the cube can be set to be dragged with a specific button.

**Comment by JoseExposito** [comment]
Does swiping with 2 fingers move the cursor in your desktop environment?

If not, this is complicated to implement Touchégg. You would like to be able to emulate a mouse. But mice are relative devices, i.e., they send relative information (moved 10 units to the left and 20 to the bottom) not absolute devices (moved to pixel 150,400).

The mouse pointer is affected by the acceleration profile and by the speed configured in settings. That means that 50 units to the left can be 50 pixels or 100px depending on the mouse speed and how fast you moved it.

With all of this, it is not possible to me to emulate cursor movement in a way that the mouse follows your fingers.

The best option is to request the desktop cube developers to add support for your touchscreen rather than trying to emulate with a third party tool.
If they already have support to move it with the mouse, it should be easy to do the same with a touchscreen.

**Comment by Secret-chest** [comment]
In fact, it does move the cursor.

**Comment by Secret-chest** [comment]
@JoseExposito

**Comment by JoseExposito** [comment]
Which desktop cube are you using? I just tested this GNOME Shell extension:
https://extensions.gnome.org/extension/4648/desktop-cube/

And it works with a touchscreen. Also, is your device a touchscreen or a drawing tablet? I assumed touchscreen, but reading again the bug report description it is not clear.

I emphasize requesting this feature to the desktop cube developers, at the moment, there is no way to perform this with Touchégg. I'm trying to think in ways to implement this in a generic way so all actions can benefit from it, and so far I don't find a good way to implement it.

**Comment by Secret-chest** [comment]
@JoseExposito 

My device is a touchscreen.

I'm using the Compiz cube extension which is shipped with Compiz, in the Mate DE. It can be rotated with the touchscreen, but I have to press a key combination of my choice to enable rotate mode. Since the cursor does move when I drag with multiple fingers, I basically want some modifier keys to be activated while dragging like this.

**Comment by JoseExposito** [comment]
Ok, thanks for the clarification:

>  I basically want some modifier keys to be activated while dragging like this

Have you tried to use the send keys action?

https://github.com/JoseExposito/touchegg?tab=readme-ov-file#keyboard-shortcut-send_keys

If you just need to send the modifiers, that should be enough. Even though I spect a mouse button to be pressed.

If that's the case, at the moment it is not possible. I'll need to implement a way to execute an action on gesture start (a script that presses the keys and mouse button) and another script on gesture end (another script to release everything).

**Comment by Secret-chest** [comment]
A mouse button needs to be pressed to drag, but I think you can release the modifiers after initiating it. I'll check when I can

**Comment by Secret-chest** [comment]
@JoseExposito It does work if I hold Ctrl-Super, then start dragging and release: it will keep dragging. However, I can't make Touchegg do it.

**Comment by Secret-chest** [comment]
The best implementation I can think of is a "drag" gesture type which can specify the mouse button to emulate dragging with (if possible; not necessary) and the modifiers to hold while dragging.

**Comment by Penguin-Guru** [comment]
I have not yet looked at the code for this but I suspect simply separating the button press and release actions would work. This could be a mode for SEND_KEYS' "on" tag-- something like "drag" to include the whole span between "begin" and "end". Another option would be to simply add a DRAG action.

My use-case for this is simply to reposition windows by dragging them while holding a modifier. Maybe that's already possible somehow and I just haven't figured it out yet.

**Comment by JoseExposito** [comment]
I have implemented a solution for your use case in a way that, hopefully, it would be generic enough to cover more use cases. See https://github.com/JoseExposito/touchegg/pull/670:

> Until now, it was only possible to execute the MOUSE_CLICK, SEND_KEYS and RUN_COMMAND actions when the gesture started or when the gesture ended.
>
> Include a third option, <on>begin-and-end</on> allowing to run the actions both when the gesture starts and ends.
>
> When this new setting is used, MOUSE_CLICK starts presses the mouse button when the gesture starts and releases it when the gesture ends.
>
> In the case of RUN_COMMAND, a environment variable is set (TOUCHEGG_GESTURE_ON) allowing the executed script to take different actions at the beginning and the end of the gesture.

For your use case, you could either use the `MOUSE_CLICK` action with `<on>begin-and-end</on>` or, if you need modifiers, use the `RUN_COMMAND` to execute a custom script that, using `xdotool` presses the required mouse and keyboard buttons.

**Comment by Secret-chest** [comment]
Can it use any button ID, or just left, middle, right, back and forwards?

**Comment by Secret-chest** [comment]
I'm going to try it. Can I set any button number, or only 1, 2, 3, 7 and 8?

**Comment by Secret-chest** [comment]
I think it's what I want.

**Comment by JoseExposito** [comment]
You can use any button ID, just set the number in the config file.

**Comment by JoseExposito** [comment]
To keep the conversation in a single place, about your comment in https://github.com/JoseExposito/touchegg/pull/670#issuecomment-2511615911

> It doesn't work; I'd like a new "drag" gesture type. Even if the button is held down, the click position is in the same place, not where the cursor is.

I explicitly asked about this and explained the reason why a "drag" action is not possible to implement. To avoid repeating myself, read this comment again:
https://github.com/JoseExposito/touchegg/issues/665#issuecomment-2463121996

**Comment by Secret-chest** [comment]
I just said it moves the cursor.

**Comment by Secret-chest** [comment]
As an alternative, do you know a way to get the number of fingers touching the screen in shell or python?

**Comment by JoseExposito** [comment]
Touchégg has a client/server architecture. You can write your own client in Python or your favourite language and add custom actions.

An example of a client written in JavaScript:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures

Otherwise, you can use libinput directly and have way more flexibility. This repo is a good example.

**Comment by Penguin-Guru** [comment]
@Secret-chest 

I don't know if this will help you but I got something similar working for moving windows around in i3. My cursor was not moving with gestures so I also made the changes in that pull request above.

My Touchegg config (using "UP" as a simple example):
```
<touchégg>

  <settings>
    <property name="reposition_cursor">GESTURE_UPDATE_AND_END</property>
  </settings>

  <application name="All">
	<gesture type="SWIPE" fingers="2" direction="UP">
		<action type="RUN_COMMAND">
			<repeat>false</repeat>
			<on>begin-and-end</on>
			<command>toggle-drag-window</command>
		</action>
	</gesture>
  </application>

</touchégg>
```

My `toggle-drag-window` script:
```
#!/bin/bash
if [[ "$TOUCHEGG_GESTURE_ON" == 'begin' ]]; then
	toggle-input-device touchscreen off
	xdotool keyup super keydown super mousedown 1
## Ignoring value: "update".
elif [[ "$TOUCHEGG_GESTURE_ON" == 'end' || -z "$TOUCHEGG_GESTURE_ON" ]]; then
	xdotool mouseup 1 keyup super
	toggle-input-device touchscreen on
fi
```

My `toggle-input-device` script is a bit long and might not work for your device but I can share that too if you need it.
